### ISSUE TITLE
Anonymous user can access data ingested by named user

### ISSUE THREAD

**Issue by olavbm** [memgraph/memgraph#1009]
**Memgraph version**
2.8.0

**Environment**
Some information about the environment you are using Memgraph on: operating
system, how do you connect, with or without docker, which driver etc.
 Static hostname: syl
       Icon name: computer-laptop
         Chassis: laptop 💻
      Machine ID: 5551a993327844858c5ccb0787095d5d
         Boot ID: 786b3bba88b746fc80d9f4b2a723e418
Operating System: Debian GNU/Linux 12 (bookworm)
          Kernel: Linux 6.1.0-9-amd64
    Architecture: x86-64
 Hardware Vendor: Lenovo
  Hardware Model: ThinkPad X1 Carbon Gen 10
Firmware Version: N3AET67W (1.32 )

web-gui, localhost:3000

docker:
`docker run -it -p 7687:7687 -p 3000:3000 -e "MEMGRAPH=--bolt-server-name-for-init=Neo4j/5.8.0 --log-level=TRACE --query-execution-timeout-sec=30" -e MGCONSOLE="--username vlasta --password vp"  memgraph/memgraph-platform`

**Describe the bug**
I can access data that is inserted by a user/password combination without logging in myself.

**To Reproduce**
1. `docker run -it -p 7687:7687 -p 3000:3000 -e "MEMGRAPH=--bolt-server-name-for-init=Neo4j/5.8.0 --log-level=TRACE --query-execution-timeout-sec=30" -e MGCONSOLE="--username vlasta --password vp"  memgraph/memgraph-platform`
2. Open your browser and go to localhost:3000. Log in with above credentials under "Connect Manually
3. Insert some data
4. Open a new(incognito) browser and go to localhost:3000 and click connect now.
5. Access data that was ingested without supplying username or password

**Expected behavior**
Getting an error message or no nodes in the graph.

**Logs**
I dont think this is applicable.

**Additional context**
I've asked in ask-kapa-emgraph on discord, Matea | Memgraph asked me to open an issue and also said she consulted with the team.

**Comment by katarinasupe** [comment]
It can maybe be resolved with init flag, whose fix is merged and will be available in Memgraph 2.9 - https://github.com/memgraph/memgraph/issues/975
@olavbm I sent the message on Discord too :)

**Comment by katarinasupe** [comment]
Discussed with @olavbm that init file will resolve such issue, and the fix for that is merged into master. Hence, closing this issue :)

**Comment by olavbm** [comment]
That's great. Is there any way I can test the 2.9 release?

**Comment by katarinasupe** [comment]
Hi @olavbm, since https://github.com/memgraph/memgraph/pull/974 is merged into master, you can build Memgraph from source and test it that way. Instructions to do that can be found here: https://memgraph.notion.site/Memgraph-Internals-12b69132d67a417898972927d6870bd2.
