### ISSUE TITLE
community_detection_online and projections support

### ISSUE THREAD

**Issue by priamai** [memgraph/memgraph#1029]
Hello there,
not a bug but I would like some clarity on the following scenario.
I have a dataset with multiple subgraphs (those are companies with a company id as a property) and each graph contains a relation between employees and rooms.
I want to run the community detection online making sure that it tracks the graph status for each subgraph.
The set method: this is easy I call the method with a subgraph for each company (as a projection).
The get method: it needs a list of modified edges and nodes, but how do I refer that to each subgraph?

Any feedback and examples will be very welcome.

**Comment by katarinasupe** [comment]
Hi @priamai, can you tell me what you are actually tracking in the database when you say 'graph status'? Also, how is the new data being created in the database? Are you streaming data or running queries by yourself? Any more info you can provide will help

**Comment by priamai** [comment]
Sure I can attach all my jupyter here let me try

**Comment by priamai** [comment]
The easiest way is via [colab](https://colab.research.google.com/drive/1gXg8J4gYH2HrjFWG6ZfK4gbg0GjsMHaK?usp=sharing) @katarinasupe hopefully this makes sense.

**Comment by priamai** [comment]
Okay closing this question, I will open a new one I understand the problem and the trigger better now!
