### ISSUE TITLE
Remove repeated lines from TRACE logs

### ISSUE THREAD

**Issue by katarinasupe** [memgraph/memgraph#1041]
`Recovering vertex <ID>` is an unnecessary repeated log line in `TRACE` logs. When a user wants to debug something, they set the log level to `TRACE` and waste resources on `Recovering vertex <ID>` log lines. For example, if there are >10M vertexes, there are >10M log lines for recovering them.  

It would be better to reduce those log lines to something like `Recovering Vertex set <1-1M>`, mainly for large databases.

Related to [Discord discussion](https://discord.com/channels/842007348272169002/1120986856612438127/1121801702463520869).

**Comment by antejavor** [comment]
@gitbuda  I think it is feasible in this case. The question is do we even need that type of logging where recovery progress is stated by each vertex/edge? 
So this is a much better solution: `Recovering vertex set <1-1M>`
