### ISSUE TITLE
Check for logical errors with deletes in replication

### ISSUE THREAD

**Issue by antejavor** [memgraph/memgraph#1048]
Check for logical errors with deletes -> create social network graph and randomly delete an edge in the graph.

This was split from the issue here: https://github.com/memgraph/memgraph/issues/953

**Comment by DavIvek** [comment]
It's been a while since this issue was opened, and a lot of work has been done on the replication side. I have not been able to reproduce the issue recently. Given that we don't have exact steps to reproduce it, should we consider closing this issue? @antejavor

**Comment by antejavor** [comment]
Yep, let's close this one.
