### ISSUE TITLE
Fix flaky tests/e2e/streams/kafka_streams_tests

### ISSUE THREAD

**Issue by gitbuda** [memgraph/memgraph#1053]
Sometimes the test fails under CI, sometimes kafka gets in a faulty state, but this has happened when Kafka was 100% OK

```
cd tests/e2e
ave3
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:../../libs/mgclient/lib python  runner.py \
    --workloads-root-directory . --workload-name "Kafka streams start, stop and show"
```

![Screenshot 2023-06-28 at 1 12 34 PM](https://github.com/memgraph/memgraph/assets/4950251/2634d96f-f2a3-4d54-8855-00b42d73eb1f)

**Comment by antepusic** [comment]
Closing this issue since we fixed it in the initiative to make flaky tests reliable (see on [Slack](https://memgraph.slack.com/archives/CSR01RS80/p1720101199718929)).
