### ISSUE TITLE
Implement recovery of the STORAGE MODE

### ISSUE THREAD

**Issue by gitbuda** [memgraph/memgraph#1057]
Once Memgraph ends up in the storage mode `IN_MEMORY_ANALYTICAL` it should stay in that mode after restart if the recovery part is set properly (data directory, recovery on startup, etc)

**Comment by antejavor** [comment]
We have a +1 on this issue.

**Comment by katarinasupe** [comment]
+1 from the community ([source](https://discord.com/channels/842007348272169002/1186649049747701790/1186914572142125086)).
