### ISSUE TITLE
[BUG] No way to create index via code using Neo4j.Driver.Simple

### ISSUE THREAD

**Issue by smitha-cgi** [memgraph/memgraph#1065]
**Memgraph version**
2.8.0

**Environment**
Memgraph platform running via docker on CentOS 7. C# application on Windows using Neo4j.Driver.Simple 5.9.0

**Describe the bug**
I am unable to create an index via code. I assume this is because the Memgraph create index syntax is different from the standard Neo4j index syntax and so the library is unhappy with the syntax being used and throws a weird exception. 

**To Reproduce**
1. Create a simple node with an id property either via lab or via code: CREATE (n:Location {name: 'San Marino', id: 44})
2. Create an index on the node id property via code using the following syntax: CREATE INDEX ON :Location(id)

Code that creates the index looks something like this:

```
public int CreateIndex(string type, string property)
{
    return Session.ExecuteWrite(tx => CreateIndex(tx, type, property));
}

private int CreateIndex(IQueryRunner tx, string type, string property)
{
    _ = tx.Run(string.Format("CREATE INDEX ON :{0}({1})", type, property), null);

    return 0;
}
```

_Note that running the same command via lab successfully creates the index. I only get the error when running command using the API._

**Expected behavior**
An index is created successfully

**Logs**
Neo4j.Driver.ClientException: 'Index manipulation not allowed in multicommand transactions.'

**Additional context**
I realise there may be nothing that can be done here due to the syntax differences - interested in any workarounds anyone might be able to suggest.

**Comment by smitha-cgi** [comment]
Thanks @katarinasupe - this workaround has solved my problem!

**Comment by katarinasupe** [comment]
Fantastic to hear that @smitha-cgi! :) I will close the issue.

I hope your work with Memgraph is progressing well, and let me know if you have any more questions. Feel free to open an issue for whatever you notice too, but for quicker conversation, [join our Discord server](https://www.discord.gg/memgraph).

**Comment by katarinasupe** [comment]
Fantastic to hear that @smitha-cgi! :) I will close the issue.

I hope your work with Memgraph is progressing well, and let me know if you have any more questions. Feel free to open an issue for whatever you notice too, but for quicker conversation, [join our Discord server](https://www.discord.gg/memgraph).
