### ISSUE TITLE
Fix flaky durability unit test

### ISSUE THREAD

**Issue by gitbuda** [memgraph/memgraph#1097]
Seems like `memgraph__unit__storage_v2_durability_inmemory` sometimes fails as well -> https://github.com/memgraph/memgraph/actions/runs/5610784789/jobs/10266240986?pr=1087 (the logs might be deleted because of the retention policy)

![Screenshot 2023-07-20 at 3 42 22 PM](https://github.com/memgraph/memgraph/assets/4950251/c88b8b9e-851c-4d6a-93ac-31132654f31c)

**Comment by as51340** [comment]
Worked on this but couldn't reproduce the issue. I tried running the test which isolated for N times and whole durability test N times but it never failed. I think what happened is that execution on some machine was very slow or very fast and then Memgraph managed to create more snapshots than what test expects. I really think there is nothing wrong here, but we will see how it will behave in the future.
