### ISSUE TITLE
[BUG] Map projection from NULL values

### ISSUE THREAD

**Issue by ZelvaMan** [memgraph/memgraph#1118]
**Memgraph version**
Memgraph 2.8.0

**Environment**
Using latest docker image 
connected using memgraph lab

**Describe the bug**
According to [documentation](https://memgraph.com/docs/memgraph/reference-guide/data-types#map-projection) map values should be null, when map_variable is null. But when i use All-properties selector it return error
![image](https://github.com/memgraph/memgraph/assets/31016933/2b456b25-ca5b-45c7-8fd2-a2b6e620282c)

**To Reproduce**
You can just run this query
```
OPTIONAL MATCH (node:DOESNT_EXIST)
RETURN node {.*}
```

**Expected behavior**
It should return null

**Logs**
screenshot is above in description

**Additional context**
Thanks for help. If this is indeed intended behavior, I would suggest updating docs to make in obvious.

**Comment by Josipmrden** [comment]
@lomnido the PR associated with the issue is https://github.com/memgraph/memgraph/pull/1119 so you can track it :)
