### ISSUE TITLE
[BUG] cannot build 2.10.0 from source

### ISSUE THREAD

**Issue by lomnido** [memgraph/memgraph#1136]
**Memgraph version**
2.10.0

**Environment**
Ubuntu 22.04, from source

**Describe the bug**
Cannot compile due to error on 'cmake'

**To Reproduce**
mkdir _build
cd _build
cmake ..

**Expected behavior**
complete building process

**Logs**
CMake Error at /usr/local/share/cmake-3.27/Modules/ExternalProject.cmake:3207 (message):
  No download info given for 'spdlog-populate' and its source directory:

   /usr/local/src/memgraph-no-git/memgraph-2.10.0/libs/spdlog

  is not an existing non-empty directory.  Please specify one of:

   * SOURCE_DIR with an existing non-empty directory
   * DOWNLOAD_COMMAND
   * URL
   * GIT_REPOSITORY
   * SVN_REPOSITORY
   * HG_REPOSITORY
   * CVS_REPOSITORY and CVS_MODULE
Call Stack (most recent call first):
  /usr/local/share/cmake-3.27/Modules/ExternalProject.cmake:4376 (_ep_add_download_command)
  CMakeLists.txt:21 (ExternalProject_Add)

-- Configuring incomplete, errors occurred!

CMake Error at /usr/local/share/cmake-3.27/Modules/FetchContent.cmake:1650 (message):
  CMake step for spdlog failed: 1
Call Stack (most recent call first):
  /usr/local/share/cmake-3.27/Modules/FetchContent.cmake:1802:EVAL:2 (__FetchContent_directPopulate)
  /usr/local/share/cmake-3.27/Modules/FetchContent.cmake:1802 (cmake_language)
  /usr/local/share/cmake-3.27/Modules/FetchContent.cmake:2016 (FetchContent_Populate)
  libs/CMakeLists.txt:200 (FetchContent_MakeAvailable)

**Additional context**
Can you please check?

**Comment by gitbuda** [comment]
Hi @lomnido, thanks for reporting!

In this case, Memgraph v2.10 natively builds on Ubuntu 22.04, there are a few things:
1. you need to use Memgraph toolchain -> the right compiler and subset of libraries comes packaged there (easier to install them)
2. running `init` is required

-> toolchain details -> https://memgraph.notion.site/Toolchain-37c37c84382149a58d09b2ccfcb410d7
-> quick start details -> https://memgraph.notion.site/Quick-Start-82a99a85e62a4e3d89f6a9fb6d35626d

briefly the following is required:
1. download the Ubuntu 22.04 toolchain
2. install toolchain and memgraph deps (explain under quick start)
3. `cd memgraph && mkdir build`
4. `source /opt/toolchain-v4/activate`
5. `init`
6. `cd build`
7. `cmake .. && make -j16`

**Comment by lomnido** [comment]
@gitbuda  thank you very much! 
confirming it is now working :smiley:

**Comment by gitbuda** [comment]
Great! Glad you make it work 💪 Closing the issue 😃
