### ISSUE TITLE
Fix 100% CPU usage on the GC thread

### ISSUE THREAD

**Issue by gitbuda** [memgraph/memgraph#1141]
The issue is visible on our CI sometimes -> investigate

**Comment by gitbuda** [comment]
Similar but might not be the same issue (seems like +1 -> investigate):
"A little more light on the 100% CPU issue, I used strace to attach to the process and it’s on an [epoll_wait()](https://man7.org/linux/man-pages/man2/epoll_wait.2.html) loop, not sure if this will help you debug the issue, we continue to have it even on the latest version.
Could this be related to the issues we are having with basic cypher sessions that timeout and run fine after they’re restarted? I haven’t been able to pinpoint the time when the CPU goes into this loop to establish a correlation."

**htop**
![image001](https://github.com/memgraph/memgraph/assets/4950251/539d97eb-16a6-4a37-ace3-6bc4256829f0)

**strace**
![image002](https://github.com/memgraph/memgraph/assets/4950251/0338e5fd-f6c8-40b7-81eb-335c88b36f5b)

**Comment by gvolfing** [comment]
A comment on the `strace` image.
We only use `epoll` explicitly from one place in memgraph, `Listener::WaitAndProcessEvents()` to be precise. And there we specify `maxevents` (the 3rd argument) to be always `1`.
These calls to `epoll_wait()` are probably called by something else we use, likely some `asio` related stuff.
