### ISSUE TITLE
Unable to install memgraph 2.7 on rhel 8

### ISSUE THREAD

**Issue by mehdibad** [memgraph/memgraph#1160]
I have an issue installing memgraph 2.7 on rhel 8 kernel 4.18.0-477.13.1.el8_8.x86_64
rpm -ivh memgraph-2.7.0_1-1.x86_64.rpm
error: Failed dependencies:
        libcrypto.so.10()(64bit) is needed by memgraph-2.7.0_1-1.x86_64
        libcrypto.so.10(libcrypto.so.10)(64bit) is needed by memgraph-2.7.0_1-1.x86_64
        libssl.so.10()(64bit) is needed by memgraph-2.7.0_1-1.x86_64
        libssl.so.10(libssl.so.10)(64bit) is needed by memgraph-2.7.0_1-1.x86_64
        libstdc++.so.6(GLIBCXX_3.4.29)(64bit) is needed by memgraph-2.7.0_1-1.x86_64

**Comment by gitbuda** [comment]
Hi @mehdibad!

Is this a similar issue to the one that was fixed under https://github.com/memgraph/memgraph/pull/863?

Can you try out v2.9.0 (or the latest v2.10.0) because there the `rhel` setup was improved?

**Comment by mehdibad** [comment]
tested and run ok, had to install compat-openssl10 in order to start memgraph binary.

**Comment by gitbuda** [comment]
Interesting, I've actually tested explicitly but only on CentOS 7, is that some `rhel` specific package?

@mehdibad, can we close this issue?

CC @vpavicic, we should put that into the `docs`, but it requires verification and testing of where the package is actually required. NOTE we plan to revisit the setup for releasing on different Linux distros, so we should cover that under that work.

**Comment by mehdibad** [comment]
yes it's a rhel 8 specific package, @gitbuda you can close this issue, thanks.

**Comment by gitbuda** [comment]
Ok! Thanks a lot for reporting!
