### ISSUE TITLE
[BUG] N

### ISSUE THREAD

**Issue by rkaira-uptycs** [memgraph/memgraph#1206]
**Memgraph version**
Which version did you use?

**Environment**
Some information about the environment you are using Memgraph on: operating
system, how do you connect, with or without docker, which driver etc.

**Describe the bug**

**To Reproduce**
1. Run the following query '...'

**Expected behavior**

**Logs**
If applicable, add logs of Memgraph, CLI output or screenshots to help explain
your problem.

**Additional context**

**Comment by gitbuda** [comment]
I guess, this is created by accident because all the template stuff is just left as is -> closing this issue 😃
