### ISSUE TITLE
Add a way to check the stats and sizes of indexes

### ISSUE THREAD

**Issue by rkaira-uptycs** [memgraph/memgraph#1207]
**Memgraph version**
2.8.0

**Environment**
linux and running as docker and neo4j driver

**Describe the bug**
i wanted to see the stats of indexes which I have created to check the index size 
it is useful to analyze the index that are growing very rapidly or which are impacting the performances

**Comment by gitbuda** [comment]
Hi @rkaira-uptycs! This is another very valid feature request 😃 

What's the severity of it from your perspective?

**Comment by rkaira-uptycs** [comment]
hi @gitbuda 
we have a very high volume of data and we are planning to move to production. it would be great If we can see in coming releases. because as data bases usage  we should be able to analyze the kind of data it is holding the memory or spiking the CPU just because of one bad index. so consider it has high priority feature to use it at production level
