### ISSUE TITLE
Fix memory usage constantly increasing on memgraph cloud installation

### ISSUE THREAD

**Issue by marganellim** [memgraph/memgraph#1223]
**Memgraph version**
v2.10.0

**Environment**
Running memgraph cloud , US East region with 2GB Memory size. 

**Describe the bug**
Every 15 seconds I am querying the memgraph cloud deployment for information. I am not adding or removing any nodes. I call FREE MEMORY after each query. The memory usage as shown in graphana lab constantly goes up and up slowly. After about 30 hours I've reached the memory limit and have to pause/unpause my project to continue working with it. 

I began a new project under a different email in the same region, v2.10.0, 2GB memory in memgraph cloud. After logging into memgraph lab, I can see the memory usage go up with no transactions going on. 

**To Reproduce**
1. Launch a new memgraph cloud project using 2GB tier
2. Login using memgraph lab
3. memory continues to go up even with no trasactions going on

**Expected behavior**
If no transactions are going on, no nodes being added, no interaction with the graph database, memory using should not be increasing. 

**Logs**
![image](https://github.com/memgraph/memgraph/assets/82058625/281fbe59-589c-4d9e-9f17-e9800847c408)

**Additional context**
Making queries, even ones that do not add nodes seems to increase the rate of the memory leak. In the memgraph instance where I am quering every 15 seconds for information, the 1.5GB available gets exhausted in a little over 24 hours.

**Comment by ajosecueto** [comment]
@gitbuda Community detection Online and pagerank online present the same bug. Memory consumtion ran out my RAM. I had to disable triggers for my streaming graph.

**Comment by ajosecueto** [comment]
![image](https://github.com/memgraph/memgraph/assets/25847849/b8d20da7-8fb8-4276-b397-2ad28c4de0de)

Imposible to work with Streaming algorithms. Memory never was released and incrementally is growing until memgraph crash. Using v2.10.1

**Comment by gitbuda** [comment]
Might be similar/related to https://github.com/memgraph/memgraph/issues/1251
This needs separated investigation
