### ISSUE TITLE
Start Memgraph with on-disk storage mode by default

### ISSUE THREAD

**Issue by as51340** [memgraph/memgraph#1283]
Many users would like to use start Memgraph with disk storage automatically

**Comment by gitbuda** [comment]
My view is that the default should be `IN_MEMORY_TRANSACTIONAL` with the **snapshot isolation level**, but would like to hear the reasoning for the on-disk stuff 😃 If you can provide more details here it would be great!

**Comment by as51340** [comment]
I agree that for the majority default should be IN_MEMORY_TRANSACTIONAL. I would just like to add the flag storage mode which specifies in which storage mode is Memgraph started, Because switching to disk is tricky and I am sure that many users already know their dataset won't fit into memory upfront.
