### ISSUE TITLE
Add geospatial datatype support

### ISSUE THREAD

**Issue by gitbuda** [memgraph/memgraph#1290]

**Comment by matea16** [comment]
+1 on the issue from the user on [Discord](https://discord.com/channels/842007348272169002/890968055339958292/1182677054743920692) who requested a POINT type

**Comment by antejavor** [comment]
This is directly related: https://github.com/memgraph/memgraph/issues/1583

**Comment by DavIvek** [comment]
Duplicate of [1583](https://github.com/memgraph/memgraph/issues/1583)
