### ISSUE TITLE
Crash caused by using exists()

### ISSUE THREAD

**Issue by ljhhuxiaoba** [memgraph/memgraph#1294]
I executed a query on my empty memgraph database and get an error.

memgraph version:2.11.0
operating system: windows 10
API：Cypher version 9
query:match (a) RETURN exists((a)-[]-())
error message:Query failed: Connection was closed by server

Actual behavior:
The query failed and the memgraph container exited abnormally with the error message.

**Comment by gitbuda** [comment]
@ljhhuxiaoba, thanks for reporting all the issues!
This + https://github.com/memgraph/memgraph/issues/1293 + https://github.com/memgraph/memgraph/issues/874, all seems to be similar, we'll check all of them 💪

**Comment by DavIvek** [comment]
@ljhhuxiaoba Currently 'exists' works only for filtering in WHERE clauses, we will fix this bug by throwing an exception with a clear message.

**Comment by DavIvek** [comment]
@ljhhuxiaoba You could rewrite your query like this:
MATCH (a)
OPTIONAL MATCH path=(a)-[]-()
RETURN CASE WHEN path IS NULL THEN false ELSE true END AS has_relationship;

Or if you want to list all paths, you can execute query like this:
MATCH (a)
OPTIONAL MATCH path=(a)-[]-()
WITH path
WHERE path IS NOT NULL
RETURN path;

Is there a specific query in which you need to use exists in return clause?

**Comment by ljhhuxiaoba** [comment]
Thanks for the reply, I didn't come across a query that had to use exists in return clause, I was just doing my test work so I was wondering if the bug would be fixed or throw an exception with a clear message.
