### ISSUE TITLE
Crash caused when adding "WITH *"

### ISSUE THREAD

**Issue by ljhhuxiaoba** [memgraph/memgraph#1298]
I executed a query on my empty memgraph database and get an error.

memgraph version:2.11.0
operating system: windows 10
API：Cypher version 9
query:MATCH (n1) WITH * MATCH p=(n1) RETURN 1
error message:Query failed: Connection was closed by server

But it's worth noting that the query executes correctly when I remove the "WITH *".

Actual behavior:
The query failed and the memgraph container exited abnormally with the error message.

**Comment by dzello** [comment]
Just chiming in with a +1, I'm seeing the same thing. If I change the WITH * to WITH anything else then it works. Maybe something in the query planner? I am seeing it on 2.11 and also saw it on 2.9 & 2.10 so I don't _think_ it was introduced in the latest release.

**Comment by ljhhuxiaoba** [comment]
Yes, thank you for adding that the problem is as you describe it.

**Comment by as51340** [comment]
@ljhhuxiaoba can you check whether this issue still exists? I cannot reproduce with 2.12. on empty database.

**Comment by ljhhuxiaoba** [comment]
It does not crash in 2.12,maybe it has been fixed.

**Comment by as51340** [comment]
@dzello could you also verify please?

**Comment by as51340** [comment]
Closing since it is fixed in 2.12
