### ISSUE TITLE
Inconsistent results when using exists() in reduce()

### ISSUE THREAD

**Issue by ljhhuxiaoba** [memgraph/memgraph#1309]
I executed two queries on my memgraph database and get an error.

memgraph version:2.11.0
operating system: windows 10
API：Cypher version 9

To reproduce:
CREATE ();
Ⅰ: MATCH () WHERE exists(()) RETURN 1;
Ⅱ: MATCH () WHERE reduce(a=exists(()),b in []|a) RETURN 1;

I think the two queries above are equivalent, so they should return the same result.But the Ⅰ query returned 1 row of results, while the Ⅱ returned 0 rows.

**Comment by ljhhuxiaoba** [comment]
May i ask if this bug is fixed?

**Comment by as51340** [comment]
The bug is fixed in a sense that we will now throw exception explicitly if such a query is observed. Exists is only (currently) meant to be used with `where` clause. So the bug was that we allowed execution of something which we don't support...

**Comment by ljhhuxiaoba** [comment]
Thanks for your reply and the issue #1376 is the same reason?

**Comment by as51340** [comment]
yes exactly the same
