### ISSUE TITLE
Implement Cypher pattern comprehension

### ISSUE THREAD

**Issue by penghs520** [memgraph/memgraph#1310]
https://neo4j.com/docs/cypher-manual/current/values-and-types/lists/#cypher-pattern-comprehension

Pattern comprehension needs to be added in order to reduce the number of matches provided by the workaround of the `OPTIONAL MATCH`. 

Usage example:

`CREATE
  (keanu:Person {name: 'Keanu Reeves'}),
  (johnnyMnemonic:Movie {title: 'Johnny Mnemonic', released: 1995}),
  (theMatrixRevolutions:Movie {title: 'The Matrix Revolutions', released: 2003}),
  (theMatrixReloaded:Movie {title: 'The Matrix Reloaded', released: 2003}),
  (theReplacements:Movie {title: 'The Replacements', released: 2000}),
  (theMatrix:Movie {title: 'The Matrix', released: 1999}),
  (theDevilsAdvocate:Movie {title: 'The Devils Advocate', released: 1997}),
  (theMatrixResurrections:Movie {title: 'The Matrix Resurrections', released: 2021}),
  (keanu)-[:ACTED_IN]->(johnnyMnemonic),
  (keanu)-[:ACTED_IN]->(theMatrixRevolutions),
  (keanu)-[:ACTED_IN]->(theMatrixReloaded),
  (keanu)-[:ACTED_IN]->(theReplacements),
  (keanu)-[:ACTED_IN]->(theMatrix),
  (keanu)-[:ACTED_IN]->(theDevilsAdvocate),
  (keanu)-[:ACTED_IN]->(theMatrixResurrections)`

```
MATCH (keanu:Person {name: 'Keanu Reeves'})
RETURN [(keanu)-->(b:Movie) WHERE b.title CONTAINS 'Matrix' | b.released] AS years
```

**Comment by gitbuda** [comment]
+ 1 on this request

**Comment by gitbuda** [comment]
NOTE: reopened because only the grammar part is done, the planner is next

**Comment by gitbuda** [comment]
The planner part WIP under https://github.com/memgraph/memgraph/pull/1686

**Comment by katarinasupe** [comment]
@Darych Just a sanity check. After the PR is done, this type of query will work (pattern comprehension):
```
MATCH (keanu:Person {name: 'Keanu Reeves'})
RETURN [(keanu)-->(b:Movie) WHERE b.title CONTAINS 'Matrix' | b.released] AS years
```

But this won't (list comprehension):
```
RETURN [x IN range(0,10) WHERE x % 2 = 0 ] AS result
```
?

**Comment by Darych** [comment]
> @Darych Just a sanity check. After the PR is done, this type of query will work (pattern comprehension):
> 
> ```
> MATCH (keanu:Person {name: 'Keanu Reeves'})
> RETURN [(keanu)-->(b:Movie) WHERE b.title CONTAINS 'Matrix' | b.released] AS years
> ```
> 
> But this won't (list comprehension):
> 
> ```
> RETURN [x IN range(0,10) WHERE x % 2 = 0 ] AS result
> ```
> 
> or
> 
> ```
> MATCH (keanu:Person {name:'Keanu Reeves'})
> RETURN [x IN keanu.resume WHERE x contains 'The Matrix'] AS matrixList
> ```
> 
> ?

Yes, @katarinasupe . You are right.

**Comment by katarinasupe** [comment]
Hi @penghs520, Cypher pattern comprehension was added to Memgraph 2.16, so let us know if it works well for you 😄
