### ISSUE TITLE
Feature Request: ANALYZE GRAPH on startup

### ISSUE THREAD

**Issue by lucasprograms** [memgraph/memgraph#1326]
**Memgraph version**
2.10

**Environment**
docker

**Describe the bug**
When memgraph restarts, it loses statistics from a previous `ANALYZE GRAPH`

**To Reproduce**
1. Create dataset where the following is true:
> When multiple label-property indexes exist, the database can sometimes select a non-optimal index due to the data's distribution.
2. Confirm memgraph uses non-optimal index
3. run `ANALYZE GRAPH`
4. Confirm memgraph uses optimal index
5. Restart docker container
6. Confirm memgraph uses non-optimal index

**Expected behavior**
Statistics are maintained and recreated via e.g. snapshot, or option is available to run `ANALYZE GRAPH` on startup

**Comment by as51340** [comment]
hi @lucasprograms , this is solved [here](https://github.com/memgraph/memgraph/pull/1281). It will be part of the current release next week. Stay tuned!

**Comment by andrejtonev** [comment]
> To double check, @andrejtonev is this really done under #1281?

In the linked PR we introduced statistics deltas, its replication and durability.
We don't actually redo the `ANALYZE GRAPH`, but use the statistics from the last analysis.
