### ISSUE TITLE
Crash caused by deleting non-existing relationship

### ISSUE THREAD

**Issue by ljhhuxiaoba** [memgraph/memgraph#1329]
I executed a query on my empty memgraph database and get a crash.

memgraph version:2.11.0
operating system: windows 11
API：Cypher version 9
query:CREATE (n0)<-[r0:T3]-(n1) DETACH DELETE n0 DETACH DELETE r0 RETURN n1
error message:Query failed: Connection was closed by server

Actual behavior:
The query failed and the memgraph container exited abnormally with the error message.

**Comment by gitbuda** [comment]
It should be, it's fixed under https://github.com/memgraph/memgraph/pull/1355, not releases yet, but plan is to release it in the next few days

**Comment by ljhhuxiaoba** [comment]
OK,thanks.
