### ISSUE TITLE
Pass labels as variables / parameters

### ISSUE THREAD

**Issue by gitbuda** [memgraph/memgraph#1357]

**Comment by katarinasupe** [comment]
Related to: https://github.com/memgraph/memgraph/issues/1509

**Comment by DavIvek** [comment]
If you mean to pass labels as parameters in the following way:
`MATCH (n:$label) return n;  -- {label: "L1"}`
,then this is closed via [1602](https://github.com/memgraph/memgraph/pull/1602). Otherwise, it's the duplicate of [1509](https://github.com/memgraph/memgraph/issues/1509).
