### ISSUE TITLE
Linking MAGE to Memgraph slows down query modules

### ISSUE THREAD

**Issue by as51340** [memgraph/memgraph#1360]
**Memgraph version**
2.11, 2.10, 2.9

**Environment**
Docker and local build

**Describe the bug**
When running Memgraph together with MAGE, calling of query modules is much slower than in the case when we just create this one query module from the Memgraph LAB.
With memgraph-mage and memgraph-platform the import of 2000 nodes using LOAD CSV takes 2-5 min. When using just memgraph image and we create query module separately, import of 2000 nodes takes 17s.

Importing query:
```cypher
LOAD CSV FROM "https://download.memgraph.com/datasets/music-genres-social-network/csv/nodes-user.csv.gz"
  WITH HEADER IGNORE BAD AS row
  CREATE (:`__mg_node__`:`USER` {
    `__mg_id__`: row.`__mg_id__:ID:INDEX:TEMPORARY`,
    `id`: toInteger(row.`id:INTEGER`),
    `genres`: convert.str2object(row.`genres:JSON`)
  });
```

Link to the MAGE function that is used: [convert.str2object](https://github.com/memgraph/mage/blob/main/python/convert.py).

**Expected behavior**
Memgraph with MAGE shouldn't be slower.

**Comment by as51340** [comment]
I successfully reproduced the issue just with a bit different numbers but the logic is the same:
- import without MAGE = few seconds
- import with MAGE = 1 min

Perf wasn't very helpful but it obviously has to do something with linking Python.
![profile_2](https://github.com/memgraph/memgraph/assets/53269502/97d71c1a-9c83-4dbd-a90a-202c67de38b5)

cc @tonilastre to keep you updated

**Comment by antejavor** [comment]
This may be related to that issue: https://github.com/memgraph/memgraph/issues/969 cc @tonilastre @as51340

**Comment by gitbuda** [comment]
+1 report about `convert.str2object` being slow

**Comment by as51340** [comment]
Failed to do some meaningful work here except that there is a big difference in profiling whether you link the module at the beginning (by setting query modules) or you just create a query module from lab.

This is result when whole mage is linked to Memgraph:


![Image](https://github.com/memgraph/memgraph/assets/53269502/8487f096-89c4-459a-a3d7-9d4c7bf54e80)




This is result when just one module is linked to Memgraph:


![Image](https://github.com/memgraph/memgraph/assets/53269502/2e2416af-fe95-43b5-a5a5-b8c2616d1202)

**Comment by as51340** [comment]
I will pause work on this since I didn't have any progress here.

**Comment by as51340** [comment]
convert2str is moved to Memgraph so this is solved but we still maybe have a general issue that linking query modules at startup slows them down.
