### ISSUE TITLE
enhance date function to support temporal type

### ISSUE THREAD

**Issue by penghs520** [memgraph/memgraph#1372]
**Describe the scenario**
we have a scenario where we store values in datetime format and we want to support day-by-day filtering and millisecond by-millisecond filtering, we use the date function like this when day-by-day filtering:
```cypher
MATCH (n:Card) WHERE n.vutId IN ['xxx']
WITH n
WHERE date(n.plan_date) = date('2023-09-30')
RETURN n
```
the "n.plan_date" is a localdatetime property, but it gets a error "Optional 'date' argument at position 1 must be either 'string' or 'map'."

**Comment by as51340** [comment]
Hi @penghs520 thanks for the feedback!

I will be working on that issue and will let you know once we have the fix!
