### ISSUE TITLE
Result return failed when using exists() in CASE WHEN

### ISSUE THREAD

**Issue by ljhhuxiaoba** [memgraph/memgraph#1376]
I executed a query on my memgraph database and get an error.

memgraph version:2.11.0
operating system: windows 10
API：Cypher version 9

To reproduce:
CREATE ()-[:T]->();
MATCH (a) WHERE CASE WHEN TRUE THEN exists(()-[]->()) END RETURN a;

I think the query should return 2 nodes as result.But it returns 0 row of results.

**Comment by as51340** [comment]
Yep, I agree because if you run:
```
MATCH (a) WHERE exists(()-[]->()) RETURN a;
```
you will get 2 nodes and this is correct result.
I am working on it and will get back when I will have some new info.
