### ISSUE TITLE
OPTIONAL MATCH is slow upon returning of many variables

### ISSUE THREAD

**Issue by Josipmrden** [memgraph/memgraph#1416]
**Memgraph version**
v2.11

**Environment**
Ubuntu

**Describe the bug**
Query below takes a long time to execute. The culprit seems to be the producing of many results that is possibly being extracted one by one. We would need detailed overview of what's the bottleneck.

```
MATCH (a<-[t]-(b)-[]->(m)
WHERE a.prop ='abc'
OPTIONAL MATCH (m)<-[:TYPE1]-(d)
OPTIONAL MATCH (e)-[:TYPE2]->(b) where ...
OPTIONAL MATCH (b)-[:TYPE3]->()
OPTIONAL MATCH (b)-[:TYPE4]->()
OPTIONAL MATCH (b)-[:TYPE5]->()
OPTIONAL MATCH (b)-[:TYPE6]->()
OPTIONAL MATCH (b)-[:TYPE7]->()
OPTIONAL MATCH (b)-[:TYPE8]->(:IPN)-[:TYPE9]->() where ...
OPTIONAL MATCH (z)<-[:TYPE9]-(:IPN)<-[:TYPE9]-(b) where ...
WITH (assign 60 props)
RETURN DISTINCT 60 props...
```

**Expected behavior**
The query should run very fast.

**Comment by penghs520** [comment]
I have also encountered this problem before. If only a few optional matches are available, it is fine. If the number is too large, memgrpah's execution plan will be disrupted and it will go in the worst direction

**Comment by Josipmrden** [comment]
hello @penghs520 . Can you maybe share the query that was slow for you as well as the explain and profile plans?

**Comment by Josipmrden** [comment]
Closed with https://github.com/memgraph/memgraph/pull/1432

**Comment by penghs520** [comment]
> hello @penghs520 . Can you maybe share the query that was slow for you as well as the explain and profile plans?

ok, this query demo in 'Game of Thrones deaths' dataset.

First look at the normal situation and its profile：
```cypher
PROFILE MATCH (c:Character)-[:LOYAL_TO]->(a:Allegiance) 
OPTIONAL MATCH (c)-[:VICTIM_IN]->(d:Death)-[:HAPPENED_IN]->(e:Episode) 
WITH c,a,collect({name:e.name}) AS episode
OPTIONAL MATCH (c)-[:VICTIM_IN]->(d:Death)-[:HAPPENED_IN]->(s:Season) 
WITH c,a,episode,collect({number:s.number}) AS season
OPTIONAL MATCH (c)-[:VICTIM_IN]->(d:Death)-[:HAPPENED_IN]->(l:Location) 
WITH c,a,episode,collect({name:l.name}) AS location
OPTIONAL MATCH (c)-[:VICTIM_IN]->(d)<-[:KILLER_IN]-(killer:Character) 
WITH c,a,episode,location,collect({name:killer.name}) as killer
RETURN c.name,a.name,episode,location,killer
```
![image](https://github.com/memgraph/memgraph/assets/52020193/27892234-c23e-4c48-873d-dc4f6adf9c77)

When optional match gradually increased：
```cypher
PROFILE MATCH (c:Character)-[:LOYAL_TO]->(a:Allegiance) 
OPTIONAL MATCH (c)-[:VICTIM_IN]->(d:Death)-[:HAPPENED_IN]->(e:Episode) 
OPTIONAL MATCH (c)-[:VICTIM_IN]->(d:Death)-[:HAPPENED_IN]->(e:Episode) 
OPTIONAL MATCH (c)-[:VICTIM_IN]->(d:Death)-[:HAPPENED_IN]->(e:Episode) 
//Repeat it to simulate more optional matches，Because the model of this dataset is too simple
OPTIONAL MATCH (c)-[:VICTIM_IN]->(d:Death)-[:HAPPENED_IN]->(e:Episode) 
WITH c,a,collect({name:e.name}) AS episode
OPTIONAL MATCH (c)-[:VICTIM_IN]->(d:Death)-[:HAPPENED_IN]->(s:Season) 
WITH c,a,episode,collect({number:s.number}) AS season
OPTIONAL MATCH (c)-[:VICTIM_IN]->(d:Death)-[:HAPPENED_IN]->(l:Location) 
WITH c,a,episode,collect({name:l.name}) AS location
OPTIONAL MATCH (c)-[:VICTIM_IN]->(d)<-[:KILLER_IN]-(killer:Character) 
WITH c,a,episode,location,collect({name:killer.name}) as killer
RETURN c.name,a.name,episode,location,killer
```
![image](https://github.com/memgraph/memgraph/assets/52020193/af545491-6a48-43d7-ba0b-c5da90e55164)

**Comment by penghs520** [comment]
On the other hand, the performance of collect operator seems to be a little slow

**Comment by penghs520** [comment]
hi @Josipmrden ,The issue has not been fully resolved.
It solves the scenario of repeated attribute utilization, but does not really solve the execution plan optimization problem of multiple optional matches.

In the case of the King game I mentioned above, there are duplicates in the cypher given, and this cypher is already fine in v2.12.0
```
PROFILE MATCH (c:Character)-[:LOYAL_TO]->(a:Allegiance) 
OPTIONAL MATCH (c)-[:VICTIM_IN]->(d:Death)-[:HAPPENED_IN]->(e:Episode) 
OPTIONAL MATCH (c)-[:VICTIM_IN]->(d:Death)-[:HAPPENED_IN]->(e:Episode) 
OPTIONAL MATCH (c)-[:VICTIM_IN]->(d:Death)-[:HAPPENED_IN]->(e:Episode) 
//Repeat it to simulate more optional matches，Because the model of this dataset is too simple
OPTIONAL MATCH (c)-[:VICTIM_IN]->(d:Death)-[:HAPPENED_IN]->(e:Episode) 
WITH c,a,collect({name:e.name}) AS episode
OPTIONAL MATCH (c)-[:VICTIM_IN]->(d:Death)-[:HAPPENED_IN]->(s:Season) 
WITH c,a,episode,collect({number:s.number}) AS season
OPTIONAL MATCH (c)-[:VICTIM_IN]->(d:Death)-[:HAPPENED_IN]->(l:Location) 
WITH c,a,episode,collect({name:l.name}) AS location
OPTIONAL MATCH (c)-[:VICTIM_IN]->(d)<-[:KILLER_IN]-(killer:Character) 
WITH c,a,episode,location,collect({name:killer.name}) as killer
RETURN c.name,a.name,episode,location,killer
```
![image](https://github.com/memgraph/memgraph/assets/52020193/60de6bbb-9d89-4011-8bdf-106fa665f910)

But if many optional matches with no duplication at all, such as in my data model (I actually only have tens of thousands of nodes and edges), still run slowly, I see scanAll in the execution plan, which produces a large Cartesian product:
![image](https://github.com/memgraph/memgraph/assets/52020193/ebfdb25f-0f2b-4967-b0b8-4972340e8be3)

**Comment by penghs520** [comment]
It is worth mentioning that all the points are labeled with a tag called Card in my model, what do you think about this, and does it affect the execution plan

**Comment by penghs520** [comment]
I feel the need to provide you with a working example in the hetionet dataset:
```cypher
profile MATCH (gene:Gene)
WITH gene limit 1000
OPTIONAL MATCH (gene)<-[:UPREGULATES_DuG]-(d1:Disease)
WITH gene,collect(d1) as d1
OPTIONAL MATCH (gene)<-[:ASSOCIATES_DaG]-(d2:Disease)
WITH gene,d1,collect(d2) as d2
OPTIONAL MATCH (gene)<-[:DOWNREGULATES_DdG]-(d3:Disease)
WITH gene,d1,d2,collect(d3) as d3
OPTIONAL MATCH (gene)<-[:EXPRESSES_AeG]-(a1:Anatomy)
WITH gene,d1,d2,d3,collect(a1) as a1
OPTIONAL MATCH (gene)<-[:UPREGULATES_AuG]-(a2:Anatomy)
WITH gene,d1,d2,d3,a1,collect(a2) as a2
OPTIONAL MATCH (gene)<-[:DOWNREGULATES_AdG]-(a3:Anatomy)
WITH gene,d1,d2,d3,a1,a2,collect(a3) as a3
OPTIONAL MATCH (gene)<-[:BINDS_CbG]-(c1:Compound)
WITH gene,d1,d2,d3,a1,a2,a3,collect(c1) as c1
OPTIONAL MATCH (gene)<-[:UPREGULATES_CuG]-(c2:Compound)
WITH gene,d1,d2,d3,a1,a2,a3,c1,collect(c2) as c2
OPTIONAL MATCH (gene)<-[:DOWNREGULATES_CdG]-(c3:Compound)
WITH gene,d1,d2,d3,a1,a2,a3,c1,c2,collect(c3) as c3
OPTIONAL MATCH (gene)-[:PARTICIPATES_GpBP]->(b1:BiologicalProcess)
WITH gene,d1,d2,d3,a1,a2,a3,c1,c2,c3,collect(b1) as b1
RETURN gene,d1,d2,d3,a1,a2,a3,c1,c2,c3,b1
```
I added 10 optional matches, which produced scanAll
![image](https://github.com/memgraph/memgraph/assets/52020193/04266db4-48dc-443e-a9c4-4ec7914992e1)
I went back to normal when I removed any optional match
![image](https://github.com/memgraph/memgraph/assets/52020193/5f35d002-7221-4083-afec-10e0191fb181)

**Comment by Josipmrden** [comment]
@penghs520 Thank you so much for this. It definitely makes sense for ScanAll not to be there. Where is your Memgraph running?

As it seems, perhaps the --cartesian-product-enabled=true is the flag that needs to be set to false. We did some optimizations on the cartesian products to speed some of our queries up. That should be the workaround, but we'll provide a fix and then perhaps make a patch release.

**Comment by penghs520** [comment]
@Josipmrden --cartesian-product-enabled=false not helpful for the current scenario

**Comment by Josipmrden** [comment]
I guess we'll need some more time inspecting the issue. We'll notify you on the progress of the issue.
