### ISSUE TITLE
Create user exception not handled

### ISSUE THREAD

**Issue by katarinasupe** [memgraph/memgraph#1417]
**Memgraph version**
Memgraph 2.11.1

**Environment**
Docker, Mac M1

**Describe the bug**
I am running Memgraph with Docker/Docker Compose with volumes set and [init-file flag](https://memgraph.com/docs/configuration/configuration-settings#use-init-flags-with-docker) used. Users are using `init-file` flag to initialize users before the Bolt server starts. 

When rerunning the Memgraph container, the user is being created again before the Bolt server starts and that causes Memgraph to crash. I think this happens because [the exception is not handled correctly](https://github.com/memgraph/memgraph/blob/3158a16ffd744e2be583e2c38fc1f01886e80987/src/query/interpreter.cpp#L467-L474). 

**To Reproduce**
1. Download project
[test-docker-compose.zip](https://github.com/memgraph/memgraph/files/13176383/test-docker-compose.zip)

2. Run `docker compose build`
3. Run `docker compose up` -- all works fine and as expected (auth with created user)
4. Open another terminal window and run `docker stop init-test`
5. Now run `docker start init-test`
6. Memgraph crashes (run `docker logs -f init-test` to see logs)

**Expected behavior**
On the second run, Memgraph runs normally and notifies the user that the user has already been created. 

**Logs**
Run `docker logs -f init-test` to see logs
![Screenshot 2023-10-26 at 12 26 09](https://github.com/memgraph/memgraph/assets/61758502/cb9e9759-062a-415c-893c-b4272e0a3b85)

**Additional context**

**Comment by katarinasupe** [comment]
Importance - I2 - affected are all the community/enterprise users who need to define the user before the Bolt server starts, and this is quite common in a production environment. 
Severity - S2 - community user who reported wanted to set this up before running Memgraph in production, so this is currently a blocker for that.

**Comment by katarinasupe** [comment]
There is a possible workaround. First drop the user and then create a new one:

```
DROP USER memgraph1;
CREATE USER memgraph1 IDENTIFIED BY '1234';
```

I am waiting for the user to verify if this is a good enough workaround for now, but I see how this is still not a workaround for Enterprise users who could have added role-based or label-based access control rules sometimes after starting the Bolt server. That would be persisted, but once the user is dropped and created again, role-based or label-based access control rules would have to be set again. In that case, the best practice is to always define all user permissions in the init-file.

**Comment by LukasPoque** [comment]
The workaround helps me partially. For the first run with no state saved the `DROP USER` will result in an error. So I need to start the container without this command first and add it afterward so it can prevent the `User already exists` crash.

**Comment by LukasPoque** [comment]
I think the best solution for me is to set the user through [environment variables](https://memgraph.com/docs/configuration/configuration-settings#environment-variables) this works completely fine.

**Comment by katarinasupe** [comment]
@LukasPoque, thank you for another workaround and happy to hear you managed to find a suitable solution 😄

**Comment by katarinasupe** [comment]
Notice that .env file didn't zip with other contents. It was located in the root and here is its content:
`MEMGRAPH="--log-level=TRACE --init-file=/usr/lib/memgraph/auth.cypherl"`

**Comment by as51340** [comment]
@katarinasupe This isn't expected or?

**Comment by katarinasupe** [comment]
@as51340 It is expected that the exception is handled properly, similar to the case when you try running CREATE INDEX twice. I think that it's not expected that the action such as user creation of a user that already exists crashes Memgraph.

**Comment by as51340** [comment]
yes yes but my question was about zipping .env file?

**Comment by katarinasupe** [comment]
Oh sorry, that one was unrelated to the actual issue, I just provided the missing .env file from test-docker-compose.zip to easily reproduce the issue.
