### ISSUE TITLE
Add date manipulation functionalities

### ISSUE THREAD

**Issue by gitbuda** [memgraph/memgraph#1421]
* add a month
* today - 30 days
* add min/max for date types

**Comment by katarinasupe** [comment]
Related: https://github.com/memgraph/memgraph/issues/1422

**Comment by antepusic** [comment]
In addition to PR https://github.com/memgraph/memgraph/pull/1790, the new https://github.com/memgraph/mage/pull/456 PR addresses the first two points of the issue.
