### ISSUE TITLE
Min / max functions are not available in Memgraph for date types

### ISSUE THREAD

**Issue by Josipmrden** [memgraph/memgraph#1422]
Currently, min max functions are not supported for temporal types. We have the MAGE modules but from the convenience point there should be also temporal types supported in the awesome memgraph functions.

**Comment by katarinasupe** [comment]
**+1 from the community**. Here is a workaround:
Use the [collections](https://memgraph.com/docs/advanced-algorithms/available-algorithms/collections#max) module from the MAGE library. Here is an example of how to use it:

```
CREATE (:Person {birthday: date("1947-07-30")});
CREATE (:Person {birthday: date("1948-07-30")});

MATCH (n:Person)
WITH collect(n.birthday) AS birthdays
RETURN collections.max(birthdays);
```

In the same way you can calculate min value.

**Comment by antepusic** [comment]
The `min()` and `max()` functions will work with temporal types as intended from #1790 on.
