### ISSUE TITLE
Memory usage increases constantly

### ISSUE THREAD

**Issue by nofendermatt** [memgraph/memgraph#1429]
**Memgraph version**
2.11.0

**Environment**
Memgraph Cloud

**Describe the bug**
I have 94K nodes, 307 relationships and 2 indexes. I now use 3.3GB out of 3.08GB available memory.

**To Reproduce**
I have no ongoing processes right now. Only Memgraph Lab. But have no active connections.

**Expected behavior**

**Logs**
I have no warnings in the log files

**Additional context**

**Verification Environment**
Once we fix it, what do you need to verify the fix?
Do you need:
* Plain memgraph package -> for which Linux?
* Plain memgraph Docker image?
* Which architecture do you use ARM | x86?
* Full Memgraph platform?

**Comment by imilinovic** [comment]
There was an issue with garbage collection not working properly.
It was fixed in this [PR](https://github.com/memgraph/memgraph/pull/1471)
Are you still experiencing this issue in the newer Memgraph version (2.13)
@nofendermatt

**Comment by imilinovic** [comment]
Closed due to insufficient information and issue probably being resolved in the new version already.
