### ISSUE TITLE
Neo4J Diver Error When Filtering by a Literal Array

### ISSUE THREAD

**Issue by AndriiG13** [memgraph/memgraph#1435]
**Memgraph version**
memgraph/memgraph-platform:2.11.1-memgraph2.11.0-lab2.8.3 (2.10 and 2.9 are also affected) 

**Environment**
ARM processor, connecting through Docker with:
```bash
docker run -it -d -p 7687:7687 -p 7444:7444 -p 3000:3000 --name memgraph  -v mg_log:/var/log/memgraph -e MEMGRAPH="--log-level=TRACE --bolt-server-name-for-init=Neo4j/5.11.0" memgraph/memgraph-platform:2.11.1-memgraph2.11.0-lab2.8.3
```

To execute queries I'm using the latest Neo4J Driver `5.14.0`.

**Describe the bug**
When executing multiple queries with an `IN [...]` filter with the Neo4J driver, an exception is thrown:
```bash
IncompleteCommit: Failed to read from defunct connection IPv4Address(('localhost', 7687)) (ResolvedIPv6Address(('::1', 7687, 0, 0)))
```

This happens with both the Sync and the Async driver, but is much more common with the Async driver. In Memgraph logs, I also see a `Segmentation fault` logged. The last Memgraph version where this works without any issue is `2.8.0`, all releases since then seem to have this exception thrown. 

**To Reproduce**
1. Insert some data with  `CREATE (n:Country {name: 'San Marino', continent: 'Europe'}) RETURN n;`
2. To reproduce with sync client, in Python run:
```python
from neo4j import GraphDatabase

QUERY = """
MATCH (n:Country)
WHERE n.continent IN ['Europe']
RETURN n.id, n.name
"""

client_sync = GraphDatabase.driver("bolt://localhost:7687",  auth=("neo4j", "password"))
res = [client_sync.execute_query(QUERY) for _ in range(3_000)]
```
3. To reproduce with async client, in Python run:
```python
from neo4j import AsyncGraphDatabase

QUERY = """
MATCH (n:Country)
WHERE n.continent IN ['Europe']
RETURN n.id, n.name
"""

client_async = AsyncGraphDatabase.driver("bolt://localhost:7687",  auth=("neo4j", "password"))
calls = [client_async.execute_query(QUERY) for _ in range(1_000)]
res = await asyncio.gather(*calls)
```

**Expected behavior**
The queries execute successfully. 

**Logs**
`Segmentation fault` is logged 

<img width="921" alt="Screenshot 2023-10-30 at 13 51 27" src="https://github.com/memgraph/memgraph/assets/47453561/a69c7276-5035-4b8b-8827-c90e15ea201a">

**Additional context**
I know that according to best practices, using parameters is preferred, however, I would still expect the queries above to run without any issues. In addition, we found that using a parameter in a `IN [...]` filter slowed down our queries quite a bit, but I will have to benchmark some more to confirm for sure. 

**Verification Environment**
* Plain memgraph Docker image for ARM

**Comment by antejavor** [comment]
Looks similar to this: https://github.com/memgraph/memgraph/issues/1350 cc @as51340

**Comment by AndriiG13** [comment]
Woah that was blazing fast! Unfortunately, I only have an ARM environment, so would appreciate an ARM image

**Comment by antejavor** [comment]
Hi @AndriiG13, we think that 2.12 we did solve this issue. Can you try running it on the new 2.12 version of Memgraph?

**Comment by AndriiG13** [comment]
Hi @antejavor, I tried running on 2.12 `2.12.0-memgraph2.12.0-lab2.9.0`, but I'm still getting segmentation error

<img width="928" alt="Screenshot 2023-11-14 at 12 18 25" src="https://github.com/memgraph/memgraph/assets/47453561/c9d6a4de-0696-4881-ad89-7a507ce368f4">

**Comment by antejavor** [comment]
Hi @AndriiG13, 

For some folks, 2.12 solved the issue, but we have one more fix that didn't end in the 2.12. We will have a patch release early next week so, 2.12.1 will include the other fix, [that I also mentioned above.](https://github.com/memgraph/memgraph/issues/1435#issuecomment-1785236299)

In the meantime here is the [**ARM-based** docker image of Memgraph](https://drive.google.com/file/d/1WqP2Z6y2zQQF3Puy9DuNeLuaRFBdQEek/view?usp=sharing). It is the current master that includes the fix. You can give that one a try. 

You can load image via the following command: 

`docker load -i memgraph-2.12.0_29_9cc060c4b-docker.tar.gz `

Start it container via the following command: 

`docker run -it  -p 7687:7687 --name memgraph memgraph:2.12.0_29_9cc060c4b`


Let me know if this works for you.

**Comment by AndriiG13** [comment]
Indeed this works now :) Thank you!

**Comment by antejavor** [comment]
Happy to hear that. Stay tuned for 2.12.1 version that has the fix. 🎊
