### ISSUE TITLE
Cannot resolve conflicting transactions on Java client

### ISSUE THREAD

**Issue by penghs520** [memgraph/memgraph#1449]
**Memgraph version**
v2.11.0

**Environment**
Some information about the environment you are using Memgraph on: operating
system, architecture (ARM, x86), how do you connect, with or without docker,
which driver etc.

**Describe the bug**
When multiple threads change the same node at the same time, and the greater the scope of the change, the greater the probability of occurrence.
![image](https://github.com/memgraph/memgraph/assets/52020193/0fb90ab3-d553-446a-ae81-2dcf3d5db0fc)

**Expected behavior**
I run into this problem a lot in my scenario, especially when modifying a dense node. The error message asks me to retry the problem at the application layer and whether I can solve it at the server layer.

**Comment by antejavor** [comment]
Hi @penghs520, I have seen @chrischabot suggest upgrading to 2.12. We added a bunch of improvements in that release; one of them was this: https://github.com/memgraph/memgraph/pull/1361. 

This should be fixed in 2.12.

**Comment by penghs520** [comment]
That's great!

I also want to know what the following configuration does, which I thought was used to solve this transaction conflict problem









                       
Original Email
                       
                     

Sender:"Ante Javor"< ***@***.*** &gt;;

Sent Time:2023/11/3 19:14

To:"memgraph/memgraph"< ***@***.*** &gt;;

Cc recipient:"penghs"< ***@***.*** &gt;;"Mention"< ***@***.*** &gt;;

Subject:Re: [memgraph/memgraph] Cannot resolve conflicting transactions onJava client (Issue #1449)




 
Hi @penghs520, I have seen @chrischabot suggest upgrading to 2.12. We added a bunch of improvements in that release; one of them was this: #1361.
 
This should be fixed in 2.12.

**Comment by penghs520** [comment]
![image](https://github.com/memgraph/memgraph/assets/52020193/2b8fa93b-3d74-4bf6-898a-3ce6271a84bf)

**Comment by antejavor** [comment]
@penghs520, this configuration is for the streaming use-case. When streaming transformation fails because of conflicting transactions, you can define the quantity and interval of retries. 

But it has noting to do with the Java driver, which is handled on the Neo4j Client side.

**Comment by penghs520** [comment]
@antejavor hi，v2.12.0 still hasn't solved the problem

**Comment by penghs520** [comment]
@antejavor 
memgraph: v2.12.0
neo4j-java-driver:5.14.0

code demo: Simulates two threads making concurrent changes
```java
public static void main(String[] args) throws InterruptedException {
        Driver driver = GraphDatabase.driver("bolt://localhost:7687", AuthTokens.basic("", ""));
        try (Session session = driver.session()) {
            session.run("MATCH (n {name:'Alice'}) DETACH DELETE n;");
            session.run("MATCH (n {name:'Bob'}) DETACH DELETE n;");
            session.run("CREATE (a:Person {name: $name,age:$age})", parameters("name", "Alice", "age", 20));
            session.run("CREATE (a:Person {name: $name})", parameters("name", "Bob"));
        }
        // In another thread，modify this Alice node again and again
        Thread thread1 = new Thread(() -> {
            try (Session session = driver.session()) {
                for (int i = 0; i < 1000; i++) {
                    session.run("MATCH (a:Person {name: $name}) SET a.age = a.age + 1", parameters("name", "Alice"));
                }
            }
        });
        // In another thread，try to create a relationship between Alice and Bob again and again
        Thread thread2 = new Thread(() -> {
            try (Session session = driver.session()) {
                for (int i = 0; i < 1000; i++) {
                    session.run("MATCH (a:Person {name: $name1}), (b:Person {name: $name2}) CREATE (a)-[:KNOWS]->(b)", parameters("name1", "Alice", "name2", "Bob"));
                }
            }
        });

        thread1.start();
        thread2.start();
        thread1.join();
        thread2.join();
    }
```
result:
![image](https://github.com/memgraph/memgraph/assets/52020193/338562fe-d0f9-4ee6-bd96-b98c3630e09d)

**Comment by antejavor** [comment]
Thanks for providing the details, will get back to you.  cc @Josipmrden

**Comment by penghs520** [comment]
I wonder where the retry logic is in the driver,  I can debug it
@antejavor

**Comment by antejavor** [comment]
ok, so you are using the auto-commit or implicit transactions: https://neo4j.com/docs/java-manual/current/session-api/#java-driver-simple-autocommit-transactions 

As you can see in Neo4j docs,  driver won't retry on the Transient exception in that transaction mode. In the screenshot you provided, we are returning a Transient error to the Neo4j driver indicating that it should be retried, but this does not work for auto-commits.

**Comment by antejavor** [comment]
Using a simple transaction functions will solve your problem: https://neo4j.com/docs/java-manual/current/session-api/#java-driver-simple-transaction-fn

**Comment by penghs520** [comment]
@antejavor thanks！
Switching to manually committed transaction operations is fine, and the other question is whether the retry operations here are likely to be repeated

**Comment by antejavor** [comment]
> and the other question is whether the retry operations here are likely to be repeated

If you do not use auto-commit transaction API in any Neo4j Driver, transactions will be retried if they receive the Transient error. We are providing that error in case of conflicts, so each time conflicts happens it will be retried with exponential backoff.

**Comment by penghs520** [comment]
@antejavor I got it，thks
