### ISSUE TITLE
CALL schema.node_type_properties() YIELD * throws "There is no procedure named 'schema.node_type_properties'"

### ISSUE THREAD

**Issue by agentsmith41** [memgraph/memgraph#1463]
**Memgraph version**
2.12

**Environment**
Memgraph-platform on docker

**Describe the bug**
querying CALL schema.node_type_properties() YIELD * throws "There is no procedure named 'schema.node_type_properties'"

**To Reproduce**
1. Run the following query 'CALL schema.node_type_properties() YIELD *'

**Expected behavior**
should behave the same as it was on 2.11

**Logs**
If applicable, add logs of Memgraph, CLI output or screenshots to help explain
your problem.

**Additional context**
![image](https://github.com/memgraph/memgraph/assets/35218069/525ce821-695e-4c4d-8233-0c510d50f31d)
![image](https://github.com/memgraph/memgraph/assets/35218069/a28503d6-2cdf-43aa-8523-e3cd4f39d690)

**Verification Environment**
Once we fix it, what do you need to verify the fix?
Do you need:
* Plain memgraph package -> for which Linux?
* Plain memgraph Docker image?
* Which architecture do you use ARM | x86?
* Full Memgraph platform?

**Comment by gvolfing** [comment]
Related issue about incorrect output from the above mentioned procedure:
https://github.com/memgraph/memgraph/issues/1467

**Comment by DavIvek** [comment]
The error we are getting while loading query modules when we start memgraph is `/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/memgraph/query_modules/schema.so). `
When the query module (or any one of its dynamic dependencies) was built it was on a system with GCC 11 and hence the libstdc++ it used while building was symbol version as GLIBCXX_3.4.29. So when we try to use that binary on any system that can't satisfy that symbol versioning we get a failure. Currently, we are using Debian 11 as a base image, what it means is that we are using GCC 10.2.1, and that doesn't satisfy the symbol versioning that we need for our query modules. 
There are several ways to solve this issue and we will come up with a solution as fast as possible.

**Comment by antoniofilipovic** [comment]
This is reopened as we didn't fix that completely in the 2.12.1 release. The way we fixed that is now it deadlocks memgraph when loading `pytorch` module (i.e. `node_classification.py`). Needs further investigation. To reproduce, check following internal slack thread: https://memgraph.slack.com/archives/CS5827FK3/p1700562372183509

**Comment by DavIvek** [comment]
This is fixed with #1554 .
