### ISSUE TITLE
Query memory limit not respected when running in query rapid succession

### ISSUE THREAD

**Issue by antoniofilipovic** [memgraph/memgraph#1469]
## Steps to reproduce

1. Import dataset in Memgraph Lab
2. Run query limit on following query: `MATCH p=()-[*]->() RETURN count(*) QUERY MEMORY LIMIT 1 MB`
3. Run same query immediately 

After few tries, query limit will not be respected.

Bug resolution:
- [ ] jemalloc thread.arena gives wrong arena id for given thread, so in some cases arena counter ends up being 0 instead of 1, and therefore tracking is disabled
- [ ] due to giving wrong arena id, arena_counter ends up being negative number, which shouldn't happen in any case

Opened PR here which fixes the bug: https://github.com/memgraph/memgraph/pull/1468

**Comment by hal-eisen-MG** [comment]
@antoniofilipovic Please add Severity and Importance labels, thanks

**Comment by antoniofilipovic** [comment]
@hal-eisen-MG done

**Comment by antoniofilipovic** [comment]
This issue is fixed by https://github.com/memgraph/memgraph/pull/1468 PR.
