### ISSUE TITLE
Memgraph returns a Record with null values, Neo4j doesn't return a Record

### ISSUE THREAD

**Issue by antejavor** [memgraph/memgraph#1474]
**Memgraph version**
Memgraph 2.12

**Environment**
Memgraph in docker 

**Describe the bug**
When using collect Memgraph will return a result, Neo4j won't return the result. This causes users to change the code base, increased traction for migration. 

**To Reproduce**

No results: 
```
MATCH (subnet:Subnet)
WHERE FALSE
RETURN id(subnet) AS subnetId
```

Returns a record with null subnetId. 
```
MATCH (subnet:Subnet)
WHERE FALSE
WITH subnet, collect(subnet.ip) AS ips
RETURN id(subnet) AS subnetId
```

**Expected behavior**
Neo4j does not return results, Memgraph probably should not also.

**Comment by as51340** [comment]
`collect(null)` should definitely returns [] because that's how it is specified in openCypher. The only question is whether we should evaluate `with` if the filter branch is false. Not sure about that. @gitbuda help please
