### ISSUE TITLE
Implement a recovery version check

### ISSUE THREAD

**Issue by gitbuda** [memgraph/memgraph#1475]
If the snapshot is incompatible with the current memgraph version, log an error, and stop memgraph but don't do any destructive action.

**Comment by hal-eisen-MG** [comment]
In the file `snapshot.cpp` we have a line of code like this:
```
  if (!IsVersionSupported(*version)) throw RecoveryFailure("Invalid snapshot version!");
```
which then goes to
```
inline bool IsVersionSupported(uint64_t version) { return version >= kOldestSupportedVersion && version <= kVersion; }
```

While that exception message could be improved, it does seem like it meets the minimum requirements. Was there something more you had in mind @gitbuda ?

**Comment by gitbuda** [comment]
Sorry for being very late here... Hm, I've opened this issue probably for a reason, but the description is not detailed enough. The code you linked, satisfies the description. I'm thinking now, maybe the versioning for RocksDB was an issue here, but if that's a problem let's create a new more specific issue. Closing this issue, thank you!
