### ISSUE TITLE
Skip/ignore all files with wrong permission on getting storage info in the data directory

### ISSUE THREAD

**Issue by gitbuda** [memgraph/memgraph#1522]
This is important because some backup systems (e.g., veeam.com) create hidden files inside the repos they back up.

**Comment by antoniofilipovic** [comment]
@gitbuda can you expand on this issue, what needs to be skipped exactly?

**Comment by antoniofilipovic** [comment]
Following PR should fix the issue: https://github.com/memgraph/memgraph/pull/1566/files
