### ISSUE TITLE
ToBoolean casts the strings "t" and "f" to null

### ISSUE THREAD

**Issue by lucasprograms** [memgraph/memgraph#1538]
**Memgraph version**
2.11

**Describe the bug**
For csv like
```
id,is_a_fun_guy_at_parties
3,f
42,t
```

```
LOAD CSV FROM $file_path
WITH header NULLIF '' AS row
MERGE (a:Node { id: ToInteger(row.node_id) })
SET a.isAFunGuyAtParties = ToBoolean(row.is_a_fun_guy_at_parties)
```

All `Node` entities loaded like so will have a null value for `isAFunGuyAtParties`. Since, e.g., postgresql COPY to CSV will record true values as `t` and false values as `f`, it may be worth updating `ToBoolean` to accept the string 't' as true, and 'f' as false. Otherwise, updating the documentation to describe which values are treated as t/f could be helpful.

**Comment by karmenrabar** [comment]
Hello @lucasprograms, good news - Memgraph has a new release, 2.14., which includes the fix for this issue! Could you check if the newest version works as expected for you now?
