### ISSUE TITLE
Problems with std::locale, RTLD_DEEPBIND, pytorch

### ISSUE THREAD

**Issue by gitbuda** [memgraph/memgraph#1559]
There are in total 3 issues:
* not being able to print anything other than string under C++ query modules (e.g float number)
* not being able to start Memgraph when a python module using pytorch is getting loaded
* not being able to load the utils query module like `schema` while pytorch-dependent module is getting loaded

Related:
* https://github.com/memgraph/memgraph/issues/1463
* https://github.com/memgraph/memgraph/pull/335
* https://stackoverflow.com/a/67999062/4888809
* https://stackoverflow.com/a/34074587

**Comment by Ignition** [comment]
Investigation + experiment git repo:
https://github.com/Ignition/dlopen_and_toolchain

**Comment by Ignition** [comment]
Findings: `RTLD_DEEPBIND` is always causing failure in the experiment repo. It causes `std::cout` to be different in the app and in the lib, the one in lib will cause a segfault.

**Comment by Ignition** [comment]
When using `RTLD_DEEPBIND` it changes the order on how stuff is bound. IMO its a ~good security~ ok flag to ensure we don't accidentally link incorrect symbol from our app into the query module.
TODO: we should `__attribute__ ((visibility ("hidden")))` things we do not expect to export to QM (better security, it would prevent QM from maliciously binding and manipulating memgraph).
But symbols from libstdc++ we do want to bind and use in QM.
`RTLD_DEEPBIND` would find it correctly but it would be a dynamical reference, which wouldn't have been initialised correctly.
Fix is to ensure our application memgraph uses relocatable/dynamic symbol for libstdc++ symbols. Hence our app should be placement independent code.
`set_property(TARGET memgraph PROPERTY POSITION_INDEPENDENT_CODE ON)`

**Comment by Ignition** [comment]
Useful background information https://gcc.gnu.org/bugzilla/show_bug.cgi?id=42679
