### ISSUE TITLE
Make error message `Function '{}' doesn't exist.`  informative and correct

### ISSUE THREAD

**Issue by kgolubic** [memgraph/memgraph#1564]
**Memgraph version**
Memgraph Platform 2.12.1

**Environment**
Platform running in Docker on Windows 11.

**Describe the bug**
In the line https://github.com/memgraph/memgraph/blob/eceed274d983d6f135189d945c407b30b6e506a6/src/query/frontend/ast/ast.hpp#L1325 we have an error message that is shown if something is wrong. 

**To Reproduce**
1. Run the following query

```
MATCH (p:Person)
WHERE exists(p)
RETURN p.name
ORDER BY p.name;
```

I get an error message that says that function EXISTS doesn't exist, [but we do have it](https://memgraph.com/docs/querying/functions#pattern-functions).

**Expected behavior**
To provide error that has the more correct info. In my case, the function does exist so why does the error message says that it doesn't exist?

**Logs**

![image](https://github.com/memgraph/memgraph/assets/46486712/06c33d5f-7582-4fc6-866c-5b747e0abe07)

**Additional context**

**Verification Environment**
Once we fix it, what do you need to verify the fix?
Do you need:
* Full Memgraph platform?

**Comment by hal-eisen-MG** [comment]
@kgolubic We seem to have a documentation discrepancy. Another [page](https://memgraph.com/docs/querying/differences-in-cypher-implementations) says we don't support `exists`

**Comment by kgolubic** [comment]
@hal-eisen-MG you are right. I've [created the issue in the docs repo](https://github.com/memgraph/documentation/issues/474), and I'll deal with it.

**Comment by hal-eisen-MG** [comment]
@kgolubic Please be patient. We might add `exists` so I'm not sure which documentation is wrong yet.

**Comment by kgolubic** [comment]
@hal-eisen-MG got it.  I’ll check with developers if we support checking against property or do we support only checking against pattern. I’ve updated the documentation ticket to be more specific.

**Comment by kgolubic** [comment]
@hal-eisen-MG I’ve checked with the developers. At the moment we can use exists only with patterns. The documentation doesn’t need any updates regarding this behavior. Update will be needed if we implement possibility to check against the property.

**Comment by andrejtonev** [comment]
This is an interesting case.
What is happening is that `WHERE EXISTS(n)` does not satisfy our grammar for the `EXISTS` and is defaulting to a function call.
We really do not have a function called `EXISTS` and so we fail.
The "correct" way to write the above would be `WHERE EXISTS ((n))`. This is because `(n)` signifies a node. It is our grammar that is forcing there to be these double parentheses.
There are 2 options that I see:
1. Update the grammar. We could use the same grammar we use for MATCH. But this would mean we would also allow things like `WHERE EXISTS ()-`

**Comment by hal-eisen-MG** [comment]
I'm very tempted to fix this one with a documentation update. Given that we can use `IS NOT NULL` instead of `EXISTS` for the property, there's a good workaround already in place.
