### ISSUE TITLE
Query behavior changed: `count(*)>0` on an empty set

### ISSUE THREAD

**Issue by jchvz** [memgraph/memgraph#1582]
**Memgraph version**
v2.13.0

**Environment**
Docker: an image with the base image `memgraph/memgraph-mage:1.13-memgraph-2.13` + some query modules

**Describe the bug**
The operation `count(*)>0` on an empty set used to return `false`, but now it returns an empty set. 

Here's a side-by-side of the behavior on `v2.12` vs `v2.13`:

![image](https://github.com/memgraph/memgraph/assets/39979644/8faa13ed-b32c-44d6-b877-b83e4922dab4)

**To Reproduce**
- Ensure the label `DoesNotExist` really does not exist :)
- Run this query on both memgraph `v2.12` and `v2.13` (as shown above):
```cypher
MATCH (n:DoesNotExist) RETURN count(*)>0 AS exists;
```
- Observe the different results

**Expected behavior**
We expect that the example query would return `true` if the nodetype exists and `false` if it does not. Forgive me if this is intended / not a bug, but it was an unexpected change for us. We use this to check if a nodetype exists in the graph.

**Logs**
n/a

**Additional context**
None

**Verification Environment**
Would appreciate a docker image for AMD to verify the fix. Perhaps with MAGE but that is not a requirement.

**Comment by antepusic** [comment]
Hello @jchvz! I’ve opened #2095 in order to resolve the issue you’re having. The PR contains tests which verify that your query should now work as expected.

**Comment by jchvz** [comment]
Thanks @antepusic !
