### ISSUE TITLE
Missing POINT type (feature request)

### ISSUE THREAD

**Issue by Apidcloud** [memgraph/memgraph#1583]
This is not a bug, but more of a feature request (and a blocker for me) to be further compatible with Neo4j. We rely on using the POINT type to save lists of locations inside a single node.

The use case is that the same place (think of a city or even the same street) can have multiple more fine/specific locations (latitude, longitude, height/altitude).

We can then use point.distance to check if said locations are within a certain radius (i.e., nearby). More info at https://neo4j.com/docs/cypher-manual/current/functions/spatial/ .

Let me know if you would need more details.

### Progress
* https://github.com/memgraph/memgraph/pull/2208
* https://github.com/memgraph/memgraph/pull/2298
* https://github.com/memgraph/memgraph/pull/2362

**Comment by antejavor** [comment]
Hi @Apidcloud, thanks for opening the issue 🚀 , [the milestone for Memgraph 2.14](https://github.com/memgraph/memgraph/milestone/13) contains the tasks to add geospatial datatype support. 

This is a subset of that issue. It may end up in 2.14.

**Comment by Apidcloud** [comment]
Ah, awesome!

**Comment by gitbuda** [comment]
Quick update, the geospatial capabilities are not planned for v2.14 (the milestone was not up to date), sorry! It's not known where geospatil datatypes will be released at the moment... @Apidcloud I'm happy to jump on a call and figure out if there is a short term alternative 🤔  CC @antejavor

**Comment by antejavor** [comment]
Hi @Apidcloud, have you been able to avoid this blocker and push the project further to be compatible with Memgraph?

**Comment by Apidcloud** [comment]
Hey @antejavor 

Unfortunately no. There's a few (at least 1 big) other blockers that come to mind; the high availability from the cloud hosted solution is one example.

**Comment by matea16** [comment]
Hi @Apidcloud, I'm sorry to hear that. Could you tell us about the other blockers you encountered? We'd appreciate any feedback you have to help improve our product. 
If it would be easier, we can always jump on a [quick call](https://calendly.com/d/3jv-347-54b/memgraph-office-hours)

**Comment by Ignition** [comment]
@Apidcloud FYI the `point` datatype will be part of v2.19 as a soft release (undocumented). If that works for your use-case then that is good news. We will be working on spatial indexing features for an upcoming release.

**Comment by katarinasupe** [comment]
@Ignition can this be closed now?

**Comment by Ignition** [comment]
> @Ignition can this be closed now (with Memgraph 2.21)?

Still some other work to deliver around withinbbox and possible UX improvement to make index usage occur in more situations.

I'm happy to close this issue. The functional requirements are met.

**Comment by katarinasupe** [comment]
I will close this issue then. Please open new issues for what you mentioned above (future work). Thank you 🙏
