### ISSUE TITLE
MAGE info settings

### ISSUE THREAD

**Issue by 1191000814** [memgraph/memgraph#1591]
When I want to build an algorithm with MAGE, but when I write a bug, **the query result only has the error message, not the information I custom entered in the module**, which makes it difficult for me to know what the bug is? Is it possible to display the information I entered in the query structure window?

**Comment by 1191000814** [comment]
like this
![image](https://github.com/memgraph/memgraph/assets/79617801/50ad5b29-6602-490a-a22c-5845f4cf85a0)

**Comment by gitbuda** [comment]
Hi! Maybe you can use Python Query Module logger to print out what is happening inside the module, an example of such module:
```
import mgp
@mgp.read_proc
def log(
  context: mgp.ProcCtx,
  data: mgp.Nullable[mgp.Any]
) -> mgp.Record(done=bool):
  # https://memgraph.com/docs/custom-query-modules/python/python-api#logger-objects
  logger = mgp.Logger()
  try:
    ... code ...
  except Exception as e:
    logger.info(str(e)) # or something better
  return mgp.Record(done=True)
```
Hope this helps!

**Comment by 1191000814** [comment]
It may not I want, I mean that if I use "print(...)" in the MAGE query module, where I can see the info I print?

like this:

import mgp
@mgp.read_proc
def print_info():
    print("...")

**Comment by imilinovic** [comment]
Hello, are you compiling Memgraph from source or are you using docker?

If you are compiling from source you can see the output in the console where you ran Memgraph.

**Comment by 1191000814** [comment]
Thanks! I am using a docker with windows, I have solved the problems! not by directly using the database, but using the mock python api: https://memgraph.com/docs/custom-query-modules/python/mock-python-api.
