### ISSUE TITLE
Storage mode flag not working as expected

### ISSUE THREAD

**Issue by katarinasupe** [memgraph/memgraph#1599]
**Memgraph version**
2.13

**Environment**
Docker, Mac M1

**Describe the bug**
When I set flag --storage-mode to IN_MEMORY_ANALYTICAL it doesn't actually change the storage mode, but only the value of the --storage-mode flag in memgraph.conf.

**To Reproduce**
1. Run Memgraph with: `docker run --name memgraph-test -p 7687:7687 -p 7444:7444 memgraph/memgraph:2.13.0 --storage-mode=IN_MEMORY_ANALYTICAL`

**Expected behavior**
Storage mode is changed to IN MEMORY ANALYTICAL. 

**Logs**
![Screenshot 2023-12-20 at 13 36 20](https://github.com/memgraph/memgraph/assets/61758502/bfbac2a6-eddc-4efe-986b-770b3a02bdac)
![Screenshot 2023-12-20 at 13 36 34](https://github.com/memgraph/memgraph/assets/61758502/b25f4f43-203b-460d-83db-02d26db87bab)

**Additional context**
I suspect that the issue is not only in the result of SHOW STORAGE MODE query, but that the storage mode isn't actually changed. The reason for that is because user tried it and import is not any faster.

**Comment by as51340** [comment]
Until we investigate the issue, please use `STORAGE MODE IN_MEMORY_ANALYTICAL` to change the storage mode.
