### ISSUE TITLE
Figure out how to safely call memgraph via client from query module (auth concern)

### ISSUE THREAD

**Issue by gitbuda** [memgraph/memgraph#1650]
Merge application roles from the "role provider" roles
If you don't have credentials it should, some form of SSO integration
Maybe an option is to integrate with auth module

**UPDATE(2024-01-20)**
As far as we understand it's not possible to securely execute a query from a query module using any client because the password somehow has to be injected (very insecure). The solution seems to be to extend the query module by adding the `execute_query` function, with the following properties:
* pass only query string + query params and implement pull logic under the API:
* limit the execution to a single query transaction (to avoid implementing multiple query pulls, a later extension)
* the query should be a new concurrent transaction (equivalent to executing a query from the client)
* user authentication is not needed because the top query authentication should be enough

**Comment by Josipmrden** [comment]
The resolution so far is to make the procedure API method `execute_query` which will be able to bypass the authentication and execute the query under the same user.
