### ISSUE TITLE
Load CSV not working correctly with NULL values

### ISSUE THREAD

**Issue by kgolubic** [memgraph/memgraph#1652]
**Memgraph version**
Memgraph Platform with Memgraph 2.13.0 and Lab 2.10.0

**Environment**
Docker version of Memgrpah Paltform.

**Describe the bug**

**To Reproduce**
1. Run the query 
```
LOAD CSV FROM "iot.csv" WITH HEADER AS row
WITH row WHERE row.device_id IS NOT NULL AND row.device_type IS NOT NULL
CREATE (d:Device {id: row.device_id, type: row.device_type});
```

2. Run the query
`MATCH (n) RETURN n; `

**Expected behavior**
Since the CSV file looks like this

```
device_id,device_type,connected_from,connected_to
200,Thermostat,,
201,Smoke Detector,,
202,Light Sensor,,
203,Security Camera,,
204,Smart Lock,,
,,200,201
,,200,202
,,200,203
,,201,203
,,202,204
```

I would expect only to get 5 nodes, but I get 10 nodes.

```
{"n":{"id":30,"labels":["Device"],"properties":{"id":"200","type":"Thermostat"},"type":"node"}}
{"n":{"id":31,"labels":["Device"],"properties":{"id":"201","type":"Smoke Detector"},"type":"node"}}
{"n":{"id":32,"labels":["Device"],"properties":{"id":"202","type":"Light Sensor"},"type":"node"}}
{"n":{"id":33,"labels":["Device"],"properties":{"id":"203","type":"Security Camera"},"type":"node"}}
{"n":{"id":34,"labels":["Device"],"properties":{"id":"204","type":"Smart Lock"},"type":"node"}}
{"n":{"id":35,"labels":["Device"],"properties":{"id":"","type":""},"type":"node"}}
{"n":{"id":36,"labels":["Device"],"properties":{"id":"","type":""},"type":"node"}}
{"n":{"id":37,"labels":["Device"],"properties":{"id":"","type":""},"type":"node"}}
{"n":{"id":38,"labels":["Device"],"properties":{"id":"","type":""},"type":"node"}}
{"n":{"id":39,"labels":["Device"],"properties":{"id":"","type":""},"type":"node"}}
```

How are we storing` ,,202,204` this? Do we store `,` with NULL or as an empty string?

![image](https://github.com/memgraph/memgraph/assets/46486712/5bb3693b-d2cc-451b-aa2d-372980d51ad6)

I've also tried to run queries:

```
LOAD CSV FROM "iot.csv" WITH HEADER AS row
WITH row WHERE row.device_id IS NOT "" AND row.device_type IS NOT ""
CREATE (d:Device {id: row.device_id, type: row.device_type});
```

```
LOAD CSV FROM "iot.csv" WITH HEADER AS row
WITH row WHERE row.device_id IS NOT '' AND row.device_type IS NOT ''
CREATE (d:Device {id: row.device_id, type: row.device_type});
```

But these two failed with an error line `2:37 mismatched input '""' expecting CYPHERNULL`

If we are storing an empty string why do these two queries fail?

**Logs**
If applicable, add logs of Memgraph, CLI output or screenshots to help explain
your problem.

**Additional context**

I've used several CSV files: one with a comma, a single quote and double quote. The result was always the same.

[comma - iot.csv](https://github.com/memgraph/memgraph/files/13988046/iot.csv)
[single qoute - iot2.csv](https://github.com/memgraph/memgraph/files/13988045/iot2.csv)
[double qoute - iot3.csv](https://github.com/memgraph/memgraph/files/13988044/iot3.csv)

**Verification Environment**
Once we fix it, what do you need to verify the fix?
Do you need:
* Full Memgraph platform

**Comment by Josipmrden** [comment]
https://memgraph.com/docs/data-migration/csv#load-csv-clause-syntax
@kgolubic  nullif should solve this

**Comment by kgolubic** [comment]
@Josipmrden, you are right. This query works:

```
LOAD CSV FROM "iot.csv" WITH HEADER NULLIF '' AS row
WITH row WHERE row.device_id IS NOT NULL AND row.device_type IS NOT NULL
CREATE (d:Device {id: row.device_id, type: row.device_type});
```

**Comment by Josipmrden** [comment]
can we close this issue? @kgolubic

**Comment by kgolubic** [comment]
Yes, we can.

**Comment by Josipmrden** [comment]
Yes, please then close it :)
