### ISSUE TITLE
Query parsing and plan generation times

### ISSUE THREAD

**Issue by 1sand0s** [memgraph/memgraph#1669]
Hello All,

I am trying to identify the breakup of the end to end execution time (query parsing + plan generation + plan execution). Any pointers on how to obtain this information?

The PROFILE directive only prints the time spent in executing each of the logical plan operators.

I am comfortable with modding Memgraph source code to achieve this.

Any help/direction would help.

Thanks

**Comment by matea16** [comment]
hI @1sand0s, to get a breakdown of the execution time, you set the -verbose_execution_info flag to true when running `mgconsole`. It will extend the information about the execution time with the `COST estimate`, `PARSING time`, `PLAN EXECUTION time` and `PLANNING TIME`. You can check out our [docs](https://memgraph.com/docs/getting-started/cli#query-execution-time) for more detailed explanations and usage.
I hope this answers your question.

**Comment by 1sand0s** [comment]
@matea16 Thank you for the prompt response. 

I am curious if this information can be obtained by means of the Neo4j Java driver?

**Comment by matea16** [comment]
Hi @1sand0s, sorry for the late response. I've never tested this using the Neo4j Java driver and from a quick browse, I assume the driver interacts with the database, but doesn't directly expose the detailed execution time breakdown information. Have you been able to test it out in the meantime?

**Comment by katarinasupe** [comment]
Hi @1sand0s, I will close this issue due to the inactivity. If you have more questions, open a new issue, ask on our [Discord server](https://discord.gg/memgraph) or [schedule an office hours call](https://memgraph.com/office-hours).
