### ISSUE TITLE
Cannot build v2.14.0

### ISSUE THREAD

**Issue by 1sand0s** [memgraph/memgraph#1689]
**Memgraph version**
2.14.0

**Environment**
5.15.0-84-generic  20.04.1-Ubuntu, x86_64

**Describe the bug**
ERROR: failed validation of new value '/usr/lib/memgraph/query_modules' for flag 'query_modules_directory'
Traceback (most recent call last):
  File "../../config/generate.py", line 110, in <module>
    flags = extract_flags(args.memgraph_binary)
  File "../../config/generate.py", line 34, in extract_flags
    root = ET.fromstring(data)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1321, in XML
    return parser.close()
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
make[2]: *** [src/CMakeFiles/memgraph.dir/build.make:208: memgraph-2.14.0_Debug] Error1
make[2]: *** Deleting file 'memgraph-2.14.0_Debug'
make[1]: *** [CMakeFiles/Makefile2:7727: src/CMakeFiles/memgraph.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**To Reproduce**
1. source /opt/toolchain-v4/activate
2. ./init
3. cd build
4. cmake .. && make memgraph

**Expected behavior**
Builds memgraph binaries

**Comment by karmenrabar** [comment]
Thank you for reporting this @1sand0s. I will reproduce it and get back to you :)

**Comment by gitbuda** [comment]
@1sand0s This is an error in generating the default config values (it's an automated process). Did you change something in the code because this doesn't happen on the latest `master`? If yes, could you post the git patch here?

**Comment by 1sand0s** [comment]
@gitbuda Seems like a leftover config file in`/etc/memgraph` from a previous memgraph installation was messing with the build. `sudo apt-get remove memgraph` did not remove this folder so I had to manually remove it and then build memgraph. That worked!

Thanks!
