### ISSUE TITLE
Add support for DROP DATABASE

### ISSUE THREAD

**Issue by gitbuda** [memgraph/memgraph#1692]
`DETACH DELETE` is a complex operation -> sometimes, drop all is all one needs

Options and ideas (take a look at @Josipmrden comment below):
* on large detach delete -> warning
* drop database everything (streams, triggers, anything owned by a database)
* drop database data-only
* what to do with streams, triggers? data-only drop shouldn't touch anything except data, while `DROP DATABASE` should stop and drop everything 🤔

**Comment by lomnido** [comment]
Such command will be nice, but at the same time very dangerous indeed.

I advise using additional option like "DO-AS-I-SAY=true" so it will not be executed by accident or something like that.

**Comment by katarinasupe** [comment]
Until the periodic delete function is available on MAGE, I added workaround instructions for users in the docs -> https://memgraph.com/docs/querying/clauses/delete#how-to-lower-memory-consumption
