### ISSUE TITLE
Query causes a big Memory spike and kills Memgraph (IN_MEMORY_ANALYTICAL) 

### ISSUE THREAD

**Issue by antejavor** [memgraph/memgraph#1757]
**Memgraph version**
Memgraph v2.14

**Environment**
Memgraph in docker 

**Describe the bug**
Running a specific query (private) causes a Memgraph to crash.  Query crashes Memgraph only IN_MEMORY_ANALYTICAL mode, not in the IN_MEMORY_TRANSACTIONAL.  

**To Reproduce**
This is missing, it will be filled in later. 

**Expected behavior**

**Logs**
If applicable, add logs of Memgraph, CLI output or screenshots to help explain
your problem.

**Additional context**

**Verification Environment**
Once we fix it, what do you need to verify the fix?
Do you need:
* Plain memgraph package -> for which Linux?
* Plain memgraph Docker image?
* Which architecture do you use ARM | x86?
* Full Memgraph platform?

**Comment by DavIvek** [comment]
Still no steps to reproduce, can we close this @antejavor ?
