### ISSUE TITLE
Create a flag to automatically generate indices

### ISSUE THREAD

**Issue by gvolfing** [memgraph/memgraph#1768]
Implement a solution to automatically create indices in Memgraph. Since edge-type indices are a lot more rare than label and label+property indices we might want to create separate flags automatically create them.
Question is do we want flags for:
 - Label indices, Label+Property indices, Edge-type indices? (3 separate)
 - (Label indices, Label+Property indices), (Edge-type indices)? (2 separate "traditional indices" + "edge-type")
 - One flag for all
 The last one is probably a bad idea, because most use-cases would likely never require edge-type indices.

**Comment by gvolfing** [comment]
One potential solution might be tied to this issue
https://github.com/memgraph/memgraph/issues/1546

This is not necessarily the way we have to go about this but if we want to detect what indices are currently existing in the database, we either have to check that here, or with the index data-structures.

**Comment by gitbuda** [comment]
A note, only label / edge-type index creation by default is I think an option here, but will expand 😄

**Comment by Josipmrden** [comment]
Done with the PRs linked
