### ISSUE TITLE
Expand, collapse and hide buttons does not work

### ISSUE THREAD

**Issue by pwretmo** [memgraph/memgraph#1787]
**Memgraph version**

Memgraph Lab v2.12.1

**Environment**

Windows x64 (Chrome and Firefox)

**Container image**

docker.io/memgraph/memgraph-platform:2.12.1

**Describe the bug**

In graph result view, the Expand, Collaps and Hide buttons in additional information does not work. Nothings happens when those are clicked.

**To Reproduce**

-  Select a node in the graph result. Additional information is opened on the right.
-  Click one of the buttons.

**Actual behavior**
Nothing happens.

**Expected behavior**
Node is collapsed, expanded or hidden.

**Comment by antejavor** [comment]
Hi @pwretmo, thanks for opening the issue 🚀  We will look and get back to you on this one.

**Comment by tonilastre** [comment]
@pwretmo Just a tip before this is fixed, you can use double-click on the node to expand/collapse. That seems to work ok.

**Comment by tonilastre** [comment]
@pwretmo I just wanna let you know that the fix for the reported issue has been released, Lab v2.12.2. Thanks a lot for reporting it!
