### ISSUE TITLE
Unit subquery creates nodes until OOM

### ISSUE THREAD

**Issue by katarinasupe** [memgraph/memgraph#1829]
**Memgraph version**
Memgraph 2.15

**Environment**
Docker, Mac M1

**Describe the bug**
When you run a unit subquery, nodes are being created until OOM. Instead, the query should create 20 nodes and return count of 4 (create 5 copies for each of the 4 existing nodes)

**To Reproduce**
1. Create dataset
```
CREATE
 (a:Person:Child {name: 'Alice', age: 20}),
 (b:Person {name: 'Bob', age: 27}),
 (c:Person:Parent {name: 'Charlie', age: 65}),
 (d:Person {name: 'Dora', age: 30})
 CREATE (a)-[:FRIEND_OF]->(b)
 CREATE (a)-[:CHILD_OF]->(c)
 CREATE (a)-[:OWES {dollars: 20}]->(c)
 CREATE (a)-[:OWES {dollars: 25}]->(b)
 CREATE (b)-[:OWES {dollars: 35}]->(d)
 CREATE (d)-[:OWES {dollars: 15}]->(b)
 CREATE (d)-[:OWES {dollars: 30}]->(b)
CREATE (:Counter {count: 0})
```
2. Run a query:
```
MATCH (p:Person)
CALL {
  WITH p
  UNWIND range (1, 5) AS i
  CREATE (:Person {name: p.name})
}
RETURN count(*)
```

**Expected behavior**
Returned result: 4 (20 created notes, 20 properties set, 20 labels added). 

**Additional context**
I am checking the Cypher compatibility, so I stumbled upon this. This was not reported by any community member yet.

**Comment by DavIvek** [comment]
<img width="903" alt="Screenshot 2024-07-08 at 12 02 03" src="https://github.com/memgraph/memgraph/assets/88043717/27faff66-3f7d-48ff-9607-15c712e52ef0">

Looks to me that this was fixed in one of the previous releases.
