### ISSUE TITLE
`ScanAllByLabelPropertyRange` does not work with `<` and `>` operators

### ISSUE THREAD

**Issue by Josipmrden** [memgraph/memgraph#1954]
**Memgraph version**
v2.16

**Environment**
Docker

**Describe the bug**
Although `ScanAllByLabelPropertyRange` operator is used in the query, it does not capture both lower and upper bound of the query.

**To Reproduce**
1. CREATE INDEX ON :Node;
2. CREATE INDEX ON :Node(id);
3. FOREACH (i in range(1, 1000000) | CREATE (:Node {id: i}));
4. PROFILE MATCH (n:Node) WHERE n.id > 1000 and n.id < 2000 RETURN sum(n.id);

**Expected behavior**
`ScanAllByLabelPropertyRange` operator should be applied with much smaller amount of rows.

**Details**
The details are in the `index_lookup.hpp` and `preprocess.cpp`
`void Filters::AnalyzeAndStoreFilter(Expression *expr, const SymbolTable &symbol_table)` function does not have the capability of generating a `PropertyFilter` of `Type::Range`, and that's why only upper or lower bound is written inside a property filter. 

In the `index_lookup.hpp`, that filter is consumed and a `ScanAllByLabelPropertyRange` is applied, but with the maximal upper or lower bound, because we have applied only one filter to form an index. Furthermore, the second filter operation will be left out and virtual calls will be spent on unnecessary verification.

Possible solutions:
1. Make processing of filters more effective -> this is a bit harder because the function `SplitExpressionOnAnd` is splitting those filters, but a post filter rewriter can do the job
2. Make a rewriter on the operator level like we do with index lookup

**Comment by Ignition** [comment]
Fix being worked on #2055
