### ISSUE TITLE
Question: suggestion for storing state?

### ISSUE THREAD

**Issue by vsoch** [memgraph/memgraph#1975]
Hi! I'm new to using Memgraph, and am going to test it for a graph database backend for our resource manager and scheduler. I'm wondering how memgraph (if it can) represent state? For example, the basic graph is resources (nodes) and relationships between them (a node has some number of cores) and then the state would be whether some subset of those cores are allocated (being used) or not. So typically when we have a scheduling problem we consider these states to determine if a request for work can be matched (to free resources). Any suggestions / pointers would be appreciated, thank you!

**Comment by matea16** [comment]
Hi @vsoch, not sure what exactly is the context of representing the state, are you looking to store it in a property or is there other solution you're looking for? What's your use case, are you just starting to test out Memgraph? 
Also, since GitHub is usually dedicated to opening issues and feature requests, feel free to join us on [Discord](https://discord.gg/memgraph) where we usually answer questions and talk to our users

**Comment by vsoch** [comment]
> Hi @vsoch, not sure what exactly is the context of representing the state, are you looking to store it in a property or is there other solution you're looking for?

I'm not sure how it might be stored with Memgraph, why I'm asking :) For our graphs we have everything custom implemented in C++ and objects associated with boost indices.

> What's your use case, are you just starting to test out Memgraph?

Yes, and specifically assessing it for a graph scheduler backend.

Thanks for answering here - I am hoping I don't need to join another chat space to have questions answered about software, at least I'm accustomed to that happening on Github where the conversation is easy to find in the future.

**Comment by antejavor** [comment]
> I'm not sure how it might be stored with Memgraph, why I'm asking :) For our graphs we have everything custom implemented in C++ and objects associated with boost indices.

Hi @vsoch , a memgraph is a [label property graph](https://en.wikipedia.org/wiki/Graph_database#Graph_models) database.  Hence you use it as that model. If you are new to label property graphs I would recommend skimming this: https://memgraph.com/docs/fundamentals/graph-modeling

You can model your resources allocation problem as graph, keep it in a updated state and query based on the node (core) properties as you would like. 

So the thing you are describing (If I understood correctly, is possible to achieve with Memgraph)

**Comment by vsoch** [comment]
Thanks! So if I understand correctly, I'd need to have everything represented in key values pairs associated with nodes. For example, if a physical node resource is scheduled, it might have scheduled=true, or (because that is too simple for a need to find a time into the future) more likely, a timestamp when the node will next be free that increases as it is scheduled. 

I'll think more about this - I understand the idea of the label graph database, I'm just not convinced it will be very good to hold states that have a fine grained temporal quality and that change fairly quickly.

**Comment by antejavor** [comment]
Hi @vsoch, I will close this issue due to the inactivity. If you have more questions, open a new issue, ask on our [Discord server](https://discord.gg/memgraph) or [schedule an office hours call](https://memgraph.com/office-hours).
