### ISSUE TITLE
Audit logs not logging IP properly

### ISSUE THREAD

**Issue by tonijurjevic96** [memgraph/memgraph#2079]
IP address not being logged correctly, 0.0.0.0

**Comment by antepusic** [comment]
Hello @tonijurjevic96 & thanks for reporting the issue! Upon discovering this, did you see whether this issue applied to IP addresses in general, or was `0.0.0.0` the only adress not to be logged correctly?

**Comment by tonijurjevic96** [comment]
It refers to IP addresses in general I think
