### ISSUE TITLE
Crash about Pattern Comprehension in Return

### ISSUE THREAD

**Issue by ljhhuxiaoba** [memgraph/memgraph#2112]
I executed a query on my empty memgraph database and get a crash.

memgraph version:2.17.0
operating system: windows 11
API：Cypher version 9
query:RETURN [(n0)-[]->(n1)|1]
error message:Query failed: Connection was closed by server

Actual behavior:
The query failed and the memgraph container exited abnormally with the error message.

**Comment by katarinasupe** [comment]
Hi @ljhhuxiaoba and thank you for opening this issue. Based on your other issues, I believe this is not a blocker for you?

**Comment by ljhhuxiaoba** [comment]
Yes.I'm just running a test.

**Comment by DavIvek** [comment]
In latest 2.18 release Memgraph doesn't crash anymore, instead an exception is thrown:
`Client received query exception: Not yet implemented: One of the branches in pattern comprehension is null! Please contact support.`

Can we close this? cc @katarinasupe

**Comment by katarinasupe** [comment]
I will close this issue based on @DavIvek's comment above. @ljhhuxiaoba I hope that works for you.
