### ISSUE TITLE
Crash due to assertion failure, "Expected to generate all filters"

### ISSUE THREAD

**Issue by CelineWuest** [memgraph/memgraph#2116]
When running the following query:
```cypher
CALL {
	RETURN 0 AS x
} MATCH ({n0:x})
RETURN 0
```

My memgraph instance crashes due to an abort and a message "Expected to generate all filters".

I encountered this issue when testing queries against a locally compiled instance of the memgraph master branch with address sanitization enabled in a Docker container running **debian bullseye**.

This query also crashes the docker image **memgraph/memgraph:2.17.0**.

### Steps to reproduce
Run the following query and observe the database crashes:
```cypher
CALL { RETURN 0 AS x } MATCH ({n0:x}) RETURN 0
```

### Expected behavior
The query should run successfully

### Actual behavior
The query crashes the database.

**Comment by katarinasupe** [comment]
Hi @DominicWuest, thank you for reporting this. Is this issue a blocker for your work with Memgraph? How severe the issue is for you?

**Comment by DominicWuest** [comment]
Hi @katarinasupe!
This report and all other reports I created were found by my fuzzer, so technically they're the opposite of a blocker for me :sweat_smile:

**Comment by CelineWuest** [comment]
Thanks for looking into this @as51340!
But I'm not sure why this query would be invalid? From my understanding, variables returned from a CALL subquery should be accessible in subsequent clauses.
I ran my original query on an instance of Neo4j 5.25.1, and it reported no error.

**Comment by as51340** [comment]
@CelineWuest you are right, from Cypher point of view this query should be valid. Because of Memgraph's implementation we need `WITH` clause.
