### ISSUE TITLE
HA switching data instances issue

### ISSUE THREAD

**Issue by tonijurjevic96** [memgraph/memgraph#2121]
When main instance is shutdown and when you try to switch to replica coordinator logic seems to get messed if some api is still using shutdown instance and you get following error 
Assertion failed in file at line 486 Expression: 'bolt_mains.size() <= 1 Message: 'There can be at most one main instance active!'

**Comment by katarinasupe** [comment]
@tonijurjevic96 Importance is no longer being used. We use Severity, Effort, Frequency and Reach. If you agreed on smth else for customer issues, then ignore me 😄

**Comment by antepusic** [comment]
Closing this issue as the related PR (see above) has been merged.
