### ISSUE TITLE
Can't create constraint for property 'text'

### ISSUE THREAD

**Issue by katarinasupe** [memgraph/memgraph#2136]
The following query causes exception:

`CREATE CONSTRAINT ON (n:NodeTwo) ASSERT EXISTS (n.text);`

Causes:
`mgclient.DatabaseError: line 1:51 mismatched input 'text'`

Note: this was working as expected on Memgraph 2.5. I now updated GQLAlchemy to 2.17 and this test is failing. I will just update the test, so this is not a blocker for me.

**Comment by andrejtonev** [comment]
`TEXT` got added to the list of Cypher reserved words when text search was added.
CC @antepusic

**Comment by antepusic** [comment]
@andrejtonev is right – @katarinasupe can you accordingly close this issue?

**Comment by katarinasupe** [comment]
Meanwhile, I remembered the workaround from a similar reported issue:
`CREATE CONSTRAINT ON (n:NodeTwo) ASSERT EXISTS (n.`text`);`
