### ISSUE TITLE
valueType() doesn't work on Enum

### ISSUE THREAD

**Issue by katarinasupe** [memgraph/memgraph#2161]
Memgraph 2.18 - rc2 

To reproduce:
```
CREATE ENUM Status VALUES { Good, Okay, Bad };

WITH Status::Good as wanted_enum
CREATE (n:Node {enum_prop: wanted_enum});

MATCH (n:Node)
RETURN valueType(n.enum_prop);
```

**Comment by katarinasupe** [comment]
Below queries don't throw `not yet implemented` like defined in specs, but `line 1:6 no viable alternative at input 'DROPENUM'`.
```
ALTER ENUM Status REMOVE VALUE Terrible;
DROP ENUM Status;
``` 
@Ignition

**Comment by antepusic** [comment]
@katarinasupe Now that the above PR has been merged, can you fill me in on whether I can close this issue?
