### ISSUE TITLE
Query without variable not utilizing edge type index

### ISSUE THREAD

**Issue by matea16** [memgraph/memgraph#2164]
Memgraph 2.18 - rc2

**Description**
When running two similar queries, one with a variable and one without, the query without the variable does not utilize the edge type index

**To reproduce**
Create nodes and relationship:
`CREATE (n:Node), (m:Node), (n)-[:CONNECTED_TO {id:3}]->(m)`

Create edge type index:
`CREATE EDGE INDEX ON :CONNECTED_TO(id)`

First query:
`PROFILE MATCH path=()-[r:CONNECTED_TO {id:3}]-() RETURN path`

Generates this profile:
![screenshot 2024-07-03](https://github.com/memgraph/memgraph/assets/80577904/366931e2-cfa3-4439-9284-28db1be63384)

And the second query without the variable r:
`PROFILE MATCH path=()-[:CONNECTED_TO {id:3}]-() RETURN path;`

Generates this profile that uses ScanAll:
![screenshot 2024-07-03 101324](https://github.com/memgraph/memgraph/assets/80577904/0cb0e642-4212-46da-b3a9-9d121da75f55)

**Comment by DavIvek** [comment]
This got fixed in previous Memgraph releases.
