### ISSUE TITLE
Not able to include mgp.py in IDE

### ISSUE THREAD

**Issue by jmatak** [memgraph/memgraph#218]
When creating query modules for making procedures or transformations, would be nice to have a source code for mgp.py. This issue occured for multiple MAGE developers. One solution might be adding this file as some package (for example named mg-dev to) PyPI.

**Comment by antonio2368** [comment]
Thanks for the suggestion!
The mgp.py file is now uploaded to [PyPI](https://github.com/memgraph/mgp).
