### ISSUE TITLE
Remove system-replication out of experimental features

### ISSUE THREAD

**Issue by gitbuda** [memgraph/memgraph#2227]
"Just" remove the value/handling from `--experimental-enabled`, make the feature part of `replication` feature.

User quote: "There should be just two features, replication and HA. Replication is classic database replication where you have another copy of the database; primary and replica. HA automatic failover is a mechanism of making sure a given database is available if one node has an issue or breaking in any way."

**Comment by Ana-Marija-design** [comment]
Introducing complexity: Roles / multitenancy are not a community feature, but "system" replication deal w/it
