### ISSUE TITLE
Memgraph replica container dies abruptly with error 'The vertex must be inserted here!'

### ISSUE THREAD

**Issue by AkshayParihar** [memgraph/memgraph#2243]
**Memgraph version**
memgraph/memgraph:2.18.0

**Environment**
Using the docker image `memgraph/memgraph:2.18.0`.
Hosting in AWS EKS only Statefulset and Services (not coordinators).
The nodes support AMD architecture with CentOS.
AWS CSI driver v1.29.1-eksbuild.1 is used to manage EBS provisioning.
Community mode (not enterprise)

**Describe the bug**
In multiple scenarios, it appears the `Main` instance gets corrupted when an operation is done on Replica or Main. It yields the following error and the container gets restarted. It doesn't self-heal and gets stuck in CrashLoopBackoff state

**To Reproduce**

Scenario 1: When moving pods across multiple nodes.

1. Setup of 1 main 2 replica across different AZs
2. Register both Replicas on Main using the `REGISTER REPLICA REP1 ASYNC TO "memgraph-1-svc:10000"` command where memgraph-1-svc is the service which has only 1 target endpoint of memgraph-data-1 pod.
3. Taint the node on which Replica pod is running right now.
4. Force delete the Replica pod simulating a fault
5. Allow replic pod to get scheduled on another node
6. Drop Replica REP1 from Main and re-register
7. Do the above steps 3-4 times.
8. The same can be observed when Main is being moved around different nodes.

Scenario 2: When EBS volume goes down (outside of EKS env) and we spin up a new EBS to attach it to same pod.

1. Setup of 1 main 2 replica across different AZs
2. Register both Replicas on Main using the `REGISTER REPLICA REP1 ASYNC TO "memgraph-1-svc:10000"` command where memgraph-1-svc is the service which has only 1 target endpoint of memgraph-data-1 pod.
3. Go to AWS Console and Force detach the EBS volume of Main or Replica.
4. Delete the EBS volume.
5. Rollout restart the corresponding Statefulset.
6. Do this 2-3 times and the error can be reproduced.

**Expected behavior**
The error shouldn't occur and pods should be able to get placed without corrupting.

When this error occurs, we need to completely delete the entire stack (statefulset, pvc, pv and ebs) and recreate at the cost of loosing all data. Even if we create EBS from the last saved state, this error continues to occur (i am assuming this is because something in configuration memory is getting corrupted).

**Logs**
`[2024-07-25 10:30:02.880] [memgraph_log] [critical]
        Assertion failed in file  at line 287.
        Expression: 'inserted'
        Message: 'The vertex must be inserted here!'`

**Additional context**
This doesn't happen always but 1 out of 10 times, this issue is reproducible.

**Verification Environment**
Once we fix it, what do you need to verify the fix?
I would need to upgrade to the new version and perform the same steps multiple times to make sure this is not occurring again.

Do you need:
* Plain memgraph package -> for which Linux? NA
* Plain memgraph Docker image? Yes
* Which architecture do you use ARM | x86? AMD for managed env and for local testing ARM | x86
* Full Memgraph platform? NA

**Comment by antejavor** [comment]
@AkshayParihar Thanks for opening the issue, we will take a look.

**Comment by hal-eisen-MG** [comment]
I apologize for not updating this issue recently. We believe that there might already be a fix in a newer version of Memgraph. Please upgrade to v2.20 and let us know if that solves the problem.

**Comment by as51340** [comment]
@AkshayParihar this issue was fixed in recent releases. If you manage to reproduce it, feel free to open the issue again.
