### ISSUE TITLE
Replicas appear as "unknown" but are alive in HA cluster

### ISSUE THREAD

**Issue by antoniofilipovic** [memgraph/memgraph#2249]
Issue related to High availability:

After the MAIN data instance is shut down, other replica nodes appear as "unknown" in the coordinator, but the replicas are alive.

When restarting the master data node, the following error messages appear:

Coordinator Leader: [memgraph_log] [warning] Force reset failed since promoting replica to main failed.
Data Master: [memgraph_log] [error] Couldn't replicate data to instance_2. For more details
Data Replica: [memgraph_log] [error] Exception was thrown while processing an event in the RPC session associated with <IP>
Client: Memgraph.TransientError.MemgraphError.MemgraphError (At least one SYNC replica has not confirmed committing the last transaction.)

The problem here is that data instances appear in an unknown state.

**Comment by gitbuda** [comment]
@as51340, similar question here, is this still applicable? 🤔

**Comment by as51340** [comment]
@as51340 No, I think we should close it

**Comment by gitbuda** [comment]
Closing because it is not relevant anymore.
