### ISSUE TITLE
MAIN crashes when REPLICA crashes in HA

### ISSUE THREAD

**Issue by antoniofilipovic** [memgraph/memgraph#2250]
When a replica instance is shut down and then restarted, the MAIN  crashes simultaneously.
Data Master: [memgraph_log] [error] Couldn't replicate data to n2. For more details

**Comment by penghs520** [comment]
I encountered this problem on version 2.13.0, which version is it

**Comment by gitbuda** [comment]
@as51340, quick check, is this issue still relevant?

**Comment by as51340** [comment]
> @as51340, quick check, is this issue still relevant?

@gitbuda Never encountered it

**Comment by gitbuda** [comment]
Closing because it is not relevant anymore.
