### ISSUE TITLE
Lab - Allow other LLM models in Ollama besides llama2

### ISSUE THREAD

**Issue by cloudscalebytes** [memgraph/memgraph#2259]
**Memgraph version**
`memgraph/memgraph-mage:latest 2024-07-23T13:14:58`
`memgraph/lab:latest 2024-07-03T14:38:08`

**Environment**
Linux amd64, latest docker-compose and docker.

**Describe the issue**
GraphChat requires that Ollama have the llama2 model installed as only that model is supported.
I get the error message: `"Ollama setup failed: Error: Ollama call failed with status code 404: model 'llama2' not found, try pulling it first"`
Can other LLMs be supported like llama 3.1?  That could get much better results.

**To Reproduce**
1. Edit the LLM connection in the GraphChat configuration screen.
2. Specify the Ollama address, e.g http://ollama:11434
3. Click on 'Connect'

**Expected behavior**
It should work with models besides lllama2.

**Logs**
![image](https://github.com/user-attachments/assets/c5b0b25b-daf2-48fb-aac8-977b9a237f0d)

**Comment by katarinasupe** [comment]
Hi @cloudscalebytes, is this related to the issue you're experiencing? https://github.com/memgraph/memgraph-platform/issues/98

Lucky news -- a feature to select model name for Ollama is coming to Memgraph Lab v2.16, at the end of August! 😄 

I am glad to hear you're testing it out. What is your project about?

**Comment by katarinasupe** [comment]
Hi @cloudscalebytes, this should be resolved in Lab 2.16 -> https://memgraph.com/docs/release-notes#lab-v2160---aug-14-2024

I am closing this issue for now and please reopen it if it is not working for you.
