### ISSUE TITLE
Edge type indexes not working on upgrade

### ISSUE THREAD

**Issue by katarinasupe** [memgraph/memgraph#2380]
**Memgraph version**
2.20

**Environment** 
/

**Describe the bug**

> I updated memgraph to 2.20.0 and there seems to be a bug related to edge type indexes. I had previously a few million edges and existing edge indexes from 2.19. After upgrading, performing a query with any relationship label such as MATCH path = (e1)-[r1:REL_LABEL]->(e2) return path no longer produced any results. However, if I removed the REL_LABEL label from r1 it would clearly show that that relationship existed with that label. I was able to identify a fix by dropping the edge index using the query: DROP EDGE INDEX ON :REL_LABEL;. After adding the edge index again, the existing query seems to be working fine, but I'm not sure if that's because creating the edge index again skips scanning existing relationships and only indexes new relationships going forward.
I use in memory transactional mode, so I rely on the snapshots + WAL files. When memgraph restarts, it reloads the indexes and data on startup.

New info:
> The query seems to work if I do:
> MATCH path = (n)-[r:REL1|FAKE_LABEL]->(n2) return path but returns no data if I just do MATCH path = (n)-[r:REL1]->(n2) return path. 

> I'm wondering if it has to do with this PR, which no longer seg faults on aborts but potentially corrupts the edge indexes? https://github.com/memgraph/memgraph/pull/2310 
> I can't go back to 2.19 because I was seeing seg faults occur on that version. This version at least addresses that. I don't want to drop the edge indexes because my read performance really suffers without it.

**To Reproduce** 
/

**Expected behavior**
To work as in 2.19 and return the relationship

**Logs**
/

**Additional context**
I am pasting the community report. [Here is the source](https://discord.com/channels/842007348272169002/890969266600423504/1291807185533407313). 

**Verification Environment**
Once we fix it, what do you need to verify the fix?
Do you need:
* Plain memgraph package -> for which Linux?
* Plain memgraph Docker image?
* Which architecture do you use ARM | x86?
* Full Memgraph platform?

**Comment by katarinasupe** [comment]
Might be related -> https://github.com/memgraph/memgraph/issues/2177

**Comment by andrejtonev** [comment]
@katarinasupe 
Still investigating, but this seems to be a bug in the GC.
Seems like the edge type index incorrectly assigns elements for garbage collection.
