### ISSUE TITLE
memgraph crashed  due to data  stream

### ISSUE THREAD

**Issue by yongyong123** [memgraph/memgraph#2420]
**Memgraph version**
2.20

**Environment**
ARM,DOCKER all try

**Describe the bug**

Regardless of the specific data, this stream has been running very stably on version 2.14. However, when a large amount of data begins to sync, this exception can cause Memgraph to crash.
This causes version 2.19,2.20 to crash.
the code is very simple

**To Reproduce**
1.kafka data stream
**Expected behavior**

**Logs**
![image](https://github.com/user-attachments/assets/e8bc59d8-89e5-456e-9995-a619a3770334)

![image](https://github.com/user-attachments/assets/d2f1ae19-ce4f-4061-91ec-f348fc31c76b)

**Comment by matea16** [comment]
Hi @yongyong123 thank you for reporting this issue and providing steps on how to replicate

**Comment by matea16** [comment]
Since this is related to the issue https://github.com/memgraph/memgraph/issues/2350 and I see you've updated it with the logs from the newer version of Memgraph, I'll close this one to keep every relatable information in the same thread
