### ISSUE TITLE
`any()` function returns NULL instead of FALSE on empty list

### ISSUE THREAD

**Issue by dracoooooo** [memgraph/memgraph#2481]
**Memgraph version**
2.21.0

**Environment**
Docker

**Describe the bug**
I have encountered unexpected behavior with the any() function while using Memgraph. I think the `any()` function should return FALSE when applied to an empty list. However, in Memgraph, it appears to return NULL, which affects query results when used in the WHERE clause.

**To Reproduce**

Execute the following Cypher queries:
```cypher
CREATE (n:N0 {p0:1});

MATCH (n:N0)
WHERE NOT (any(v IN [] WHERE n.p0 = v))
RETURN *;
```

**Expected Behavior**
- I think the `any()` function should return FALSE when applied to an empty list.
- Therefore, `NOT any(...)` should evaluate to TRUE, and the query should return one node.

**Actual Behavior**

The query returns no results.

**Additional Information**

When executing `RETURN any(v IN [] WHERE true);`, the result is NULL instead of FALSE. However, in Neo4j, the result is FALSE.

**Comment by Ignition** [comment]
Simplified test case `WITH any(v IN [] WHERE true) AS res RETURN res IS NOT null, res = false;`
