### ISSUE TITLE
apoc.date.convertFormat is not yet supported

### ISSUE THREAD

**Issue by jroith** [memgraph/memgraph#2506]
**Memgraph version**
2.19.0

The "apoc.date.convertFormat" does not appear to be supported or mapped in memgraph. This function is widely used in the GraphQL library and supporting it is as important as supporting validatePredicate to be compatible.

**Comment by matea16** [comment]
Hi @jroith, thank you for reporting this. We had previous requests for this procedure and it's all listed in the issue https://github.com/memgraph/memgraph/issues/1007. I'll add the +1 for this procedure to that issue and close this one for a better overview.
Is this a blocker for you?

**Comment by jroith** [comment]
@matea16 Thank you. Yes, this is a blocker for us.

**Comment by gitbuda** [comment]
Since we are actively working on the GraphQL support, I guess we can easily cover this soon CC @colinbarry & @DavIvek
