### ISSUE TITLE
create enum error

### ISSUE THREAD

**Issue by LPeng111** [memgraph/memgraph#2516]
**Memgraph version**
Which version did you use?
2.14.1

**Describe the bug**
When I use the cypher(CREATE ENUM BidType VALUES { win, invite };) to create ENUM, the error occured as follow.
![image](https://github.com/user-attachments/assets/a50ac9e2-3b72-4d03-bfa8-c8c7a6152567)

**Expected behavior**

Please tell me what caused this problem and how to solve it

**Comment by gitbuda** [comment]
A quick run of the same query worked under v2.21.0. SS is attached below. **Could you upgrade to the latest version? 🙏  The latest version is v2.22.0 😃** 
<img width="1685" alt="Screenshot 2024-12-01 at 11 26 47 AM" src="https://github.com/user-attachments/assets/d0affd64-7e3a-4726-a3d4-62f38064fcbd">
<img width="1683" alt="Screenshot 2024-12-01 at 11 27 14 AM" src="https://github.com/user-attachments/assets/0b403746-2310-47c8-84bc-c3762b8ef576">

**Comment by LPeng111** [comment]
OK, I'll upgrade it. Thanks.
