### ISSUE TITLE
Import CSV files from remote locations

### ISSUE THREAD

**Issue by g-despot** [memgraph/memgraph#290]
## Description

It would be cool to import CSV files with the LOAD CSV clause from remote locations.

## Feature usage

```
LOAD CSV FROM "https://github.com/memgraph/..." NO HEADER AS row
...
```

**Comment by g-despot** [comment]
To add some more context. 
When creating simple examples of how to use Memgraph (in Docker), it's very problematic to import data. 
You need to copy files to a running Docker container which isn't an easy task for inexperienced users.
This feature is would make our lives a lot easier.

**Comment by antonio2368** [comment]
I agree that this is something that could be useful for a bunch of use cases but this has some security issues which we would need to discuss first. That's the reason why we didn't add it immediately. 
It's definitely something we would like to add soon, so I'll keep you updated when we have new info for this. :smile:

**Comment by gitbuda** [comment]
@Josipmrden this might be interesting for you 😄

**Comment by katarinasupe** [comment]
Related to #849.

**Comment by gitbuda** [comment]
Done in https://github.com/memgraph/memgraph/pull/1027
