### ISSUE TITLE
Comparison for temporal types is not implemented

### ISSUE THREAD

**Issue by g-despot** [memgraph/memgraph#297]
**Memgraph version**
Memgraph 2.0.0

**Environment**
Memgraph Mage Docker image

**Describe the bug**
Query results cannot be ordered using properties with temporal types.

**Logs**
```
[2021-11-14 18:40:21.416] [memgraph_log] [critical] Unhandled comparison for types
```

**Comment by antonio2368** [comment]
Thanks for creating the issue!
Somehow we managed to miss this but the fix shouldn't be a problem so you can expect this to be solved in the following weeks.
