### ISSUE TITLE
[BUG] MERGE clause allows creating relationships without specifying the direction

### ISSUE THREAD

**Issue by g-despot** [memgraph/memgraph#359]
When executing the query `CREATE (p:Person)-[s:SPEAKS]-(l:Language) RETURN p, s, l;`, you get the following error:
```
Error: Query failed: Bidirectional relationship are not supported when creating an edge
```

If you use `MERGE` instead of `CREATE`, the relationship is created:

```
MERGE (p:Person)-[s:SPEAKS]-(l:Language) RETURN p, s, l;
```

**Comment by kostasrim** [comment]
I confirm this is actually a bug according to the opencypher spec page 119, I quote: 

> Merge on an undirected relationship
> MERGE can also be used with an undirected relationship. When it needs to create a new one, it will pick a direction.
> Query
```
MATCH (charlie:Person {name: 'Charlie Sheen'}), (oliver:Person {name: 'Oliver Stone'}) 
MERGE (charlie)-[r:KNOWS]-(oliver)
RETURN r
```
> As 'Charlie Sheen' and 'Oliver Stone' do not know each other, this MERGE query will create a KNOWS relationship between them. The direction of the created relationship is arbitrary.
```
Result
+-------------+
|r | 
| :KNOWS[8]{} |
1 row
Relationships created: 1
```

**Comment by sinisa-susnjar** [comment]
> When executing the query `CREATE (p:Person)-[s:SPEAKS]-(l:Language) RETURN p, s, l;`, you get the following error:
> 
> ```
> Error: Query failed: Bidirectional relationship are not supported when creating an edge
> ```
> 
> If you use `MERGE` instead of `CREATE`, the relationship is created:
> 
> ```
> MERGE (p:Person)-[s:SPEAKS]-(l:Language) RETURN p, s, l;
> ```

I ran those same queries in Neo4j and they produce the same results as memgraph does - CREATE fails, MERGE succeeds. The cypher spec also says (like Kostas mentioned above) that in case of MERGE, a direction is picked even if none was specified.
To quote the spec: "A property graph may be defined in graph theoretical terms as a **_directed_**, vertex-labeled, edge-labeled multigraph with selfedges, where edges have their own identity." - so, from this point it makes sense that CREATE behaves like it does.
