### ISSUE TITLE
Add support for dropping all indexes with one command

### ISSUE THREAD

**Issue by kgolubic** [memgraph/memgraph#365]
At the moment Memgraph doesn't support something like `DROP INDEX ON *` that would delete all indexes.

If you have a larger number of indexes it can take some time to delete them one by one. Dropping them all with a single command would be much faster.

Can this be added to Memgraph?

**Comment by alex-linx** [comment]
+1. I am experimenting with using gqlalchemy to import a bunch of sql tables, and it creates a lot of indexes, if I want to change some configuration, I need to manually go and delete all the old indexes.

**Comment by as51340** [comment]
@katarinasupe yes

**Comment by katarinasupe** [comment]
Schema.assert can be used to drop all indexes, but it won't work until https://github.com/memgraph/memgraph/issues/1463 is fixed.

**Comment by DavIvek** [comment]
Closed with #1485 .

**Comment by gcleaves** [comment]
But how is it actually done, it's not explained anywhere. How do I delete all indexes and constraints?

**Comment by DavIvek** [comment]
Hi @gcleaves !
Yes, this should work for deleting all indexes and constraints, are you experiencing any problems? I agree that this use case could be added to the documentation.
I'll open an issue for it on memgraph's docs repository.

**Comment by gcleaves** [comment]
No problems, it just took me a while to figure out the syntax. Thanks!
