### ISSUE TITLE
[BUG] Replica in SYNC WITH TIMEOUT returns 0 for TIMEOUT

### ISSUE THREAD

**Issue by vpavicic** [memgraph/memgraph#374]
**Memgraph version**
Memgraph 2.2.1

**Environment**
Windows 10, Memgraph Lab, with Docker using memgraph-platform image

**Describe the bug**
When registering a REPLICA instance with the SYNC WITH TIMEOUT mode, then showing REPLICA instances' details, the TIMEOUT for that instance is 0.

**To Reproduce**
1. Run two instances, demote one to REPLICA
2. Register replica with the following query `REGISTER REPLICA REP2 SYNC WITH TIMEOUT 1 TO "172.17.0.4";`
3. Run the following query to get details `SHOW REPLICAS;`
4. Observe how the TIMEOUT for REP2 is 0

**Expected behavior**
Not sure if this column shows TRUE/FALSE, or s/ms of the TIMEOUT, but 0 is a wrong answer in both cases

**Comment by gitbuda** [comment]
Done in #376
