### ISSUE TITLE
[BUG] Wrong column name in SHOW REPLICATION ROLE results

### ISSUE THREAD

**Issue by vpavicic** [memgraph/memgraph#375]
**Memgraph version**
Memgraph 2.2.1

**Environment**
Windows 10, Memgraph Lab, with Docker using memgraph-platform image

**Describe the bug**
Wrong column name as a result of the `SHOW REPLICATION ROLE ` query.

**To Reproduce**
1. Run the `SHOW REPLICATION ROLE ` query.
2. Result column says "replication mode" and is showing replication role

**Expected behavior**
Column name should be "replication role"

**Comment by gitbuda** [comment]
Done in #376
