### ISSUE TITLE
Add configuration settings Cypher query

### ISSUE THREAD

**Issue by katarinasupe** [memgraph/memgraph#445]
It would be useful if there is a configuration settings Cypher query. For example, let's say I set `--log-level=TRACE` and I want to check whether the flag is set correctly. It would be useful to run something like:

`SHOW CONFIGS;`

and get the list of all configuration settings and their values. Above is just a suggestion on what that query would look like (`SHOW STREAMS;` was my inspiration). Personally, I see this being especially useful for `--query-modules-directory`, `--kafka-bootstrap-servers` and `--log-level` config settings. 

This query can, later on, be wrapped with GQLAlchemy and serve to check whether all config settings are correctly set in a whole application.

**Comment by gitbuda** [comment]
Closing this in favor of #397
