### ISSUE TITLE
Implement graph projection

### ISSUE THREAD

**Issue by gitbuda** [memgraph/memgraph#447]

**Comment by antoniofilipovic** [comment]
With graph projection, we will add two features, which are slightly different, but with both user will be able to operate on subgraph:
- `project(<path>)` - aggregator which will aggregate paths that will YIELD graph 
   example:
    ```
    MATCH p=(n1:Node1)-[:Relationship]->(n2:Node2)
   WITH project(p) AS graph
   CALL proc.procedure(graph)
   YIELD *;
   ```
- `project_transitive(<path>, <NEW_EDGE_TYPE>, {new_property: edge_1.weight + edge_2.weight})` → start and end nodes could be connected, but still needs to be specified

    _example_:
    ```
    MATCH path=(a)-[e1]→(b)-[e2]→(c) 
    WITH project_transitive(path, 'EDGE_TYPE', {prop: e1.weight + e2.weight}) AS graph  
    ```
In the next few days, we will update with more defined feature specs.

**Comment by gitbuda** [comment]
@antoniofilipovic I think we should create another Issue for `project_transitive` and close this one?

**Comment by antoniofilipovic** [comment]
Yes, we should close this one and create a `project_transitive` one. Will take care of it.
