### ISSUE TITLE
Not executable query with two boolean values

### ISSUE THREAD

**Issue by stefanak-michal** [memgraph/memgraph#470]
**Memgraph version**
2.3.1

**Environment**
Windows, Docker

**Describe the bug**
If you run query `RETURN true, false;` you get error `Client received exception: Multiple results with the same name 'true' are not allowed.`.

**To Reproduce**
1. Run the following query 'RETURN true, false;'

**Expected behavior**
I expect to get result with two values `true` and `false`.

**Comment by gitbuda** [comment]
The fix proposed in #502 only applies to this specific case. To solve the problem in general, some additional alias logic is required. It's possible to solve a problem by manually giving aliases to the expressions that boil down to the same stripped value, e.g.:
```
RETURN 1+2, 3+4;           // fails because that's replaced during the query stripping with 0+0, 0+0
RETURN 1+2 AS x, 3+4 AS y; // OK
```
