### ISSUE TITLE
Fix the toolchain activate script to NOT depend on /opt path

### ISSUE THREAD

**Issue by gitbuda** [memgraph/memgraph#558]
On [lima-vm](https://github.com/lima-vm/lima), the writeable path is under `/tmp/lima`; if the toolchain is unpacked under that directory, activate script doesn't work. -> Detect the correct directory inside the activate script and put that on all required paths.

**Comment by hal-eisen-MG** [comment]
Is this still relevant?

**Comment by gitbuda** [comment]
I think this problem is still there.

**Comment by MarkoBarisic** [comment]
Moved it over to https://github.com/memgraph/infra/issues/296
