### ISSUE TITLE
Move to the toolchain-v5

### ISSUE THREAD

**Issue by gitbuda** [memgraph/memgraph#565]
- [ ] Add LLVM standard `libc++`
- [ ] Upgrade to Clang 14 and GCC 12
- [ ] Upgrade all toolchain libs to the latest versions (`fmt` v9 is required to compile Memgraph with GCC)
- [ ] Cover #558

**Comment by hal-eisen-MG** [comment]
Can we close this now?

**Comment by gitbuda** [comment]
Yes
