### ISSUE TITLE
[BUG] Assigning LBA privileges to Role crashes Memgraph

### ISSUE THREAD

**Issue by BorisTasevski** [memgraph/memgraph#576]
**Memgraph version**
2.4

**Environment**
Ubuntu 20.04

**Describe the bug**
Assigning LBA privileges to Roles crashes Memgraph.

**To Reproduce**
`Create Role r1;
Grant Read on Labels :Label1 to r1`

**Expected behavior**
Memgraph not crashing

**Comment by gitbuda** [comment]
@BorisTasevski and @brunos252 I think we can close this PR?
