### ISSUE TITLE
[BUG] Open cypher specification violation when using aggregations with other variables

### ISSUE THREAD

**Issue by ddaa2000** [memgraph/memgraph#619]
**Memgraph version**
Which version did you use?
Memgraph2.4.0 Docker

**Environment**
Some information about the environment you are using Memgraph on: operating
system, how do you connect, with or without docker, which driver etc.
Memgraph docker image on Ubuntu20.04, Neo4j java driver 4.1.1

**Describe the bug**
Executing the following query in an empty database:
```
MATCH (n) RETURN max('a') as a, n
```
According to the open-cypher specification, the RETURN statement should consider n as a key to divide the input into buckets and the use the aggregation function on each bucket. So this query should return 0 lines of result as the database is empty. However, memgraph return 1 single result.

**To Reproduce**
Executing the following query in an empty database:
```
MATCH (n) RETURN max('a') as a, n
```

**Expected behavior**
The database return 0 lines of result.

**Logs**
If applicable, add logs of Memgraph, CLI output or screenshots to help explain
your problem.

**Additional context**

**Comment by antaljanosbenjamin** [comment]
This is probably introduced by #448.

**Comment by DavIvek** [comment]
It looks to me like this issue doesn't exist anymore. Running this query with the latest version of memgraph, I got the empty result, exactly as expected.
