### ISSUE TITLE
Question,does memgraphdb only work with docker?

### ISSUE THREAD

**Issue by RESDXChgfore9hing** [memgraph/memgraph#623]
just curious why is it.
Is it possible to run query through cli interface with memgraphlab?
Because I wanted build a database for my personal usage and ideally it should not need fancy gui for low memory consumption.

**Comment by katarinasupe** [comment]
Hi @RESDXChgfore9hing 😄 You can execute Cypher queries against Memgraph by using Memgraph's command-line tool, [mgconsole](https://memgraph.com/docs/memgraph/connect-to-memgraph/mgconsole). At the docs, you have several instructions on how to use it, depending on the operating system. You don't have to necessarily use Memgraph with Docker. [Here](https://memgraph.com/docs/memgraph/installation) are all of the possible ways of installation. Also, here is quick access to the download hub. Please [join our Discord server](https://discord.gg/memgraph) for easier and quicker communication 😄 Glad to have you here!

**Comment by RESDXChgfore9hing** [comment]
huge thanks.
ahhh memgraphdb is not natively build in windows so only docker or wsl is available.hm....
nevermind will try install in my unix system in the future.
