### ISSUE TITLE
[BUG] MemGraph+neo4j-go-driver is stuck if cypher contains any path and does not have RETURN

### ISSUE THREAD

**Issue by inv2004** [memgraph/memgraph#650]
**Memgraph version**
2.4.1 (mage)

**Environment**
docker on WSL2

**Describe the bug**
memgraph+neo4j-go-driver is stuck on `sess.Close` or `res.Consume` if cypher contains any path and does not have RETURN. neo4j works ok

**To Reproduce**
```go
package main

import (
	"context"
	"fmt"
	"time"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
)

const url = "bolt://localhost:7687"

func query(driver neo4j.DriverWithContext, cypher string) error {
	ctx := context.Background()
	ctx, cancel := context.WithTimeout(ctx, 2*time.Second)
	defer cancel()
	sess := driver.NewSession(ctx, neo4j.SessionConfig{})
	defer sess.Close(ctx) // stuck here is no res.Consume

	res, err := sess.Run(ctx, cypher, nil)
	if err != nil {
		return err
	}

	for res.Next(ctx) {
		fmt.Println(res.Record().Values...)
	}

	err = res.Err()
	if err != nil {
		return err
	}

	if res.IsOpen() {
		fmt.Println("trying to consume")
		_, err := res.Consume(ctx)
		if err != nil {
			return err
		}
		fmt.Println("ok")
	}

	return nil
}

func example() error {
	driver, err := neo4j.NewDriverWithContext(url, neo4j.BasicAuth("", "", ""))
	if err != nil {
		return err
	}

	if err := query(driver, "RETURN 1+1"); err != nil {
		return err
	}
	if err := query(driver, "MATCH ()-[r]->() SET r.test = 123 RETURN DISTINCT 1"); err != nil {
		fmt.Println(err)
	}
	if err := query(driver, "MATCH ()-[r]->() SET r.test = 123"); err != nil {
		fmt.Println(err)
	}
	if err := query(driver, "MATCH (r)-[]->() SET r.test = 123"); err != nil {
		fmt.Println(err)
	}

	return nil
}

func main() {
	if err := example(); err != nil {
		panic(err)
	}
}
```
**Expected behavior**
No timeout errors

**Logs**
```
2
1
trying to consume
ConnectivityError: Timeout while reading from connection [server-side timeout hint: -1ns, user-provided context deadline: 2022-11-15 16:09:01.720096798 +0300 MSK m=+2.011375250]: context deadline exceeded
trying to consume
ConnectivityError: Timeout while reading from connection [server-side timeout hint: -1ns, user-provided context deadline: 2022-11-15 16:09:03.722075187 +0300 MSK m=+4.013353634]: context deadline exceeded
```

**Comment by gitbuda** [comment]
@inv2004 thanks for reporting, we'll take a look at what is happening 😄

**Comment by as51340** [comment]
Hi @inv2004 I wasn't able to reproduce the error, at my local environment it doesn't hang, can you maybe include more details like the content you filled database with?

**Comment by inv2004** [comment]
@as51340 I can confirm that I cannot reproduce with empty neo4j or simple relations. Let me think how to reproduce with out data

**Comment by inv2004** [comment]
@as51340 Please find json file attached:
[3.json.gz](https://github.com/memgraph/memgraph/files/10031221/3.json.gz)

```sh
 CALL import_util.json('3.json');
```

**Comment by as51340** [comment]
@inv2004 when the database is filled, I am able to reproduce the error. The error occurs after trying to consume the stream of results, here: 
```go
_, err := res.Consume(ctx)
if err != nil {
  return err
}
```
and it happens because private field `summary` from `result_with_context` struct isn't set to nil. You can check here for more details: `https://github.com/neo4j/neo4j-go-driver/blob/5.0/neo4j/result_with_context.go`
Unfortunately, at the moment, the only advice I can give you is to use some kind of return statement in each query and then you don't need to consume stream so you can delete this part of the code:
```go
if res.IsOpen() {
  fmt.Println("trying to consume")
  _, err := res.Consume(ctx)
  if err != nil {
    return err
  }
  fmt.Println("ok")
}
```
because even if the `res.isOpen()` is true, stream consumation will not succeed and logically, the stream should have already been consumed when looping over the `res.Next`. We don't know if the issue comes from the Bolt implementation part or driver's side, my best guess it is some weird combination of both but we will get back to you when we find out. 

Btw. there are also other methods, e.g `Collect` but it seems that they all rely on the same underling mechanism and the issue persists with them too.

**Comment by inv2004** [comment]
@as51340 Thank you for investigation,

About the `if res.IsOpen() {` branch - I can delete it, but the code appeared by the reason: because if it does not exists - then the code stucks anyway, but on `defer sess.Close()`

**Comment by inv2004** [comment]
To reproduce it you can change the function the way:
```go
func query(driver neo4j.DriverWithContext, cypher string) error {
	ctx := context.Background()
	// ctx, cancel := context.WithTimeout(ctx, 2*time.Second)
	// defer cancel()
	sess := driver.NewSession(ctx, neo4j.SessionConfig{})
	defer sess.Close(ctx) // stuck here is no res.Consume

	res, err := sess.Run(ctx, cypher, nil)
	if err != nil {
		return err
	}

	for res.Next(ctx) {
		fmt.Println(res.Record().Values...)
	}

	err = res.Err()
	if err != nil {
		return err
	}

	// if res.IsOpen() {
	// 	fmt.Println("trying to consume")
	// 	_, err := res.Consume(ctx)
	// 	if err != nil {
	// 		return err
	// 	}
	// 	fmt.Println("ok")
	// }

	return nil
}
```

**Comment by as51340** [comment]
@inv2004 yes but in order to remove `if res.IsOpen()` branch you have to add `return` statement in the query. So the code that works for me locally is:
```go
package main

import (
	"context"
	"fmt"
	"time"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
)

const url = "bolt://localhost:7687"

func query(driver neo4j.DriverWithContext, cypher string) error {
	ctx := context.Background()
	ctx, cancel := context.WithTimeout(ctx, 2*time.Second)
	defer cancel()
	fmt.Println("Created new context with timeout...")
	sess := driver.NewSession(ctx, neo4j.SessionConfig{})
	defer sess.Close(ctx) // stuck here is no res.Consume
	fmt.Println("Created new session with SessionConfig")

	res, err := sess.Run(ctx, cypher, nil)
	if err != nil {
		fmt.Println("Error with Run query execution...")
		return err
	}
	
	for res.Next(ctx) {
		fmt.Printf("Results from the query execution %v\n", res.Record().Values...)
	}

	err = res.Err()
	if err != nil {
		return err
	}

	return nil
}

func example() error {
	driver, err := neo4j.NewDriverWithContext(url, neo4j.BasicAuth("", "", ""))
	if err != nil {
		fmt.Println("Error occurred when trying to connect to Memgraph...")
		return err
	}
	
	if err := query(driver, "RETURN 1+1"); err != nil {
		return err
	}

	if err := query(driver, "MATCH ()-[r]->() SET r.test = 123 RETURN DISTINCT 1"); err != nil {
		fmt.Println(err)
	}

	if err := query(driver, "MATCH ()-[r]->() SET r.test = 123 RETURN DISTINCT 1"); err != nil {
		fmt.Println(err)
	}

	if err := query(driver, "MATCH (r)-[]->() SET r.test = 124 RETURN DISTINCT 1"); err != nil {
		fmt.Println(err)
	}

	return nil
}

func main() {
	fmt.Println("Starting program...")
	if err := example(); err != nil {
		fmt.Println("Error after returning from the execution...")
		panic(err)
	}
}
```
Can you confirm that it is working for you too? 
I realize this is not a complete fix, we are moving onto solving this and will get back to you in the next few days(tomorrow is holiday in Croatia so may be a bit slower :/).

**Comment by inv2004** [comment]
@as51340 
Thank you, I see that you added `RETURN` into 3,4 queries - that is why it works, but if you remove them

and then change defer to handle Close error, because before error from Close was discarded:
```go
	defer func() {
		err := sess.Close(ctx)
		if err != nil {
			fmt.Println(err)
		}
	}()
```

you will find that the sess.Close() hangs for the same reason

> holiday in Croatia

Please enjoy the weekend, and no rush - the issue is not critical at the moment.
