### ISSUE TITLE
[BUG] Nested FOREACH doesn't carry list of nodes correctly

### ISSUE THREAD

**Issue by jhb** [memgraph/memgraph#691]
**Memgraph version**
2.4.2

**Environment**
Complete docker image running in WSL2 under Windows 10. Using memgraph lab for cypher input

**Describe the bug**

Nested FOREACHS don't carry list of nodes correctly, it seems to be they are somehow converted to property maps

**To Reproduce**

```
match (n) detach delete n;
foreach (i in range(0,100)| create (n:NODE {i: i}));
match (n)
with n
order by n.id
with collect(n) as n_
FOREACH (i in range(0, size(n_) - 2) |
 FOREACH (node1 in [n_[i]] |
  FOREACH (node2 in [n_[i+1]] |
    FOREACH (j in [1] |
     MERGE (node1)-[:foo]->(node2)))));
match p=(n)-[r]->(m) return p
```

What I try to do is tdescribed here: https://neo4j.com/developer/kb/creating-and-working-with-linked-lists/#_linking_nodes_without_apoc

What happens instead is that two fresh nodes are created. If the most inner foreach is removed, node2 is treated as a known node, and fresh nodes are created for all node1. So it seems to me that the variables from the outer loop are not correctly carried over to the inner loop.

**Comment by Josipmrden** [comment]
Hello, thanks for the issue!

This is an interesting bug, I modified the query just a little bit like:

```
MATCH (n)
WITH n
ORDER BY n.i
WITH collect(n) as n_
FOREACH (i IN range(0, size(n_) - 2) | FOREACH (node1 IN [n_[i]] | FOREACH (node2 IN [n_[i+1]] | FOREACH (j IN [1] | SET node1.pair = node2.i))));

MATCH (n) RETURN n.i, n.pair;
```
and got okay matching of pairs, but for some reason the MERGE does not work.
We will investigate this.

**Comment by Josipmrden** [comment]
```
MATCH (n)
WITH n
ORDER BY n.i
WITH collect(n) as n_
FOREACH (i IN range(0, size(n_) - 2) | FOREACH (node1 IN [n_[i]] | FOREACH (node2 IN [n_[i+1]] | FOREACH (j IN [1] | CREATE (node1)-[:foo]->(node2)))));
```

If I actually do create instead of merge, it actually creates as much nodes as there are counts in the loop.
So probably mapping and keeping track with the nodes is the problem only in `MERGE` clause

**Comment by jhb** [comment]
The idea is however, that no new nodes are created at all, but the existing ones a linked up, even when doing a create - only relationships should be created.

**Comment by jhb** [comment]
Just as a workaround, I created my first real python query module. I am amazed that this is possible:

```
import mgp
import typing

@mgp.write_proc
def chain_nodes(
  context: mgp.ProcCtx,
  nodes: mgp.List[mgp.Vertex],
  reltype: str,
  properties: mgp.Nullable[mgp.Map]
) -> mgp.Record(path=mgp.Path):
  
  if len(nodes)<2:
    raise mgp.InvalidArgumentError('nodes must contains at least 2 nodes')
    
  path = mgp.Path(nodes[0])

  for i in range(len(nodes)-1):
    n1 = nodes[i]
    n2 = nodes[i+1]
    edge = context.graph.create_edge(n1, n2, mgp.EdgeType(reltype))
    for k,v in properties.items():
      edge.properties.set(k,v)
    path.expand(edge)

  return mgp.Record(path=path)
```

can be called as

```
match (n) detach delete n;
foreach (i in range(0,100)| create (n:NODE {i: i}));
match (n)
with n
order by n.id
with collect(n) as n_
call jhb.chain_nodes(n_,'chained',{foo: 'bar'}) yield path
```

**Comment by Josipmrden** [comment]
Assigned @brunos252  and @as51340  for the task
