### ISSUE TITLE
[BUG] mgp.py Graph.create_edge returns Edge, but python typing and documentation say otherwise

### ISSUE THREAD

**Issue by jhb** [memgraph/memgraph#692]
**Memgraph version**
2.4.2

**Environment**
memgraph-platform docker image on wsl2

**Describe the bug**
The python typing and its documentation say that Graph.create_edge would return None, while in reality it returns the created edge, as it should.

I guess fixing the return type will fix the documentation

**To Reproduce**
- https://github.com/memgraph/memgraph/blob/master/include/mgp.py#L1286
- https://github.com/memgraph/memgraph/blob/master/include/mgp.py#L1305
- https://memgraph.com/docs/memgraph/reference-guide/query-modules/api/python-api#create_edge

**Expected behavior**
The typing should document correctly that an edge is returned (which is good)

**Comment by katarinasupe** [comment]
Thank you, @jhb for opening the issue. @gitbuda I will assign myself to this 😄

**Comment by katarinasupe** [comment]
@antejavor will take over, he generated the latest version of docs for mgp.
