### ISSUE TITLE
Unable to create dynamic relations with FOREACH, CASE construct

### ISSUE THREAD

**Issue by cduret** [memgraph/memgraph#726]
**Memgraph version**
2.4.2

**Environment**
docker

**Describe the bug**
Unable to create relationship with foreach, case combo

**To Reproduce**

test_ent.csv :
```
id,label
0,foo
1,bar
```

```
LOAD CSV FROM "/path/to/test_ent.csv" WITH HEADER AS row
CREATE (n:Test {id: row.id, label: row.label});
```

test_rel.csv :
```
sourceId,type,destinationId
0,IS_A,1
1,HAS_SPECIMEN,0
```

```
LOAD CSV FROM "/path/to/test_rel.csv" WITH HEADER AS row
MATCH (n1:Test {id:row.sourceId})
MATCH (n2:Test {id:row.destinationId})
FOREACH(i IN (CASE WHEN row.type = "IS_A" THEN [1] ELSE [] END) |
CREATE (n1)-[r:IS_A]->(n2) );
```

**Expected behavior**
Expecting a relation IS_A created
```
match (n1:Test) -[r:IS_A]-> (n2:Test)
return n1, r, n2;
```

**Comment by Josipmrden** [comment]
Hello @cduret . With the CREATE (n1)-[r:IS_A]->(n2), what would you expect to happen?

Initial stage: 2 nodes are present in the database -> `(Test{id:0})` and `(Test{id:1})`

**Scenario A:**
there are 4 nodes and one relationship in the database `(Test{id:0}), (Test{id:1})` and `(Test{id:0})-[:IS_A]->(Test{id:1})`

**Scenario B:**
there are 2 nodes in the database + 1 relationship: `(Test{id:0})-[:IS_A]->(Test{id:1})`

**Comment by Josipmrden** [comment]
@brunos252  Linking this one with https://github.com/memgraph/memgraph/issues/691 since it seems like a similar issue.

**Comment by Josipmrden** [comment]
@brunos252 
For reference

```
MATCH (n1:Test {id:0}), (n2:Test {id:1})
FOREACH (i IN [1] | SET n1.prop = "prop", n2.prop = "prop");
```

works fine.


@cduret In your case, the `MERGE` keyword would be more appropriate (although it is still a bug and we'll need to handle it), since MERGE does actually do CREATE if not exists. CREATE by itself will always create a new node or a copy of the matched as a new node.

**Comment by brunos252** [comment]
Yes, this is the same issue as #691. The Foreach doesn't check the outer scope for symbols (variables), so it regards `n1` and `n2` as new variables and creates those nodes again. With the fix PR #725, this works fine and only 2 nodes and 1 relationship are in the database.

**Comment by brunos252** [comment]
@cduret in the meantime, you can also import your CSV files using our Python library GQLAlchemy. Here is a [how-to guide](https://memgraph.com/docs/gqlalchemy/how-to-guides/table-to-graph-importer).
The configuration file you would need to perform this import is:
`indices:
  test_ent:
  - id

name_mappings:
  test_ent:
    label: Test

many_to_many_relations:
  test_rel:
    foreign_key_from:
      column_name: id
      reference_table: test_ent
      reference_key: id
    foreign_key_to:
      column_name: id
      reference_table: test_ent
      reference_key: id
    label: IS_A`

**Comment by cduret** [comment]
Indeed what I expect is creating relation dynamically to existing nodes in database
In this case 2 nodes and 1 relation

Happy to hear that this is being fixed soon, I'll give a try on GQLAlchemy

thanks
