### ISSUE TITLE
[BUG] Access Denied in build toolchain for ARM64

### ISSUE THREAD

**Issue by anon767** [memgraph/memgraph#735]
Following link returns "Access Denied":
https://s3.eu-west-1.amazonaws.com/deps.memgraph.io/toolchain-v4/toolchain-v4-binaries-centos-9-arm64.tar.gz

Which is referenced in the build_env.dockerfile in the arm64 release folder.

**Comment by jbajic** [comment]
Sorry for the confusion when we started building for ARM we used CentOS 9 ARM instance, and then later on we switched to support ARM only on Debian 11. 
So this URL is deprecated, the one for Debian would be: https://s3-eu-west-1.amazonaws.com/deps.memgraph.io/toolchain-v4/toolchain-v4-binaries-debian-11-arm64.tar.gz
