### ISSUE TITLE
[QUESTION]: How to simulate neo's `NOT MATCH` ?

### ISSUE THREAD

**Issue by inv2004** [memgraph/memgraph#762]
**Describe the question**
How is it possible to simulate `NOT MATCH` cypher?

**To Reproduce**
```cypher
MATCH (n) DETACH DELETE n;

CREATE (a:A)-[r:R]->(b:B);
MATCH (a:A)-[r]->(b:B) CREATE (a)-[rr:RR]->(b);
CREATE (a:AA)-[r:R]->(b:BB);
MATCH (a:AA)-[r]->(b:BB) CREATE (a)-[rr:RR]->(b) CREATE (a)-[rrr:RRR]->(b);
// +--------------------------+
// | a      | r      | b      |
// +-------------------------+
// | (:A)   | [:R]   | (:B)   |
// | (:A)   | [:RR]  | (:B)   |
// | (:AA)  | [:R]   | (:BB)  |
// | (:AA)  | [:RR]  | (:BB)  |
// | (:AA)  | [:RRR] | (:BB)  |
// +--------------------------+

neo> MATCH (a)-[r:RR]->(b) WHERE NOT (a)-[:RRR]->(b) RETURN a,r,b;
// +---------------------+
// | a    | r     | b    |
// +---------------------+
// | (:A) | [:RR] | (:B) |
// +---------------------+

mg> MATCH (a)-[r:RR]->(b) OPTIONAL MATCH (a)-[rrr:RRR]->(b) WHERE rrr IS NULL RETURN a,r,b;
// looks like inner query could help here ^^^
// +-------+-------+-------+
// | a     | r     | b     |
// +-------+-------+-------+
// | (:A)  | [:RR] | (:B)  |
// | (:AA) | [:RR] | (:BB) |
//+-------+-------+-------+
```

**Expected behavior**
Ability to select without relation

**Comment by brunos252** [comment]
This should work:
```
MATCH (a) 
OPTIONAL MATCH (a)-[r:RRR]->(b)
WITH a, b
WHERE b IS NULL
MATCH (a)-[:RR]->(c)
RETURN a, c;
```
- first we retrieve all nodes (`MATCH (a)` isn't necessary if `a` has a specific label)
- optional match using the relationship we want to avoid, since optional match puts null where the match doesn't exist
- filter only those where `b` is null, meaning where there is no such relationship
- match those given nodes with the filter we want, which is `-[:RR]-`

**Comment by inv2004** [comment]
@brunos252 

Please find an example with both cases covered:
```cypher
MATCH (n) DETACH DELETE n;

CREATE (a:A)-[r:R]->(b:B);
MATCH (a:A)-[r]->(b:B) CREATE (a)-[rr:RR]->(b);
CREATE (a:AA)-[r:R]->(b:BB);
MATCH (a:AA)-[r]->(b:BB) CREATE (a)-[rr:RR]->(b) CREATE (a)-[rrr:RRR]->(b);
CREATE (a:AAA)-[r:R]->(b:BBB);
MATCH (a:AAA)-[r]->(b:BBB) CREATE (a)-[rr:RR]->(b) CREATE (a)-[rrr:RRR]->(c:CCC);

> MATCH (a)-[r:RR]->(b) WHERE NOT (a)-[:RRR]->(b) RETURN a,r,b;
// +-------------------------+
// | a      | r     | b      |
// +-------------------------+
// | (:A)   | [:RR] | (:B)   |
// | (:AAA) | [:RR] | (:BBB) |
// +-------------------------+

> MATCH (a) OPTIONAL MATCH (a)-[r:RRR]->(b) WITH a, b WHERE b IS NULL MATCH (a)-[:RR]->(c) RETURN a, c;
// +-------------+
// | a    | c    |
// +-------------+
// | (:A) | (:B) |
// +-------------+
```

**Comment by Josipmrden** [comment]
Hello @inv2004 , is this similar to where exists?
If yes, it is currently being addressed in the following PRs:
https://github.com/memgraph/memgraph/pull/767
https://github.com/memgraph/memgraph/pull/766
https://github.com/memgraph/memgraph/pull/765
https://github.com/memgraph/memgraph/pull/764

**Comment by inv2004** [comment]
@brunos252 @Josipmrden 
Thank you. Looks like the OPTIONAL MATCH with WITH simulates it pretty well

**Comment by jchvz** [comment]
@Josipmrden thanks for the links. Speaking to our specific use-case, yes, `WITH EXISTS` will cover it. But, we would like a workable solution in the meantime as well. It looks like we've now gotten one from @brunos252 (thanks!)
