### ISSUE TITLE
Polish C++ wrapper

### ISSUE THREAD

**Issue by gitbuda** [memgraph/memgraph#776]
Add support for results verification, the client does not return results back, and it is impossible to be certain that the read query was successfully executed. 

Add support for per-thread duration measurements, per thread workload definition. Meaning you can write to a specific thread and read from other threads. 

Add support for tracking throughput across execution time. 

Add support for serialisation error counts.

**Comment by antejavor** [comment]
This issue has been resolved. 

Has been pushed to future iterations on mgbench: 

- Add support for per-thread duration measurements, per thread workload definition. Meaning you can write to a specific thread and read from other threads.

- Add support for tracking throughput across execution time.

**Comment by antejavor** [comment]
The issue has been resolved. 

Features pushed for next iteration of mgBench: 

- Add support for per-thread duration measurements, per thread workload definition. Meaning you can write to a specific thread and read from other threads.

- Add support for tracking throughput across execution time.
