### ISSUE TITLE
Improve the epoch_id branching error message in Memgraph v2 replication

### ISSUE THREAD

**Issue by gitbuda** [memgraph/memgraph#782]
"Replica {}  cannot be used with this instance..." inside `replication_client.cpp`

**Comment by vpavicic** [comment]
Would this be acceptable? You cannot register REPLICA {} to this MAIN because at one point REPLICA {} acted as the MAIN instance. Both the MAIN and REPLICA {} now hold unique data. Please resolve data conflicts and start the replication on a clean instance.
