### ISSUE TITLE
Add DNS support for cluster replica address

### ISSUE THREAD

**Issue by RobertConanMcMillan** [memgraph/memgraph#815]
When running a cluster in Kubernetes we sometimes need to reorganize or restart memgraph replicas and/or mains, due to the nature of how networking works it's annoying / impossible to ensure the "respawned" instances have the same IP.

I would like that the memgraph main supported DNS look ups so that a replica could be registered as such:

```
REGISTER REPLICA replica-0 ASYNC TO "memgraph-replica-0.components";
```

This would allow us to move, recreate and scale replicas without having to un-register / register each time.

**Comment by antejavor** [comment]
We have a +1 on this issue. Users are experiencing the same issue with DNS resolution in Kubernetes.

**Comment by shashankkoppar** [comment]
Hi @antejavor , any update on this?

**Comment by antejavor** [comment]
Hi @shashankkoppar, this got a HIGH priority, and it will be handled in the upcoming weeks. I do not have an exact date, but there is a possibility for Memgraph 2.10 since 2.9 is coming out tomorrow.

**Comment by gitbuda** [comment]
@RobertConanMcMillan an improvement for this issue has been finally merged to master 💪
We'll make the new release in the next few days 😃 
Thanks!
