### ISSUE TITLE
[BUG] Incorrect timedelta object values for a Duration type in a query module

### ISSUE THREAD

**Issue by tonilastre** [memgraph/memgraph#822]
**Memgraph version**
Memgraph 2.5.1

**Environment**
Docker image: memgraph/memgraph-mage

**Describe the bug**
Property with a defined `duration` value initialized with a number of days (e.g. `P<number of days>D...`) shows incorrect information in the `mgp` query module context.

**To Reproduce**

1. Create the following query module (name = `duration_tester`):

```python
import mgp

@mgp.function
def parse_duration(ctx: mgp.FuncCtx, node: mgp.Vertex, prop_name: str):
  value = node.properties.get(prop_name)
  return f'str={str(value)} repr={repr(value)}'
```

2. Run the following Cypher command:

```
CREATE (n:Node { duration: duration("P2D") })
RETURN n, duration_tester.parse_duration(n, "duration")
```

3. Check the response

In the response, you can see that the information (duration of 2 days) is correct from the database response, but in the `mgp` context, the timedelta Python object shows incorrect information (16 minutes and 41 seconds).

![Screenshot 2023-03-08 at 14 24 03](https://user-images.githubusercontent.com/2602830/223725582-db0e7c11-884f-49ab-a794-5321e679b881.png)

**Expected behavior**
Python object (`timedelta`) that holds duration information should have a correct value when duration is initialized with a number of days. (e.g. `P2D` or `P3D`, `P2DT2M`). It works correctly when there are only time values in the duration (e.g. `PT2M`, `PT2M2S`, ...).

**Comment by DavIvek** [comment]
![Screenshot from 2023-12-18 14-24-51](https://github.com/memgraph/memgraph/assets/88043717/e35099aa-00b3-43ef-93c6-68def4f625ab)
It looks to me like this issue doesn't exist anymore. Running this query with the latest version of memgraph mage, I got the expected result.
