### ISSUE TITLE
Support for map projections 

### ISSUE THREAD

**Issue by vishal-android-freak** [memgraph/memgraph#841]
We are trying to shift from Neo4j to memgraph and our application needs support for map projections. Consider an example query:

```
UNWIND $create_param0 AS create_var4
CALL {
    WITH create_var4
    CREATE (create_this0:`Movie`)
    SET
        create_this0.title = create_var4.title
    WITH create_this0, create_var4
    CALL {
        WITH create_this0, create_var4
        UNWIND create_var4.actors.create AS create_var5
        WITH create_var5.node AS create_var6, create_var5.edge AS create_var7, create_this0
        CREATE (create_this8:`Actor`)
        SET
            create_this8.name = create_var6.name
        MERGE (create_this0)<-[create_this9:ACTED_IN]-(create_this8)
        
        RETURN collect(NULL) AS create_var10
    }
    
    RETURN create_this0
}
CALL {
    WITH create_this0
    MATCH (create_this0)<-[create_this1:ACTED_IN]-(create_this2:`Actor`)
    WITH create_this2 { .name } AS create_this2
    RETURN collect(create_this2) AS create_var3
}
RETURN collect(create_this0 { .title, actors: create_var3 }) AS data
```

Currently, in memgraph this query gives error on line `WITH create_this2 { .name } AS create_this2` because the map projection syntax `create_this2 { .name }` is not supported.

Also, changing this query is not possible as this is autogenerated from the graphql layer.

Do we have any plans for supporting this syntax?

**Comment by vishal-android-freak** [comment]
Sorry, this isn't a bug but I couldn't file an enhancement request!

**Comment by vishal-android-freak** [comment]
@Josipmrden have created this, just in case you guys pick this up in the next release cycle :)

**Comment by gitbuda** [comment]
Quick info @vishal-android-freak how critical is this for you, critical or nice to have? 🤔

**Comment by vishal-android-freak** [comment]
We are looking to port the Neo4j graphql layer to memgraph and this is super critical for it. Rather than writing everything from scratch we thought of porting what's already working great. Sub queries was a Missing part which I think has already been integrated. Next was map projections. Would be great if this lands as we use this internally for rest of the other queries as well apart from graphql :) @gitbuda

**Comment by gitbuda** [comment]
@vishal-android-freak great input, thanks! Not sure yet how much work this is going to be, but we'll expedite the details in the next few days 😄

**Comment by vishal-android-freak** [comment]
Thanks a ton:) Feel free to let me know if you need any help! @gitbuda @Josipmrden

**Comment by Josipmrden** [comment]
Hello @vishal-android-freak , the assignee for the feature will be @antepusic . I'll email you soon if you'd like to jump on a call on how best to tackle further advancements in this topic so we can integrate graphql not only for you, but hopefully make it easier for everyone to execute GraphQL on top of Memgraph :D

**Comment by vishal-android-freak** [comment]
@Josipmrden surely! Let's do this 💪

**Comment by clres** [comment]
I would also be very interested in this as map projections seem to be required for Memgraph compatibility with Spring Data for Neo4j
