### ISSUE TITLE
Make error messages more clear and up to point

### ISSUE THREAD

**Issue by kgolubic** [memgraph/memgraph#843]
In the line https://github.com/memgraph/memgraph/blob/029be10f1de2adaf1948040c5c7ada9b2722d7e3/src/query/frontend/ast/ast.hpp#LL1236C68-L1236C68 we have an error message that is shown if something is wrong. 

This message is always the same, regardless of the cause for the error `Function '{}' doesn't exist.` So If I write a query

```
MATCH (p:Person)
WHERE exists(p)
RETURN p.name
ORDER BY p.name;
```

I'll get an error message that says that function EXISTS doesn't exist.

![image](https://user-images.githubusercontent.com/46486712/228495265-ac0b7813-2885-4c40-81e3-22ba5257900a.png)

Is it possible to check input values and then check each argument and, based on that, return different error messages, e.g. `Argument {} is the wrong type`?

**Comment by vpavicic** [comment]
I think we can go about this in 2 ways for existing errors: 
1. when noticing something is wrong, opening an issue and try to do as much to fix that particular error and ... i don't know how to say this to sound intelligent... but kind of fix everything "around" this particular issue... so see what other errors can a function cause and check its copy, check other functions AND check where is "function X doesn't exist." error copy also used and check if it's correctly used... so kind of reacting to a reported issue and doing as much fixing in its perimeter 

2. systematically go through all error msgs

I'm kind of all up for the 1st approach, BCS its less tedious task and kind of focuses more on the frequent error msgs rather an error msgs someone gets once in 1000000 queries... this will mean that some error msgs might stay faulty forever. 

The 1st approach does require being mindful of the error messages, not ignoring them, checking if they truly make sense and reporting them

Also, in the future, we can make more of an effort to make them user-oriented and truly helpful -> sort of error QA done by someone outside the engineering team BCS when you have no idea what's going on, the errors are priceless (and the other way round, when you are too deep into a subject matter, you so much that you don't truly rely on the error msgs but the previous knowledge, the under the hood knowledge the user doesn't have)

**Comment by katarinasupe** [comment]
@vpavicic I agree with the 1st approach, and I think it only requires a few resources to at least report it. Maybe write a message on Slack to everyone to be more mindful of error messages and report on GitHub as soon as they think something does not make sense. 

For future releases, it would be good to know if new error messages are introduced and, if yes, that DX (probably @vpavicic) gets access to them and check them.

**Comment by katarinasupe** [comment]
I will close this issue with a note to everyone to report bad error messages when then notice them so we can improve them incrementally.
