### ISSUE TITLE
Unexpected Query failed

### ISSUE THREAD

**Issue by ljhhuxiaoba** [memgraph/memgraph#854]
I execute a query on my memgraph database and it fails.

memgraph version: 2.6.0
operating system: windows 10
API：Cypher version 9

query:MATCH (n0:L1),()-[r0:T1]->(),(n1:L3:L5:L0) WHERE (n0)-[r0]->(n1)  RETURN count(1) 

error message:Query failed: Not yet implemented: atom expression '(n0)-[r0]->(n1)'

My graph has only 5 nodes and 5 relationships,but the qyery seems timed out.
I don't know if this is a bug or if memgraph doesn't support patterns in WHERE.

**Comment by katarinasupe** [comment]
Hi @ljhhuxiaoba :) Can you try running:

`MATCH (n0:L1) WHERE exists((n0)-[:T1]->(:L3:L5:L0)) RETURN count(1);`

Does that work for you?
The syntax here is a bit different in Memgraph. Currently, we support [pattern expression filters](https://memgraph.com/docs/cypher-manual/clauses/where#17-filter-with-pattern-expressions) with the exists(pattern) function, which can perform filters based on neighboring entities.

**Comment by ljhhuxiaoba** [comment]
Does this mean that pattern predicates can not be used in the where clause?

**Comment by Josipmrden** [comment]
Yes, pattern predicates are currently not a feature of Memgraph. Pattern predicates are currently only supported inside the exists() function.

**Comment by ljhhuxiaoba** [comment]
Thanks a lot!

**Comment by hafiz031** [comment]
For reference these are [unsupported-constructs](https://memgraph.com/docs/querying/differences-in-cypher-implementations#unsupported-constructs).
