### ISSUE TITLE
[BUG] Inconsistent behavior on memgraph and Neo4j

### ISSUE THREAD

**Issue by ljhhuxiaoba** [memgraph/memgraph#855]
I execute a query on my neo4j database and memgraph database ,and an error occurred on memgraph.

Neo4j version: 5.5.0 Enterprise
memgraph version:2.6.0
operating system: windows 10
API：Cypher version 9

query:RETURN EXISTS { WITH 0 AS n0 MATCH ({n1:COUNT { RETURN 0 AS x } }) }

Neo4j: The query runs successfully and no exception is raised
Memgraph: The query fails with the error message:Query failed: line 1:15 mismatched input '{' expecting {<EOF>, ';'}

**Comment by ljhhuxiaoba** [comment]
I can't find a similar example in the Neo4j docs, but I think this query is syntactically correct, and it can run correctly on the neo4j database. I wonder if memgraph's Cypher syntax doesn't support this feature.

**Comment by katarinasupe** [comment]
@ljhhuxiaoba Memgraph does not support `EXISTS` and `COUNT` subquery. For now, the support for `CALL` subquery will be added in the next release this week. What you can do is try figuring out if it's possible to rewrite such a query differently.

**Comment by ljhhuxiaoba** [comment]
I see,thanks for your explanation!
