### ISSUE TITLE
Query failed: Unable to get MAX of 'string' and 'int'.

### ISSUE THREAD

**Issue by ljhhuxiaoba** [memgraph/memgraph#858]
I execute a query on my memgraph database and it fails.

memgraph version: 2.6.0
operating system: windows 10
API：Cypher version 9

query:UNWIND [1, 'a'] AS a RETURN max(a)

error message:Query failed: Unable to get MAX of 'string' and 'int'.

But according to Cypher standards the string 'a' is considered to be a lower value than numeric value 1 and 1 should be returned.

Looking forward to your reply.

**Comment by katarinasupe** [comment]
Hi @ljhhuxiaoba, as you can see in [Memgraph docs](https://memgraph.com/docs/cypher-manual/functions#aggregation-functions), currently, the max function has an integer or float argument. Can you explain in which case you would find this feature helpful? What is your use case?

**Comment by ljhhuxiaoba** [comment]
I can solve this problem in an alternative way, thank you very much.
