### ISSUE TITLE
Query failed about WITH * 

### ISSUE THREAD

**Issue by ljhhuxiaoba** [memgraph/memgraph#873]
I executed a query on my empty memgraph database and got an error.

memgraph version:2.7.0
operating system: windows 10
API：Cypher version 9
query:create () with * match () return 1
error message:Query failed: There are no variables in scope to use for '*'.

Expected behavior:
The query should run successfully and return 1.

Actual behavior:
The query failed.

**Comment by gitbuda** [comment]
Thanks for the finding! This is where Memgraph is different. My view is that this is a low priority at the moment because it can be easily mitigated by running `CREATE (n) WITH * MATCH (m) RETURN 1;` (haven't actually tested the query). Let me know if there is a deeper issue 😄

**Comment by katarinasupe** [comment]
@ljhhuxiaoba, the query @gitbuda provided does return 1. Is this good enough for you?
By the way, I see that you opened a couple of issues. If you have additional questions about Memgraph, feel free to[ join our Discord server](https://www.discord.gg/memgraph).

**Comment by ljhhuxiaoba** [comment]
Thanks a lot and the issue can be resolved.
