### ISSUE TITLE
Query failed: Connection was closed by server

### ISSUE THREAD

**Issue by ljhhuxiaoba** [memgraph/memgraph#874]
I executed a query on my memgraph database and the connection closed.

memgraph version:2.7.0
operating system: windows 10
API：Cypher version 9
query:SET (CASE WHEN true THEN null END).a = 1
error message:Query failed: Connection was closed by server

**Comment by gitbuda** [comment]
@ljhhuxiaoba This is a very nice finding! There is a segmentation fault on the Memgraph side. We'll try to include the fix in the next release.

**Comment by gitbuda** [comment]
take a look at the @Ignition comment inside #1175 and figure out the root cause to close this issue

**Comment by ljhhuxiaoba** [comment]
Hello, has this problem been fixed?

**Comment by gitbuda** [comment]
Hi! This particular issue has been fixed under https://github.com/memgraph/memgraph/pull/1175 but we suspect there are more cases like this, and we have to figure out a proper fix across the board 💪 We plan to start that work soon 😃
