### ISSUE TITLE
[BUG] HEX overflow in GSS blue component function

### ISSUE THREAD

**Issue by GER-Jani** [memgraph/memgraph#875]
**Memgraph version**
Lab version 2.5.0

**Environment**
Docker (running on Windows 10)

**Describe the bug**
HEX overflow in GSS [blue component](https://memgraph.com/docs/memgraph-lab/style-script/gss-functions#bluecolor) function.

**To Reproduce**
1. Open Memgraph Lab -> Query Execution -> Graph Style Editor
2. `Define(get_component, Function(r, Blue(mediumseagreen)))` ('mediumseagreen' is the example from the [documentation](https://memgraph.com/docs/memgraph-lab/style-script/gss-functions#bluecolor))
3. Print the output somewhere e.g. `label: Format("Component: {}", get_component(edge))`
4. It outputs **"Component: 1"** instead of **"Component: 113"**

**Expected behavior**
Example from the [documentation](https://memgraph.com/docs/memgraph-lab/style-script/gss-functions#bluecolor):
Expected output: **113**

**Additional context**
You can easily test this by defining
`Define(get_component, Function(r, Blue(RGB(0, 0, 255))))`
and play around with the blue component - it stucks between 0 and 15.
Setting it between 0 and 15, it works fine.
Setting it to 16, it returns 0.
Setting it to 17, it returns 1 and so on.
Getting the red component works fine (0 - 255), getting the green component works fine (0 - 255), only the blue component has an overflow.

**Comment by gitbuda** [comment]
Thanks for reporting!

**Comment by tonilastre** [comment]
@GER-Jani Thanks for the report! Great catch btw!

There was a bug in the `Blue` component! It is fixed and will be out in the new Lab release (v2.6.0) coming up in the next few days. I will keep this Issue open until the fix is released. Also, a fix for `Darker` and `Ligher` will be there too because it doesn't work as expected.

Btw from the task description, I am seeing that you are an experienced GSS (Graph Style Script) user. Are there any other functions that you find missing in the GSS or any other feedback around GSS?

**Comment by GER-Jani** [comment]
Thanks for verifying and fixing.

@tonilastre Yes, there are a few things that could come in handy.
I'm trying to implement a simple but dynamic two-colored heatmap based on a property of my edges. To do this, I need to normalize these values. But therefore, I need their extreme values in the Graph Style Editor. I see there are the functions `EdgeCount` and `NodeCount`, which can take the graph as a whole and perform calculations based on it. It would be helpful to somehow get these extrema or to be able to perform custom operations on the `graph` parameter. For a current concept design I’m manually defining the extrema hardcorded (e. g. `Define(min_edge_property_value, 14)`).
But I think it would be very useful to have a built-in heatmap function for analytic purposes in general that can generate an interpolation-based style design, given a specific node or edge property.

**Comment by tonilastre** [comment]
@GER-Jani with this new Lab release, these are the new GSS functions that are coming up: https://github.com/memgraph/docs/pull/821. Two functions that will be great for your use case is `Min` and `Max` because you can do that with the following GSS code:

```
Define(PROP_NAME, "property_name")

// This one will create an array of all values from edge property "property_name"
// For additional filtering, `Filter` can be used too (e.g. if some edges don't have that property)
Define(AllEdgeProps,
  Function(g,
    Map(
      Edges(g),
      Function(e, Property(e, PROP_NAME))
    )
  )
)

// Using new functions `Min` and `Max` to get the min and max values from an array of values
Define(MinEdgeProp, Function(g, Min(AllEdgeProps(g))))
Define(MaxEdgeProp, Function(g, Max(AllEdgeProps(g))))

// Normalize function to normalize value to [0, 1] (missing check for min == max and div by 0)
Define(NormEdgeProp,
  Function(g, e,
    Div(
      Sub(Property(e, PROP_NAME), MinEdgeProp(g)),
      Sub(MaxEdgeProp(g), MinEdgeProp(g))
    )
  )
)

// And the usage of it
@EdgeStyle {
  width: NormEdgeProp(graph, edge)
}
```

Btw, you can call `Edges` on the `graph` variable and get all the edges from the graph view.

> But I think it would be very useful to have a built-in heatmap function for analytic purposes in general that can generate an interpolation-based style design, given a specific node or edge property.

This is great feedback and it could be really useful. We added this as a feature request, we just need to see how to make it so it can be used along with other defined built-in functions. Thanks!

**Comment by GER-Jani** [comment]
@tonilastre Nice, thank you! That would be a great add. Much more elegant and simplifies my current implementation a lot!

**Comment by tonilastre** [comment]
Hi @GER-Jani,

Just want to let you know that the new Lab (included in the latest image of `memgraph-platform` too) has all the functions that will be useful for you regarding the heatmap (`Min`, `Max`, `Reduce`, `Sum`) + the fix for the `Blue` color. You can check the CHANGELOG [here](https://memgraph.com/docs/memgraph-lab/changelog#lab-v260---apr-20-2023).

The heatmap function will be added in some future releases as we need to see how to cover most of the cases for the heatmap that will work with the current GSS functions. If you wanna be updated according to this or included in the feature specs, you can always join our Discord where we discuss current and upcoming features. [Discord link here](https://discord.gg/memgraph).

Btw, I would like to see what the finished heatmap looks like on your graph because it is probably the best usage of GSS so far. Would you mind sharing a screenshot?
Feel free to remove the labels from nodes and edges if you don't want to share the names/titles from the dataset (with GSS you can do that with `@NodeStyle { label: "" } @EdgeStyle { label: "" }` at the end of the GSS content).

**Comment by GER-Jani** [comment]
Hi @tonilastre, thanks fot the fix, now it works as expected.

Would it be possible to define global constants regarding graph-based extreme values (and normalizations), because currently all calculations are processed repeatedly per edges?

For example:

- Using the dynamic approach finding the extrema (min. and max.) on executing a query, it takes about 10 seconds just to style the graph (216 nodes, 240 edges). Memgraph Lab **is not asking** me, if I want to switch to switch to data view btw. Executing the query is still fast (23 ms).

- When I hardcore both values and execute the same query, it just takes about 500 ms to style the graph.

I will leave my GSS code here, maybe there are some few other tricks to increase the performance.
<details><summary>GSS code</summary>

```

Define(follows_user_transition, Function(r, HasProperty(r, "user_ids")))
Define(get_all_follows_user_transition_sizes, Function(g, Map(Edges(g), Function(e, Size(Property(e, "user_ids"))))))
Define(min_num_user_ids, 1)
Define(max_num_user_ids, 1837)
Define(heatmap_cold, #0000FF)
Define(heatmap_hot, #FF0000)
Define(get_num_user_ids, Function(r, Size(Property(r, "user_ids"))))
Define(get_normalized_num_user_ids, Function(g, r, Div(Sub(get_num_user_ids(r), min_num_user_ids), Sub(max_num_user_ids, min_num_user_ids))))
Define(get_color, Function(g, r, RGB(
  Floor(Add(Mul(Sub(1, get_normalized_num_user_ids(g, r)), Red(heatmap_cold)), Mul(get_normalized_num_user_ids(g, r), Red(heatmap_hot)))),
  Floor(Add(Mul(Sub(1, get_normalized_num_user_ids(g, r)), Green(heatmap_cold)), Mul(get_normalized_num_user_ids(g, r), Green(heatmap_hot)))),
  Floor(Add(Mul(Sub(1, get_normalized_num_user_ids(g, r)), Blue(heatmap_cold)), Mul(get_normalized_num_user_ids(g, r), Blue(heatmap_hot))))
)))

@NodeStyle {
  size: 6
  color: #DD2222
  color-hover: Lighter(#DD2222)
  color-selected: Lighter(#DD2222)
  border-width: 0.6
  border-color: #1d1d1d
  font-size: 3
}

@NodeStyle HasLabel(node, "Training") {
  color: #7F7F7F
  color-hover: Lighter(#DD2222)
  color-selected: Lighter(#DD2222)
}

@EdgeStyle {
  color: #999999
  color-hover: #1d1d1d
  color-selected: #1d1d1d
  width: 0.3
  width-hover: 0.9
  width-selected: 0.9
  font-size: 3
}

@EdgeStyle follows_user_transition(edge) {
  color: get_color(graph, edge)
  color-hover: #1d1d1d
  color-selected: #1d1d1d
  width: Add(Mul(get_normalized_num_user_ids(graph, edge), 5), 1)
  width-hover: 0.9
  width-selected: 0.9
  font-size: 3
}

@ViewStyle.Map {
  tile-layer: "light"
}
```
</details>

The result:

216 nodes, 240 edges:
![heatmap_example0](https://user-images.githubusercontent.com/9035100/234316945-15125b3b-dd62-402d-98d2-8dcb18a09bce.png)

Here are some other examples using the hardcoded approach:

662 nodes, 1360 edges:
![heatmap_example1](https://user-images.githubusercontent.com/9035100/234316968-7c08ca26-c56f-42d3-b1ee-dee661a3a8d5.png)

1,378 nodes, 22,757 edges (complete graph):
![heatmap_example2](https://user-images.githubusercontent.com/9035100/234317004-f44a9ad5-74d3-4c5a-a64e-1a0231776a58.png)

**Comment by GER-Jani** [comment]
Since I'm playing around with even bigger data sets, it would be nice if GSS would support ARGB colors. Or is there a current solution to define a render ordering when you have multiple edge styles that overlap each other in the graph?

**Comment by GER-Jani** [comment]
> I assume you refer to RGBA and having transparency value. ARGB is usually referenced as a hardware implementation of the RGB :). This should be fairly easy to add, so you can expect it in the next version of Lab. Regarding the order, this could be resolved too, it just affects more than GSS and Lab - it will affect Orb too (https://github.com/memgraph/orb) where the rendering order happens. Good suggestion!

Glad to hear that. Both of these points would improve designing of larger graphs and reading visual information from it.

> @GER-Jani by the way in the meantime, I think this should be 6x times faster. Having a wrapper function for the `get_color_by_normalized_value` that receives a normalized value from the wrapper function `get_color`.

Very good improvement you have discovered there! Thanks, so v1.0.0 of my script now looks like this:

```
Define(follows_user_transition, Function(e, HasProperty(e, "user_ids")))
Define(get_num_user_ids, Function(e, Size(Property(e, "user_ids"))))
Define(get_all_follows_user_transition_sizes, Function(g, Map(Filter(Edges(g), follows_user_transition), Function(e, get_num_user_ids(e)))))
Define(min_num_user_ids, Function(g, Min(get_all_follows_user_transition_sizes(g))))
Define(max_num_user_ids, Function(g, Max(get_all_follows_user_transition_sizes(g))))
Define(get_normalized_num_user_ids, Function(g, e, Div(Sub(get_num_user_ids(e), min_num_user_ids(g)), Sub(max_num_user_ids(g), min_num_user_ids(g)))))
Define(heatmap_cold, #0000FF)
Define(heatmap_hot, #FF0000)
Define(get_color_by_normalized_num_user_ids, Function(normalized_num_user_ids, RGB(
  Floor(Add(Mul(Sub(1, normalized_num_user_ids), Red(heatmap_cold)), Mul(normalized_num_user_ids, Red(heatmap_hot)))),
  Floor(Add(Mul(Sub(1, normalized_num_user_ids), Green(heatmap_cold)), Mul(normalized_num_user_ids, Green(heatmap_hot)))),
  Floor(Add(Mul(Sub(1, normalized_num_user_ids), Blue(heatmap_cold)), Mul(normalized_num_user_ids, Blue(heatmap_hot))))
)))
Define(get_color, Function(g, e, get_color_by_normalized_num_user_ids(get_normalized_num_user_ids(g, e))))
Define(get_width, Function(g, e, Add(Mul(get_normalized_num_user_ids(g, e), 5), 1)))

@NodeStyle {
  size: 6
  color: #DD2222
  color-hover: Lighter(#DD2222)
  color-selected: Lighter(#DD2222)
  border-width: 0.6
  border-color: #1d1d1d
  font-size: 3
}

@NodeStyle HasLabel(node, "Training") {
  color: #5B5B5B
  color-hover: Lighter(#5B5B5B)
  color-selected: Lighter(#5B5B5B)
  label: AsText(Property(node, "title"))
}

@NodeStyle HasLabel(node, "User") {
  color: #005B09
  color-hover: Lighter(#005B09)
  color-selected: Lighter(#005B09)
  label: Format("User_ID: {}", Property(node, "id"))
}

@EdgeStyle {
  color: #999999
  color-hover: #1d1d1d
  color-selected: #1d1d1d
  width: 0.3
  width-hover: 0.9
  width-selected: 0.9
  font-size: 3
}

@EdgeStyle follows_user_transition(edge) {
  color: get_color(graph, edge)
  color-hover: get_color(graph, edge)
  color-selected: get_color(graph, edge)
  width: get_width(graph, edge)
  width-hover: get_width(graph, edge)
  width-selected: get_width(graph, edge)
  font-size: 3
  label: Format("({})", get_num_user_ids(edge))
}
```

I'm not a designer, so I don't know which colors harmonize well while highlighting information from a heatmap for readability, but from light green to red on a dark background works just fine as well. As far as I've looked through the documentation, there is no way to change the background color of the graph in the "Graph results" window, correct?

**Comment by tonilastre** [comment]
> As far as I've looked through the documentation, there is no way to change the background color of the graph in the "Graph results" window, correct?

No, there isn't. But it will be in the next Lab version along with other GSS improvements. There are other Lab fixes we are working on, but from the GSS side these features will be released:

* New functions `RGBA`, `HSLA`, `Alpha`
* New node and edge property `z-index` (sets stack order when rendering nodes/edges, similar to CSS z-index)
* Single-line and multi-line comments in the GSS (`//` and `/* ... */` - much easier to test multiple solutions within the same code editor)
* Background canvas color - a property in `@ViewStyle` called `background-color`.

The heatmap function won't be in the upcoming release, but it will be in some future ones. Additionally, we need to figure out the issues with recalculations (`graph` available in a global context or having some Cache utility for functions).

Btw regarding the colors, as you uploaded png images I really like how your graph looks on the dark background!

**Comment by vpavicic** [comment]
@GER-Jani Hi! :) Just wanted to let you know that the new Memgraph Lab is out with a lot of new features, especially regarding GSS! 

Here's the changelog PR, I'll merge it soon -> https://github.com/memgraph/docs/pull/940/files
And you can download the new Lab here -> https://memgraph.com/downloads#memgraph-lab

The Memgraph Platform still hasn't been built, but it will be by the end of the week or early next week, I'll let you know, but for now, you can use the Desktop App :)

**Comment by GER-Jani** [comment]
Hi @tonilastre

I'm playing around with the new features of Memgraph Lab v2.7.0. Thanks for adding my requests.

But I'm having trouble with the z-index on edges. My current experimental GSS:

<details><summary>GSS code</summary>

```
Define(follows_user_transition, Function(e, HasProperty(e, "user_ids")))
Define(get_num_user_ids, Function(e, Size(Property(e, "user_ids"))))
Define(get_all_follows_user_transition_sizes, Function(g, Map(Filter(Edges(g), follows_user_transition), Function(e, get_num_user_ids(e)))))
Define(min_num_user_ids, Function(g, Min(get_all_follows_user_transition_sizes(g))))
Define(max_num_user_ids, Function(g, Max(get_all_follows_user_transition_sizes(g))))
Define(get_normalized_num_user_ids, Function(g, e, Div(Sub(get_num_user_ids(e), min_num_user_ids(g)), Sub(max_num_user_ids(g), min_num_user_ids(g)))))
Define(heatmap_cold, #00FF00)
Define(heatmap_hot, #FF0000)
Define(get_color_by_normalized_num_user_ids, Function(normalized_num_user_ids, RGB(
  Floor(Add(Mul(Sub(1, normalized_num_user_ids), Red(heatmap_cold)), Mul(normalized_num_user_ids, Red(heatmap_hot)))),
  Floor(Add(Mul(Sub(1, normalized_num_user_ids), Green(heatmap_cold)), Mul(normalized_num_user_ids, Green(heatmap_hot)))),
  Floor(Add(Mul(Sub(1, normalized_num_user_ids), Blue(heatmap_cold)), Mul(normalized_num_user_ids, Blue(heatmap_hot))))
)))
Define(get_color, Function(g, e, get_color_by_normalized_num_user_ids(get_normalized_num_user_ids(g, e))))
Define(get_width, Function(g, e, Add(Mul(get_normalized_num_user_ids(g, e), 5), 1)))

@ViewStyle {
  background-color: #191919
}

@NodeStyle {
  size: 6
  color: #DD2222
  color-hover: Lighter(#DD2222)
  color-selected: Lighter(#DD2222)
  font-color: #3F3F3F
  border-width: 0.6
  border-color: #666666
  font-size: 3
}

@NodeStyle HasLabel(node, "Training") {
  color: #4F4F4F
  color-hover: Lighter(#4F4F4F)
  color-selected: Lighter(#4F4F4F)
  label: AsText(Property(node, "title"))
}

@NodeStyle HasLabel(node, "User") {
  color: #005B09
  color-hover: Lighter(#005B09)
  color-selected: Lighter(#005B09)
  label: Format("User_ID: {}", Property(node, "id"))
  z-index: 1
}

@EdgeStyle {
  color: #999999
  color-hover: #1d1d1d
  color-selected: #1d1d1d
  width: 0.3
  width-hover: 0.9
  width-selected: 0.9
  font-size: 3
  z-index: 1
}

@EdgeStyle follows_user_transition(edge) {
  color: get_color(graph, edge)
  color-hover: get_color(graph, edge)
  color-selected: get_color(graph, edge)
  width: get_width(graph, edge)
  width-hover: get_width(graph, edge)
  width-selected: get_width(graph, edge)
  font-size: 3
  label: Format("({})", get_num_user_ids(edge))
  z-index: 10
}
```
</details>

![gss_z_order](https://github.com/memgraph/memgraph/assets/9035100/a12c9774-2dc4-4304-8a9b-4ded33dfbbcd)

My goal is to get the edges with the 'follows_user_transition' style, which make use of the heapmap colors, into the front (highest z-index) and the no-name edges into the back.
But as you can see on my screenshot, I doesn't get the desired effect.
I tested the z-index function on nodes, there it works as expected.

Do you have any idea?

**Comment by vpavicic** [comment]
Hi @GER-Jani! Thank you so much for the feedback! Toni is on annual leave at the moment, but someone from the team will take a closer look at your issue tomorrow. :)

**Comment by tonilastre** [comment]
Hey @GER-Jani! Thanks for the feedback, I've just replicated the bug and it will be fixed in the new version - will let you know once it is released.

Btw, we would be happy to hear the feedback around the updates for more performant GSS - all of which is a result of your feedback - having `graph` variable globally available, the ability to use cache object (`Map`), and having local variables within `@NodeStyle` and `@EdgeStyle` directives.
You can see an example here that is heavily influenced by your initial heatmap feature: https://memgraph.com/docs/memgraph-lab/graph-style-script-language#caching-results-for-faster-performance

**Comment by GER-Jani** [comment]
Hi @tonilastre 
Regarding the performance updates, I hadn't even noticed them:
But this is exactly what I needed - having the graph variable globally available did the trick!

Now the heatmap can be applied to the entire graph without the browser is hanging. Switching between styles still take some time (around 7 seconds at 7,642 nodes and 161,922 edges) but I think that is acceptable.

Now I'm waiting for the z-index function fix and I can finish the heatmap appearance.

**Comment by tonilastre** [comment]
That's great to hear because it was 10 seconds for 200 nodes and 200 edges before. I am sure we can improve it even more, your use case is a good benchmark.

Btw, just checked your latest GSS code, and you can do one additional performance boost - using cache for local variables where this:

```
@EdgeStyle follows_user_transition(edge) {
  color: get_color(graph, edge)
  color-hover: get_color(graph, edge)
  color-selected: get_color(graph, edge)
  width: get_width(graph, edge)
  width-hover: get_width(graph, edge)
  width-selected: get_width(graph, edge)
  font-size: 3
  label: Format("({})", get_num_user_ids(edge))
  z-index: 10
}
```

becomes this:

```
@EdgeStyle follows_user_transition(edge) {
  Define(_color, get_color(graph, edge))
  Define(_width, get_width(graph, edge))

  color: _color
  color-hover: _color
  color-selected: _color
  width: _width
  width-hover: _width
  width-selected: _width
  font-size: 3
  label: Format("({})", get_num_user_ids(edge))
  z-index: 10
}
```

I don't think it will impact soo much, but now there is only one call for `get_color` and one call for `get_width` per edge.

**Comment by GER-Jani** [comment]
@tonilastre I know - and there is even more room for optimization.
When the z-index function on edges is working and I found a good visual style, I'll post an update of my cleaned code and graph outputs.

**Comment by tonilastre** [comment]
@GER-Jani Just want to update you that the new Lab has been released and it has both those fixes in (fixed `z-index` and using `_` for a variable name). Let me know how it works. :)

Full changelog: https://memgraph.com/docs/memgraph-lab/changelog#lab-v280---aug-04-2023

**Comment by GER-Jani** [comment]
Hi @tonilastre 
sorry for the late response. I'm back in the office, checked the bug fixes and cleaned up the project.

So here is the complete code:
<details><summary>Show GSS code</summary>

```
// Settings
Define(RENDER_FOLLOWS_USER_TRANSITION_SIZES, True)

// Functions
Define(follows_user_transition, Function(edge, HasProperty(edge, "user_ids")))
Define(get_number_of_user_ids, Function(edge, Size(Property(edge, "user_ids"))))
Define(get_number_of_user_ids_normalized, Function(edge, Div(Sub(get_number_of_user_ids(edge), GLOBAL_MIN_FOLLOWS_USER_TRANSITION_SIZES), GLOBAL_DIFF_FOLLOWS_USER_TRANSITION_SIZES)))
Define(get_color_by_normalized_number_of_user_ids, Function(number_of_user_ids_normalized, RGB(
  Floor(Add(Mul(Sub(1, number_of_user_ids_normalized), HEATMAP_COLD_R), Mul(number_of_user_ids_normalized, HEATMAP_HOT_R))),
  Floor(Add(Mul(Sub(1, number_of_user_ids_normalized), HEATMAP_COLD_G), Mul(number_of_user_ids_normalized, HEATMAP_HOT_G))),
  Floor(Add(Mul(Sub(1, number_of_user_ids_normalized), HEATMAP_COLD_B), Mul(number_of_user_ids_normalized, HEATMAP_HOT_B)))
)))
Define(get_color, Function(number_of_user_ids_normalized, get_color_by_normalized_number_of_user_ids(number_of_user_ids_normalized)))
Define(get_width, Function(number_of_user_ids_normalized, Add(Mul(number_of_user_ids_normalized, 5), 1)))

// Constants
Define(ALL_FOLLOWS_USER_TRANSITIONS, Filter(Edges(graph), follows_user_transition))
Define(ALL_FOLLOWS_USER_TRANSITION_SIZES, Map(ALL_FOLLOWS_USER_TRANSITIONS, Function(edge, get_number_of_user_ids(edge))))
Define(GLOBAL_MIN_FOLLOWS_USER_TRANSITION_SIZES, Min(ALL_FOLLOWS_USER_TRANSITION_SIZES))
Define(GLOBAL_MAX_FOLLOWS_USER_TRANSITION_SIZES, Max(ALL_FOLLOWS_USER_TRANSITION_SIZES))
Define(GLOBAL_DIFF_FOLLOWS_USER_TRANSITION_SIZES, Sub(GLOBAL_MAX_FOLLOWS_USER_TRANSITION_SIZES, GLOBAL_MIN_FOLLOWS_USER_TRANSITION_SIZES))
Define(NODE_DEFAULT_SIZE, 6)
Define(NODE_DEFAULT_BORDER_WIDTH, 0.6)
Define(NODE_DEFAULT_FONT_SIZE, 3)
Define(EDGE_DEFAULT_WIDTH, 0.3)
Define(EDGE_DEFAULT_WIDTH_HOVER, 0.9)
Define(EDGE_DEFAULT_WIDTH_SELECTED, 0.9)
Define(EDGE_FOLLOWS_USER_TRANSITION_FONT_SIZE, 8)
Define(EDGE_FOLLOWS_USER_TRANSITION_Z_INDEX, 1)

// Colors
Define(HEATMAP_BACKGROUND_COLOR, #0F0F0F)
Define(HEATMAP_COLD, #00FF00)
Define(HEATMAP_COLD_R, Red(HEATMAP_COLD))
Define(HEATMAP_COLD_G, Green(HEATMAP_COLD))
Define(HEATMAP_COLD_B, Blue(HEATMAP_COLD))
Define(HEATMAP_HOT, #FF0000)
Define(HEATMAP_HOT_R, Red(HEATMAP_HOT))
Define(HEATMAP_HOT_G, Green(HEATMAP_HOT))
Define(HEATMAP_HOT_B, Blue(HEATMAP_HOT))
Define(NODE_DEFAULT_COLOR, #DD2222)
Define(NODE_DEFAULT_COLOR_HOVER, Lighter(NODE_DEFAULT_COLOR))
Define(NODE_DEFAULT_COLOR_SELECTED, Lighter(NODE_DEFAULT_COLOR))
Define(NODE_DEFAULT_COLOR_BORDER, #666666)
Define(NODE_DEFAULT_FONT_COLOR, #3F3F3F)
Define(NODE_TRAINING_COLOR, #4F4F4F)
Define(NODE_TRAINING_COLOR_HOVER, Lighter(NODE_TRAINING_COLOR))
Define(NODE_TRAINING_COLOR_SELECTED, Lighter(NODE_TRAINING_COLOR))
Define(NODE_USER_COLOR, #005B09)
Define(NODE_USER_COLOR_HOVER, Lighter(NODE_USER_COLOR))
Define(NODE_USER_COLOR_SELECTED, Lighter(NODE_USER_COLOR))
Define(NODE_USER_FONT_COLOR, #005B09)
Define(EDGE_DEFAULT_COLOR, #999999)
Define(EDGE_DEFAULT_COLOR_HOVER, Lighter(EDGE_DEFAULT_COLOR))
Define(EDGE_DEFAULT_COLOR_SELECTED, Lighter(EDGE_DEFAULT_COLOR))
Define(EDGE_FOLLOWS_USER_TRANSITION_FONT_COLOR, #CCCCCC)


@ViewStyle {
  background-color: HEATMAP_BACKGROUND_COLOR
}

@NodeStyle {
  size: NODE_DEFAULT_SIZE
  color: NODE_DEFAULT_COLOR
  color-hover: NODE_DEFAULT_COLOR_HOVER
  color-selected: NODE_DEFAULT_COLOR_SELECTED
  border-width: NODE_DEFAULT_BORDER_WIDTH
  border-color: NODE_DEFAULT_COLOR_BORDER
  font-size: NODE_DEFAULT_FONT_SIZE
  font-color: NODE_DEFAULT_FONT_COLOR
}

@NodeStyle HasLabel(node, "Training") {
  color: NODE_TRAINING_COLOR
  color-hover: NODE_TRAINING_COLOR_HOVER
  color-selected: NODE_TRAINING_COLOR_SELECTED
  label: AsText(Property(node, "title"))
}

@NodeStyle HasLabel(node, "User") {
  color: NODE_USER_COLOR
  color-hover: NODE_USER_COLOR_HOVER
  color-selected: NODE_USER_COLOR_SELECTED
  font-color: NODE_USER_FONT_COLOR
  label: Format("User_ID: {}", Property(node, "id"))
}

@EdgeStyle {
  color: EDGE_DEFAULT_COLOR
  color-hover: EDGE_DEFAULT_COLOR_HOVER
  color-selected: EDGE_DEFAULT_COLOR_SELECTED
  width: EDGE_DEFAULT_WIDTH
  width-hover: EDGE_DEFAULT_WIDTH_HOVER
  width-selected: EDGE_DEFAULT_WIDTH_SELECTED
}

@EdgeStyle follows_user_transition(edge) {
  Define(_number_of_user_ids_normalized, get_number_of_user_ids_normalized(edge))
  Define(_color, get_color(_number_of_user_ids_normalized))
  Define(_width, get_width(_number_of_user_ids_normalized))

  color: _color
  color-hover: _color
  color-selected: _color
  width: _width
  width-hover: _width
  width-selected: _width
  font-size: EDGE_FOLLOWS_USER_TRANSITION_FONT_SIZE
  font-color: EDGE_FOLLOWS_USER_TRANSITION_FONT_COLOR
  z-index: EDGE_FOLLOWS_USER_TRANSITION_Z_INDEX
  label: If(RENDER_FOLLOWS_USER_TRANSITION_SIZES, Format("[{}]", get_number_of_user_ids(edge)), "")
}
```
</details>

Applying this on my custom dataset, the complete graph looks as follows:
<details><summary>See complete graph</summary>

![02_heatmap_full_selected_max_heatmap_follows_user_transition](https://github.com/memgraph/memgraph/assets/9035100/895d3412-6f79-49c6-a740-cae4ee4bdb1e)

</details>

With the working `z-index` function one can clearly spot the extrema in my graph.


If only the nodes that make use of the heatmap edges are queried, the resulting graph looks like this:
<details><summary>See heatmap graph</summary>

![03_heatmap_follows_user_transition](https://github.com/memgraph/memgraph/assets/9035100/93448226-bdb7-4f92-bd48-baa9e47c2f16)

</details>

Again, very easy to find the extrema.

Since the identified extrema from above is an outlier (compared to the rest of the property values), here are some examples of a query with a smaller set of resulting nodes and also some other heatmap color combinations for comparison:
<details><summary>See comparison (without rendering custom labels)</summary>

![alternative_3](https://github.com/memgraph/memgraph/assets/9035100/0eb75880-aad6-4a79-9cf4-e2c4ac5c6936)

![alternative_2](https://github.com/memgraph/memgraph/assets/9035100/8a1d7225-6e17-4a44-ac20-06677143c241)

![alternative_1](https://github.com/memgraph/memgraph/assets/9035100/0788a8e9-d285-490c-9ccb-a07ca883fe1d)

</details>

Enabling the `RENDER_FOLLOWS_USER_TRANSITION_SIZES` option of my GSS on this examples, the visual readability is affected by the labels:
<details><summary>See comparison (with rendering custom labels)</summary>

![alternative_6](https://github.com/memgraph/memgraph/assets/9035100/b1d6f8c9-2b9b-4d4f-8f66-afba942dfeab)

![alternative_5](https://github.com/memgraph/memgraph/assets/9035100/d033b2f7-b9b1-4d70-be80-8b7e17ccfb1e)

![alternative_4](https://github.com/memgraph/memgraph/assets/9035100/b896831f-a2f6-44a2-9d1f-4e7960d11489)

</details>

Therefore, it will probably depend on the usage which color scheme and rendering option should be applied.
If someone found a better visual color scheme for all nodes, please let me know :)


If I would share my code:
Well, I already shared my code here, so I could also share it in a GSS-repository. But this code is currently very application specific. Anyway, it would also be very interesting to see what other people realized just by applying custom graph styles.

What can you improve to make GSS easier to use:
I think I work on too few projects to be able to write a more profound answer here. But you could definitely increase the readability of GSS code enormously if you would implement the use of basic mathematical operators in symbol form instead of the need to explicitly call its functions.
Aside from that, sometimes some style format mistakes can be found in the documentation, like [here](https://memgraph.com/docs/memgraph-lab/graph-style-script-language#caching-results-for-faster-performance) for example.

I think that's it so far :)

**Comment by GER-Jani** [comment]
OK, there is one more feature, which would be really neat:

The possibility to save a graph as a vector graphic!  
I know it's not GSS related, but I think it's worth mentioning here :)

**Comment by GER-Jani** [comment]
Hi @tonilastre 
any news about the feedback?

**Comment by tonilastre** [comment]
Hi @GER-Jani, sorry for the late response. :)

Just to get back to your screenshots and the GSS code. That is a really good sample of code and the results look astonishing. Personally, I like the green+red on the black background. Really gives a good contrast and outlines the outlines.

> If I would share my code:
Well, I already shared my code here, so I could also share it in a GSS-repository. But this code is currently very application-specific. Anyway, it would also be very interesting to see what other people realized just by applying custom graph styles.

Yep, you are 100% right. This is app-specific. We are thinking about having "modules" in GSS where you can create a module that you export with config + functions that anyone can use. This is still in the works, we are thinking about how to format that but also make it usable/shareable and easily extendable. As you are an experienced GSS user, we will get back to you once we have something.

> What can you improve to make GSS easier to use:
I think I work on too few projects to be able to write a more profound answer here. But you could definitely increase the readability of GSS code enormously if you would implement the use of basic mathematical operators in symbol form instead of the need to explicitly call its functions.

This is a great suggestion! It also fits the need for having arrays as `[x, y, z]` rather than `AsArray(...)`.

> Aside from that, sometimes some style format mistakes can be found in the documentation, like [here](https://memgraph.com/docs/memgraph-lab/graph-style-script-language#caching-results-for-faster-performance) for example.

Thanks for the link. We will check it out and fix it! ;)

> The possibility to save a graph as a vector graphic! I know it's not GSS related, but I think it's worth mentioning here :)

Thanks for sharing it. Is there a specific need for why vector? Currently, Lab draws objects on the canvas, so raster (PNG/JPEG export) is a default export that will be done. Does it have to do with an ability to zoom in/out without impacting quality?

**Comment by GER-Jani** [comment]
Thank you for your feedback @tonilastre.

> Is there a specific need for why vector? Currently, Lab draws objects on the canvas, so raster (PNG/JPEG export) is a default export that will be done. Does it have to do with an ability to zoom in/out without impacting quality?

Okay, let me ask it this way:
Is there already a way to export a graph in general?

The Memgraph Lab standalone version doesn't provide any way to save a graph visually. The "Download Results" button only gives me the options to store data in .json, .csv and .tsv.  
Using a browser like Chrome can save an image as .png but only of the visible section. To save a larger graph as a whole, you have to zoom out, which of course reflects in the image quality and the labels are no longer readable.
That's why I thought vector graphics would be the best option here. Other options are also welcome.

**Comment by tonilastre** [comment]
I am glad I asked because we planned to add an action to export a graph soon, but it would work just like browser tools work, giving the visible part of the view.
Your perspective makes perfect sense too because you can get the full image on a custom zoom level. Now we are thinking about having two options: just visible view or full view. :)

**Comment by GER-Jani** [comment]
I just wonder how often it happens that someone wants to save only a part of a graph as an image, instead of the whole graph, for example to present it either conveniently as a vector graphic or even printed out to a customer :D

**Comment by tonilastre** [comment]
Actually, it was our initial request, just the visible part of the graph.

Some users tend to use "expand" and "collapse" to traverse the graph via UI, and once they are satisfied with the findings they wanna take a screenshot of that visible part of the graph - we've seen this kind of usage is fraud detection cases where they are focused on a subgraph rather than the whole graph that is out there.

**Comment by katarinasupe** [comment]
Hi @GER-Jani, it is great to see you're utilizing GSS to style your graph! Thank you for your suggestions and for opening an issue/discussion. To keep track of the newly added features and quicker conversation with the team, feel free to [join the conversation on our Discord server](https://www.discord.gg/memgraph). Developer experience team is hanging out there and we are more than happy to hear about your Memgraph experience and help out if needed.
