### ISSUE TITLE
SHOW TRANSACTIONS hangs on the long running LOAD CSV

### ISSUE THREAD

**Issue by gitbuda** [memgraph/memgraph#884]
@antoniofilipovic, please attach more info once you can recreate it 🙏

**Comment by katarinasupe** [comment]
@antoniofilipovic any update on this issue?

**Comment by as51340** [comment]
Yes, I couldn't recreate the issue several times so not sure what is happening. I think we can close this issue for now and reopen it if someone manages to recreate.

**Comment by katarinasupe** [comment]
Closing for now since we did not manage to reproduce. We will reopen it if there are more reports like this one.
