### ISSUE TITLE
Fix queries causing null pointer dereferences

### ISSUE THREAD

**Issue by DominicWuest** [memgraph/memgraph#887]
## Memgraph version
v.2.7.0

## Environment
I used the **memgraph:2.7.0** docker image.

## Describe the bug
A few queries result in a crash due to a null pointer dereference.

## To Reproduce
Run any of the following queries against an empty database and observe they crash the server:
```cypher
DELETE null
```
```cypher
DETACH DELETE null
```
```cypher
REMOVE startNode(null).A
```
```cypher
SET startNode(null).A = 0
```

## Expected behavior
The query should run successfully and cause no side effects.

**Comment by imilinovic** [comment]
This was fixed at one point and does not happen in Memgraph 2.13.
