### ISSUE TITLE
Async replica not working correctly

### ISSUE THREAD

**Issue by katarinasupe** [memgraph/memgraph#889]
Here is the reported error on the async replica:

```
Assertion failed in file /memgraph/src/storage/v2/storage.cpp at line 514.
    Expression: 'inserted'
    Message: 'The vertex must be inserted here!'
```

The above causes the replica to continue to restart. The primary is accepting and processing new batches without issues.

Related to: [Discord conversation](https://discord.com/channels/842007348272169002/890968055339958292/1098336874466123847)

**Comment by DavIvek** [comment]
It would be great if the user could verify if this is still an issue. A lot happened after the user posted this issue. For example, this logic isn't anymore in the same file as he reported. Also, it is hard to work on this without a dataset or a query to recreate mentioned error.

**Comment by DavIvek** [comment]
Closed due not being able to replicate
