### ISSUE TITLE
Implement return feedback on LOCK/UNLOCK DATA DIRECTORY query

### ISSUE THREAD

**Issue by gitbuda** [memgraph/memgraph#891]
Using the (UN)LOCK DATA DIRECTORY query is hard at the moment as Memgraph returns no feedback about the lock status: 
I propose the following messages: 

1. LOCK DATA DIRECTORY; - upon success, should return: Data directory is now locked.
2. UNLOCK DATA DIRECOTRY; - upon success should return: Data directory is now unlocked.
3. When you try to run LOCK DATA DIRECTORY on a locked data directory, the following message should be returned: Data directory is already locked.
4. When you try to run UNLOCK DATA DIRECTORY on an unlocked data directory, the following message should be returned: Data directory is already unlocked. 
(ATM it says" Failed to unlock the directory" and i had a mini heart attack)

Also to provide more control and information, I propose a new query
DATA DIRECTORY LOCK STATUS: 
that will return the info if the data directory is locked or unlocked

**Comment by vpavicic** [comment]
I've added the proposal for enhancing the (UN)LOCK DATA DIRECTORY query
