### ISSUE TITLE
SetProperties working poorly when there is a lot of indexes

### ISSUE THREAD

**Issue by Josipmrden** [memgraph/memgraph#909]
**Memgraph version**
v2.7

**Environment**
Docker

**Describe the bug**
If there is 400 indexes in the database, SetProperties operator behaves poorly because it needs to update all the indexes. Update of indexes in the system is done sequentially via a for loop currently. There should be a smarter way to set properties and check which values need to be updated.

**To Reproduce**
1. Create 350 indexes
2. `FOREACH (i in range (1, 10000) | CREATE (:A1 {id: i}));` -> for every index
3. Try setting properties in bulk for 10 000 items

Expected:
It should be quick

Actual:
It is slow.

**Comment by gitbuda** [comment]
TODO(@Josipmrden): Link map literal stuff
