### ISSUE TITLE
[BUG] Reading deltas for supernodes is slow although deltas don't modify labels or properties

### ISSUE THREAD

**Issue by Josipmrden** [memgraph/memgraph#918]
**Memgraph version**
v2.7

The query looks something like this:

```
LOAD CSV ...
MATCH (node...), (supernode)
MERGE (node)-[:SOME_EDGE]->(supernode);
```
this query is problematic because for every line in the CSV, supernode will be matched, and every time an incoming edge is added to the supernode, it increases the amount of deltas. Problem with this is that it slows the MATCH quadratically with respect to the number of lines.

**Comment by Josipmrden** [comment]
Steps to reproduce:

// set storage_gc_cycle_sec=1800 to be sure that you only run GC by force

CREATE INDEX ON :Node;
CREATE INDEX ON :Node(id);
CREATE INDEX ON :Supernode;
CREATE INDEX ON :Supernode(id);

UNWIND range(1, 1000000) as id CREATE (:Node {id: id});
CREATE (:Supernode {id:1})

free memory; // with or without this (if you do this on the PR that should solve this issue, it should be super quick -> T634)

profile unwind range(1, 1000000) as id
match (node:Node {id: id}), (supernode:Supernode {id: 1})
with node, supernode
limit 50000
merge (supernode)<-[:TYPE]-(node);

**Comment by gitbuda** [comment]
This might be fixed with the cache improvements (the 100% CPU issue -> https://github.com/memgraph/memgraph/issues/865) -> check once it's done 👀
