### ISSUE TITLE
Enable the snasphots to be inserted durting creation of Memgraph container

### ISSUE THREAD

**Issue by antejavor** [memgraph/memgraph#926]
Moving the snapshot (target)  from old docker container to another (fresh one), requires running the fresh container, copying the target snapshot file, and restarting the container.  This can cause the creation of an even newer snapshot while the container is restarted or the creation of a new snapshot file while the target file is being copied. This can be influenced by the `--storage-snapshot-on-exit=true` and `--storage-snapshot-interval-sec=300` 

Enabling the injection of the snapshot file after the creation of the container will mitigate this issue.  
Currently, first creating a container (docker create ...) , copying the snapshot file, and starting the container (docker start ...) , results in an issue: 
![image](https://user-images.githubusercontent.com/18125448/236783215-1754d1e0-ed2f-420d-84d1-297d9599847e.png)

**Comment by antejavor** [comment]
Docker containers share the same Linux kernel with the host system. So you can’t have different users (different privileges) with the same uid inside different containers. They all relate to the same user from host's and docker's perspective.
 
This means that different usernames are possible because they relate to the same users on the host and docker container, but if IDs are identical, they are the same users. 
So **host : root(id = 0) == docker : root(id = 0)**  and host memgraph(id=101) == docker: memgraph_docker_user(101). 

Example:
 
```
maple@big-bang:~$ docker run -d ubuntu:latest sleep infinity
maple@big-bang:~$ ps aux | grep docker
root      652817  0.0  0.0   2788  1020 ?        Ss   13:08   0:00 sleep infinity
```

The process is started as root for OS perspective since it is root in the container. User Maple has root privileges to run docker. Hence it is always better and recommended to run containers as non-root users. To avoid privilege escalation on the host, context: https://docs.docker.com/engine/security/userns-remap/ 

Example 2. 

```
maple@big-bang:~$ id maple
uid=1000(maple) gid=1000(maple) groups=1000(maple),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),122(lpadmin),134(lxd),135(sambashare),999(docker)
maple@big-bang:~$ docker run -d -u 1000:1000  ubuntu:latest sleep infinity
e21537f010e0c009d904442e5c97e7622141754f2025362e76d73b71e4ae55cc
maple@big-bang:~$ ps aux | grep sleep
root      652817  0.0  0.0   2788  1020 ?        Ss   13:08   0:00 sleep infinity
maple     653227  0.2  0.0   2788  1000 ?        Ss   13:25   0:00 sleep infinity
maple@big-bang:~$ docker exec -it e21537f010e0c bash
groups: cannot find name for group ID 1000
I have no name!@e21537f010e0:/$
```
The process is now started as user Maple, OS sees it that way, since the uid:gid is 1000:1000. Inside the container, the user does not have a name, but from kernel/host perspective, it is the same Maple user with the same privileges.

**Comment by gitbuda** [comment]
Create a matrix of possible host/container states (users present in both)

Let's try to do the following (from user's perspective):
1. create user `memgraph` on host
2. pass snapshot during the `docker run` command

**Comment by antejavor** [comment]
Syncing users between host and docker is a bit cumbersome. 

The possible solution is: 
```
docker create -p 7687:7687 -u memgraph:memgraph -v SNAPSHOTS:/var/lib/memgraph/snapshots --name memgraphDB-new memgraph/memgraph
tar -cf - 20230505103724411056_timestamp_3 --mode u=+r,g=-rwx,o=-rwx --owner memgraph --group memgraph | docker cp -a  - memgraphDB-new:/var/lib/memgraph/snapshots
docker start -a memgraphDB-new
```
This will inject the right file into the container with proper rights, it remains to change snapshot dir rights to memgraph user.
