### ISSUE TITLE
All shortest paths using a lot of memory

### ISSUE THREAD

**Issue by antoniofilipovic** [memgraph/memgraph#951]

**Comment by antoniofilipovic** [comment]
All shortest paths algorithm is using more memory than needed for path generation.

**Comment by katarinasupe** [comment]
Waiting for the dataset to reproduce the issue. @antoniofilipovic and I saw a lot of memory being used on a call but did not manage to reproduce it yet.

**Comment by antoniofilipovic** [comment]
@katarinasupe Basically any dataset provided will show that we are using a lot of memory. I was able to recreate issue and there is one fix, we need to benchmark this more to see if solution is correct one

**Comment by gitbuda** [comment]
Should be done in #923. Closing this issue 😃
