### ISSUE TITLE
Improve replication logging

### ISSUE THREAD

**Issue by gitbuda** [memgraph/memgraph#953]
The first thing is to improve replication logging to understand what is happening from high-level perspective. 

NOTE: run everything on a cluster

Next steps: 
* `WalFile::Finalize` -> no error handling for WAL copy
* Check for logical errors with deletes -> create social network graph and randomly delete an edge in the graph
* Measure IOPS on all these workloads for both local SSD and Cloud disks

**Comment by antejavor** [comment]
This is a prerequisite to most replication issues, reported by the community on multiple sides.

**Comment by antejavor** [comment]
@gitbuda Logging is a prerequisite for fixing these issues. We should split this into multiple issues: 

To be exact: 

1. Check for logical errors with deletes -> create a social network graph and randomly delete an edge in the graph
2. Measure IOPS on all these workloads for both local SSD and Cloud disks
3. WalFile::Finalize -> no error handling for WAL copy
