### ISSUE TITLE
Fix `SHOW STORAGE INFO;` is showing wrong vertex count constantly (GC maybe has a bug)

### ISSUE THREAD

**Issue by gitbuda** [memgraph/memgraph#957]
After importing data from https://drive.google.com/file/d/1lnwPwQzdlMBlSiKItZuRC58GeD6dLPMT/view?usp=sharing
and running the following query
```
MATCH (p:Post)
WITH localDateTime() - p.indexedAt as duration, p
WITH duration.day as days, p
WHERE days > 2
DETATCH DELETE p;
```
Memory usage + the `SHOW STORAGE INFO;` doesn't show correct data.
Maybe that's only visible while other data is streaming in, the instructions on how to run the streaming importer follow:
```
install ts-node (and dependencies)
git clone https://github.com/memgraph/bluej
cd into dir
npm install
ts-node src/index.ts
```

**Comment by Ignition** [comment]
After being perplexed for a while I was able to distill it down to minimal reproducible testcase.

Reproducible testcase, `vertex_count` does not ever forget this vertex
```cypher
STORAGE MODE IN_MEMORY_ANALYTICAL;
MERGE (n) DELETE n;
```

Yet these are fine, `vertex_count` is corrected after garbage collection
```cypher
STORAGE MODE IN_MEMORY_TRANSACTIONAL;
MERGE (n) DELETE n;

STORAGE MODE IN_MEMORY_TRANSACTIONAL;
MERGE ();
STORAGE MODE IN_MEMORY_ANALYTICAL;
MATCH (n) DELETE n;

STORAGE MODE IN_MEMORY_ANALYTICAL;
MERGE ();
STORAGE MODE IN_MEMORY_TRANSACTIONAL;
MATCH (n) DELETE n;
```
