### ISSUE TITLE
Implement point() as an awesome_memgraph_function

### ISSUE THREAD

**Issue by gvolfing** [memgraph/memgraph#984]
point({longitude | x, latitude | y [, crs][, srid]}) should return a 2D point,
point({longitude | x, latitude | y, height | z, [, crs][, srid]}) should return a 3D point,
in the WGS 84 CRS corresponding to the given coordinate values.

point({x, y [, crs][, srid]}) should return a 2D point,
point({x, y, z, [, crs][, srid]}) should return a 3D point,
in the Cartesian CRS corresponding to the given coordinate values.

Neo's specification:
https://neo4j.com/docs/cypher-manual/current/functions/spatial/#functions-point-wgs84-2d

**Comment by katarinasupe** [comment]
Just a small comment, we had a user asking for this feature, so I think it's a good one 😄

**Comment by gitbuda** [comment]
@imilinovic very similar (https://github.com/memgraph/memgraph/issues/985#issuecomment-2298994468) here (point is done 💪) 😄

**Comment by imilinovic** [comment]
Done under [PR](https://github.com/memgraph/memgraph/pull/2208)
