### ISSUE TITLE
Implement distance() as an awesome_memgraph_function

### ISSUE THREAD

**Issue by gvolfing** [memgraph/memgraph#985]
distance() should return a floating point number representing the geodesic distance between two points in the same Coordinate Reference System (CRS).

Add support for point.distance() as well.

-    If the points are in the Cartesian CRS (2D or 3D), then the units of the returned distance will be the same as the units of the points, calculated using Pythagoras' theorem.
-    If the points are in the WGS-84 CRS (2D), then the units of the returned distance will be meters, based on the haversine formula over a spherical earth approximation.
-   If the points are in the WGS-84 CRS (3D), then the units of the returned distance will be meters.
       - The distance is calculated in two steps.
           - First, a haversine formula over a spherical earth is used, at the average height of the two points.
           - To account for the difference in height, Pythagoras' theorem is used, combining the previously calculated spherical distance with the height difference.
       - This formula works well for points close to the earth’s surface; for instance, it is well-suited for calculating the distance of an airplane flight. It is less suitable for greater heights, however, such as when calculating the distance between two satellites.

Neo's specification:
https://neo4j.com/docs/cypher-manual/4.3/functions/spatial/#functions-distance

**Comment by antepusic** [comment]
Before this issue can be done, we would need to add the `POINT` data type to Memgraph since the described function operates on values of that type.

**Comment by gitbuda** [comment]
I think this is done under https://github.com/memgraph/memgraph/pull/2208 -> @imilinovic if yes, feel free to close this issue. Furthermore, link the closing PR under https://github.com/memgraph/memgraph/issues/1007 because it also helps on the GraphQL compatibility side 😄

**Comment by imilinovic** [comment]
Yes, done under [PR2208](https://github.com/memgraph/memgraph/pull/2208)
